### ISSUE TITLE
Automatic upload of Proguard mapping files for different app modules

### ISSUE THREAD

**Issue by username4564** [getsentry/sentry-android-gradle-plugin#1]
Want set different defaults.project value for different app modules.
How provide sentry.properties for app module dir instead of rootProject dir?

As work around i do this:
1. create stub sentry.properties in rootProject dir
2. in app gradle - create new task depended on "persistSentryProguardUuidsFor*" which write required params in sentry.properties

**Comment by marandaneto** [comment]
probably same as #5

**Comment by marandaneto** [comment]
Duplicate of #5
