### ISSUE TITLE
Add Gradlle 7+ support

### ISSUE THREAD

**Issue by Stuart-campbell** [getsentry/sentry-android-gradle-plugin#101]
_Android Gradle Plugin:_
**7.0.0-alpha15**

_Gradle:_
**7.0**

_Optimizer:_
- [ ]  ProGuard
- [x]  R8

_Have you created the sentry.properties file?_
- [x]  Yes -> where?
- [ ]  No

_SDKs:_
- [x]  sentry-android -> which version?
- [ ]  sentry-react-native -> which version?

---
I have the following issue:

The plugin is incompatible with Gradle 7

**Steps to reproduce:**
- Attempt to build project with Android Studio Canary 15+ using Gradle 7+

**Actual result:**
```
A problem was found with the configuration of task ':app:addSentryProguardSettingsForLiveRelease' (type 'SentryProguardConfigTask').
  - Type 'SentryProguardConfigTask' property 'applicationVariant' is missing an input or output annotation.
 ```

**Expected result:**
- Build successful

**Comment by marandaneto** [comment]
dup https://github.com/getsentry/sentry-android-gradle-plugin/issues/70
