### ISSUE TITLE
Use Kotlin 1.3 instead of 1.4

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android-gradle-plugin#104]
Right now we're using Kotlin 1.4, we need to be sure that we're not writing incompatible code with 1.3 or to pin Kotlin 1.3 compatibility using `languageVersion`, the reason is https://github.com/gradle/gradle/issues/16345

cc @cortinico

**Comment by cortinico** [comment]
So I believe this depends on how many older versions of Gradle this tool should support.
I'm in for sticking to Gradle 6.8+, Kotlin 1.4.x+ and so on and asking people to update their Kotlin/Gradle versions accordingly (other tools in the ecosystem are doing the same).

> we need to be sure that we're not writing incompatible code with 1.3 or to pin Kotlin 1.3 compatibility using languageVersion

I'm not entirely sure, but I believe that's irrelevant. We anyway ship with an implicit dependency to `kotlin-stdlib` 1.4.x (introduced with the Kotlin Gradle Plugin). We would have to change that dependency to be a `compileOnly`. 

I'm unsure that's even worth the effort.

**Comment by marandaneto** [comment]
as long as it's not breaking if an App project is using Kotlin 1.3.x and our Plugin Kotlin 1.4.x, we are fine, about the min. Gradle version, it depends on the min. supported AGP version, so it should not be a problem if using AGP 4.x and Gradle 6.1.x
https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/.github/workflows/test-publish-dry-run.yaml#L21-L22

**Comment by cortinico** [comment]
> as long as it's not breaking if an App project is using Kotlin 1.3.x and our Plugin Kotlin 1.4.x, we are fine, about the min.

As long as we align with the bundled version in the latest Gradle version, we're good to go.
We could create annoyance for users of older versions of Gradle as they will see a warning of a version mismatch, but other popular Gradle plugins are also following the same approach. So I don't think this is going to be a major problem.

**Comment by marandaneto** [comment]
sounds good, let's keep this issue open and if we see this becomes an issue, we work on it.
