### ISSUE TITLE
sentry-debug-meta.properties not present when the apk is built via bitrise

### ISSUE THREAD

**Issue by Shilaghae** [getsentry/sentry-android-gradle-plugin#105]
_Android Gradle Plugin:_
**4.1.3**

_Gradle:_
**6.5**

_Optimizer:_
- [ ]  ProGuard
- [ x]  R8

_Have you created the sentry.properties file?_
- [ x]  Yes -> Same level of app
- [ ]  No

_SDKs:_
- [ x]  sentry-android -> 4.3.0
- [ ]  sentry-react-native -> which version?

---
I have the following issue:
When I build the apk locally I the mapping file for proguard is correctly uploaded on sentry, I use the sentry gradle plugin with autoUpload enabled, and I can also see that the io.sentry.ProguardUuids is in the intermediates/merge_assets/release or qa/out/sentry-debug-meta.properties while when I build the apk via bitrise the file is not present in the apk generated and I get:

```
> Task :app:stripQaDebugSymbols
Unable to strip the following libraries, packaging them as they are: libsentry-android.so, libsentry.so.

> Task :app:minifyQaWithR8
R8: Missing class: org.conscrypt.ConscryptHostnameVerifier

> Task :app:persistSentryProguardUuidsForQaQa
> compressing mappings
> uploading mappings
> Uploaded a total of 0 new mapping files
```

which makes me think that the sentry plugin works, I am wondering if bitrise create a different structure of the project and maybe the merge_assets are under a different folder. Any suggestion about how to solve this problem? The end result is that I can't deobfuscate in sentry and I also get the warning **Some frames appear to be minified. Did you configure the Sentry Gradle Plugin?**
In Bitrise I use the common **Android Build Step 0.10.3**

**Comment by marandaneto** [comment]
already answered in the other repo, please open the issue only in one place.
