### ISSUE TITLE
The issue line is different from the line of code.

### ISSUE THREAD

**Issue by jhamin0511** [getsentry/sentry-android-gradle-plugin#11]
I have set up Senty Android SDK in my project. (https://blog.sentry.io/2019/12/10/new-android-sdk-how-to)

I installed the plugin and checked the mapping file.

![image](https://user-images.githubusercontent.com/23713053/78092980-25278d00-740c-11ea-9bae-f52f5f72bb07.png)

However, the test exception issue line number is different from my code number.

![image](https://user-images.githubusercontent.com/23713053/78093158-88192400-740c-11ea-9eb6-a52a41854f1b.png)

The line number of the issue is 9, but the actual exception code number is 82 lines.

I don't know why it is recorded differently.

**Comment by marandaneto** [comment]
hey @jhamin0511 thanks for reporting this issue.
I believe it's a duplicated of https://github.com/getsentry/rust-proguard/issues/6

Would you mind disabling Proguard/R8 and see if the line numbers are correct?

We're gonna work on a fix for `getsentry/rust-proguard/issues/6` asap.
Thanks.

**Comment by marandaneto** [comment]
hey @jhamin0511 do you have any updates? :)

**Comment by jhamin0511** [comment]
Not yet. I keep getting number line errors.

**Comment by marandaneto** [comment]
ok, please subscribe -> https://github.com/getsentry/rust-proguard/issues/6
I'm going to close this one as it's duplicated, thanks.
