### ISSUE TITLE
Make SentryUploadProguardMappingsTask a @CacheableTask

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android-gradle-plugin#117]
inspired by https://github.com/remcomokveld/sentry-android-gradle-plugin/commit/8cfbf31e2af0173e47ff79c25a75fa01c145a78a

**Comment by marandaneto** [comment]
by doing that, we don't need to generate a new uuid on `SentryGenerateProguardUuidTask` every time probably, but rather setting proper dependency using:

`variant.mergeAssetsProvider.configure { it.dependsOn(uploadSentryProguardMappingsTask) }`

as the file is created on the assets folder by sentry-cli

**Comment by cortinico** [comment]
> Make SentryUploadProguardMappingsTask a @CacheableTask

I'm not entirely sure about this. I would not make `SentryUploadProguardMappingsTask` because is a `Exec` task. It has no output and you actually want the task to be execute the CLI whenever you invoke it. Or am I missing something? 🤔

**Comment by marandaneto** [comment]
previously, plugin 1.x, `sentry-cli` was creating the file with the `uuid` only when needed, if the file existed and the hash was the same, it'd not generate a new one, this had a bug due to not using proper Gradle APIs.

today, we write a file with a new `uuid` every time, this has a cost, even though not much I guess.

if we go this path, we can go back to the previous implementation and make the task cacheable, its an improvement, but not a bug or something.

it'd not cause the bug though cus we'd be setting the tasks accordingly using the `mergeAssetsProvider` which is where we create the file with the `uuid`

**Comment by cortinico** [comment]
> today, we write a file with a new `uuid` every time, this has a cost, even though not much I guess.
> if we go this path, we can go back to the previous implementation and make the task cacheable, its an improvement, but not a bug or something.

Ok I think there was a misunderstanding as the task to be cached is then `SentryGenerateProguardUuidTask`

**Comment by marandaneto** [comment]
@cortinico yes and no, the idea is that `SentryGenerateProguardUuidTask` would not even exist anymore, as the uuid would be created by `sentry-cli` again as before and not the plugin

**Comment by cortinico** [comment]
> as the uuid would be created by `sentry-cli` again as before and not the plugin

I see. But still, imho the `SentryUploadProguardMappingsTask` should not be cacheable. The UUID creation can be delegated to another task (i.e. `SentryGenerateProguardUuidTask`) and that task can be cached. But the CLI action should not, simply because it does not produce an output but only a side effect (the cli invocation).

**Comment by marandaneto** [comment]
yep, agreed, just trying to understand if it makes sense to cache `SentryGenerateProguardUuidTask` as well as its generating a `uuid` every time anyway, so obviously, it cannot be cached as it changes every time.

**Comment by cortinico** [comment]
> yep, agreed, just trying to understand if it makes sense to cache `SentryGenerateProguardUuidTask` as well as its generating a `uuid` every time anyway, so obviously, it cannot be cached as it changes every time.

The logic of `SentryGenerateProguardUuidTask` is pretty trivial, so we can definitely move its taskAction and merge it with the `SentryUploadProguardMappingTask` so the plugin will add one less task to the graph.

Regardless, I believe there is not much caching that can be done due to the nature of the plugin.

**Comment by marandaneto** [comment]
its a good idea :)

**Comment by cortinico** [comment]
> its a good idea :)

Actually the only thing that I'm unsure is how about task dependencies. Currently `SentryGenerateProguardUuidTask` runs before mergeAssets. I'm unsure if merging the two tasks will make sure that the `.properties` is merged correctly in the final APK/AAB.

**Comment by marandaneto** [comment]
> > its a good idea :)
> 
> Actually the only thing that I'm unsure is how about task dependencies. Currently `SentryGenerateProguardUuidTask` runs before mergeAssets. I'm unsure if merging the two tasks will make sure that the `.properties` is merged correctly in the final APK/AAB.

yeah, makes sense, let's keep as it is for now then because its well tested already as it is and if making it Cacheable won't bring any noticeable value, it's not worth doing it now, this Plugin will grow in feature so we can always do it later when it would make more sense, lets sleep on it.

**Comment by marandaneto** [comment]
since there were no complaints so far, closing it, worst case we can resurvive this issue
