### ISSUE TITLE
Task :app:persistSentryProguardUuidsForReleaseRelease FAILED

### ISSUE THREAD

**Issue by thefinnomenon** [getsentry/sentry-android-gradle-plugin#12]
I am using React-Native and my Android release builds fine without R8 enabled but fails with the following when it (or ProGuard) enabled,

```
> Task :app:persistSentryProguardUuidsForReleaseRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:persistSentryProguardUuidsForReleaseRelease'.
> A problem occurred starting process 'command 'node_modules/@sentry/cli/bin/sentry-cli''
```

I already followed the Sentry Android ProGuard guide using
`classpath("io.sentry:sentry-android-gradle-plugin:1.7.33")`
and not sure what else to do.

**Comment by marandaneto** [comment]
@thefinnomenon hey, thanks for raising this issue.
It'd be nice to know your `AGP`, `Gradle`, `sentry-react-native` and `react-native` versions so we can investigate it, thanks.

**Comment by thefinnomenon** [comment]
@marandaneto 

Of course, 
AGP: v3.4.2
Gradle: v5.5
sentry-android-gradle-plugin: v1.7.33
@sentry/react-native: v1.3.6
react-native: v0.61.5

Let me know if you need any more info. I ran the build with Sentry's debug logs enabled but it didn't provide any more insight into the issue.

**Comment by marandaneto** [comment]
@thefinnomenon I've tested it and it worked just fine for me.
https://docs.sentry.io/clients/java/integrations/#proguard

Have you applied the gradle plugin in the app's `build.gradle`, right?
`apply plugin: 'io.sentry.android.gradle'`

Have you also created the `sentry.properties` file in the root of the Android project?
eg:
```
react-native-project
    android
    ios
    node_modules
```

this file should be in:
```
react-native-project
    android/sentry.properties
```

the content of this file should look like:

```
defaults.project=your_project
defaults.org=your_org
auth.token=YOUR_AUTH_TOKEN
```

I believe that's the issue, let me know.

**Comment by thefinnomenon** [comment]
@marandaneto 

Yeah I double checked and have everything setup the way the guide says and you reiterated here but it is still giving me the same issue.

android/build.grade
```
buildscript {
    ...
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath("io.sentry:sentry-android-gradle-plugin:1.7.30")
    }
}
```
I also tried v1.7.33.

android/app/build.grade
```
apply plugin: "com.android.application"
apply plugin: "io.sentry.android.gradle"
...
```

android/sentry.properties
```
defaults.url=https://sentry.io/
defaults.org=<ORG>
defaults.project=<PROJECT>
auth.token=<AUTHTOKEN>
cli.executable=node_modules/@sentry/cli/bin/sentry-cli
```

Should I leave this line in android/app/build.grade?
```
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
```

I ran the build with logging and stacktraces enabled but it really doesn't give me any helpful information. I can see the following in app/build/intermediates/sentry/sentry.pro
```
-keepattributes LineNumberTable,SourceFile
-dontwarn com.facebook.fbui.**
-dontwarn org.slf4j.**
-dontwarn javax.**
-keep class * extends java.lang.Exception
-keep class io.sentry.event.Event { *; }
```

Is there any other information I can give to help?

**Comment by marandaneto** [comment]
hey @thefinnomenon thanks for the message.

> @marandaneto
> 
> Yeah I double checked and have everything setup the way the guide says and you reiterated here but it is still giving me the same issue.
> 
> android/build.grade
> 
> ```
> buildscript {
>     ...
>     dependencies {
>         classpath("com.android.tools.build:gradle:3.4.2")
>         classpath("io.sentry:sentry-android-gradle-plugin:1.7.30")
>     }
> }
> ```

what's about using the latest AGP version, just for the sake of trying it? `3.6.2` I guess.

> I also tried v1.7.33.

Keep using `1.7.33`, the latest is compatible with newer AGP versions.

> android/app/build.grade
> 
> ```
> apply plugin: "com.android.application"
> apply plugin: "io.sentry.android.gradle"
> ...
> ```
> 
> android/sentry.properties
> 
> ```
> defaults.url=https://sentry.io/
> defaults.org=<ORG>
> defaults.project=<PROJECT>
> auth.token=<AUTHTOKEN>
> cli.executable=node_modules/@sentry/cli/bin/sentry-cli
> ```

why are you setting `cli.executable` and `defaults.url`? `sentry-android-gradle-plugin` has a builtin `sentry-cli` and it's not needed to do anything else other than `defaults.org`, `defaults.project` and `auth.token`

> Should I leave this line in android/app/build.grade?
> 
> ```
> apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
> ```

this should not be touched afaik, `sentry-react-native` and `sentry-wizard` as stated here https://docs.sentry.io/platforms/react-native/ do everything automatically and I don't see any instruction for the manipulation of the `build.gradle`, I'd suggest to `undo` all of your manual changes and linking it again, but following the docs, which is basically `npm install @sentry/react-native --save` and `npx sentry-wizard -i reactNative -p ios android`.

> I ran the build with logging and stacktraces enabled but it really doesn't give me any helpful information. I can see the following in app/build/intermediates/sentry/sentry.pro
> 
> ```
> -keepattributes LineNumberTable,SourceFile
> -dontwarn com.facebook.fbui.**
> -dontwarn org.slf4j.**
> -dontwarn javax.**
> -keep class * extends java.lang.Exception
> -keep class io.sentry.event.Event { *; }
> ```

yep, this is part of the merging process (proguard rules) and it should not be touched as well.

> Is there any other information I can give to help?

When you get this type of error `A problem occurred starting process 'command` is most probably related to `sentry-cli` path, and as I said, the gradle plugin has its own builtin `sentry-cli`, so I'd recommend checking this out, let me know your findings, good luck :)

**Comment by thefinnomenon** [comment]
@marandaneto 

I set sentry-android-gradle-plugin back to v.1.7.33 and removed cli.executable and defaults.url from my sentry.properties (I didn't add those manually, I think they were generated from the react-native cli wizard). I was able to successfully build with ProGuard enabled but get this result now,

```
> Task :app:persistSentryProguardUuidsForReleaseRelease
> compressing mappings
> uploading mappings
> Uploaded a total of 0 new mapping files
```

and when I check the Artifacts tab for the release I have,
![image](https://user-images.githubusercontent.com/3837369/78740923-05b9c400-7926-11ea-80bd-52b915274016.png)

It should be uploading the new map for the ProGuard release right?

**Comment by marandaneto** [comment]
@thefinnomenon I'll check the `cli.executable` thingy.

this could happen if you have previously uploaded your mappings file (which came from the exact same source code).
could you try to change a little bit of your source code and execute the `build` again?
pay attention that this message can appear multiple times in the logs if you execute a build for more than one `buildType/variant`, so it probably only shows `Uploaded a total of 1 new mapping files` for one of them.

**Comment by marandaneto** [comment]
there's a fix on the way for `sentry-wizard`
https://github.com/getsentry/sentry-wizard/pull/61

**Comment by marandaneto** [comment]
so https://github.com/getsentry/sentry-react-native/releases/tag/1.3.7 has been released which bundles https://github.com/getsentry/sentry-wizard/releases/tag/v1.1.2

thanks for the bug report @thefinnomenon 
let us know if you have any other issues.
