### ISSUE TITLE
v1.7.31 not on Maven?

### ISSUE THREAD

**Issue by clembou** [getsentry/sentry-android-gradle-plugin#13]
Hi,

Looking at the changelog, Android Gradle Plugin v3.6 is supported as of v1.7.31, released on Feb 17th: https://github.com/getsentry/sentry-java/releases/tag/v1.7.31_gradle_plugin

I can't find this on Maven though: https://search.maven.org/artifact/io.sentry/sentry-android
Was this released pulled?

Based on the last comment here: https://github.com/getsentry/sentry-java/issues/740 I was expecting this to be available on Maven.

Thanks!

**Comment by marandaneto** [comment]
hey @clembou the `sentry-java` repo has a few modules and they are published with different maven package names, but still the same `groupId`.

so, for the gradle plugin, that would https://search.maven.org/artifact/io.sentry/sentry-android-gradle-plugin.

also, the gradle plugin was moved and now it has its own repo:
https://github.com/getsentry/sentry-android-gradle-plugin

let me know if you have any problems :) thanks.
