### ISSUE TITLE
Single source of truth for upgrading Gradle version

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android-gradle-plugin#134]
Today the project has 2 gradle-wrapper.properties files and bumping the Gradle requires changing both of them.
would be possible to have a single source of truth for Gradle version?

**Comment by cortinico** [comment]
I looked into this and there is no easy/elegant solution. So far an easy approach would be to create symlinks from the included build to the outer build (or vice-versa).

This would also mean that the two builds would be as isolated as they are now.

**Comment by marandaneto** [comment]
@cortinico the symlink looks like a good idea, I'm fine with that :)
