### ISSUE TITLE
Slow uploadNativeSymbols after 2.0 upgrade

### ISSUE THREAD

**Issue by tmm1** [getsentry/sentry-android-gradle-plugin#137]
_Android Gradle Plugin:_
**4.2.0**

_Gradle:_
**6.9**

_Optimizer:_
- [ ]  ProGuard
- [x]  R8

_Have you created the sentry.properties file?_
- [x]  Yes -> ./
- [ ]  No

_SDKs:_
- [x]  sentry-android -> 5.0.0
- [ ]  sentry-react-native -> which version?

---
I have the following issue:

Slow builds since upgrading.

It seems even if I click Run in android studio two times back to back, the plugin is uploading the same data over and over.

```
> Task :app:uploadNativeSymbolsForDvrDebug
> Found 120 debug information files
> Resolved source code for 47 debug information files
> Prepared debug information files for upload
> Uploaded 47 missing debug information files
> File upload complete:

  PENDING def6f1cf-e574-ed68-554a-c8670bd4e67a (out/lib/x86_64/libass.so; x86_64 sources)
  PENDING a5fbd864-c238-4738-510b-ade455757583 (out/lib/armeabi-v7a/libavutil.so; arm sources)
  ...
```

<img width="1480" alt="Screen Shot 2021-06-08 at 10 58 00 AM" src="https://user-images.githubusercontent.com/2567/121234290-6903f680-c848-11eb-95f1-3b49615642c1.png">

**Comment by marandaneto** [comment]
hey @tmm1 thanks for reporting.

do you need `uploadNativeSymbols` enabled? https://docs.sentry.io/platforms/android/proguard/
an option is to enable it only for release mode, you need to do this manually though, it'll be improved by #18

every time you hit build, it may generate new debug symbols, and right now there's no way to know if there are new symbols or they are the same afaik, hence we execute every time, unfortunately, sentry-cli though hash the files and don't upload them again, which makes a little bit easier.

@cortinico ideas?

**Comment by marandaneto** [comment]
@tmm1 just wondering, how was the behavior with the previous plugin (1.x)? faster or what? because this has not changed at all, mind elaborating? thanks

**Comment by tmm1** [comment]
It seems with the old plugin the symbols were not uploaded for debug builds, so I never noticed the slowness. I see you opened #138 to restore this behavior.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/2.0.1
