### ISSUE TITLE
Unneeded warning logged for non minified variant

### ISSUE THREAD

**Issue by ninniuz** [getsentry/sentry-android-gradle-plugin#16]
_Android Gradle Plugin:_
**3.6.2**

_Gradle:_
**5.6.4**

_Optimizer:_
- [ ]  ProGuard
- [x]  R8

_Have you created the sentry.properties file?_
- [ ]  Yes -> where?
- [ ]  No

_SDKs:_
- [x]  sentry-android -> which version?
- [ ]  sentry-react-native -> which version?

---
I have the following issue:

Everytime the SGP (v1.7.34) is applied to my project I get warnings saying `mappingFileProvider.files is empty`.

This is also for non-minified variants, which have no mapping files by definition.

**Comment by marandaneto** [comment]
hey @ninniuz thanks for raising this.

you only see this if you have `logging` enabled for Gradle, right?

The plugin runs over all the App. variants and if some conditions are not met (eg no `mappingFile`), it just exit and goes to the next one.

This `log` should not be `warn` level though, but `debug`, I'll fix that, thanks.

**Comment by ninniuz** [comment]
👍 you could also skip the logging if the variant is not minified.
Moreover, I would suggest to add the variant name into the log line to give developers some more insights on a failure condition (helpful if you have a bunch of variants with different configs). WDYT?

**Comment by marandaneto** [comment]
yep, it sounds good, it might be possible to even check on runtime if `minify` is enabled or not.
ideally, this plugin should be rewritten and we intend to do so, but it's not the highest priority right now as it seems to be working just fine, thanks for the suggestion.

**Comment by marandaneto** [comment]
I'll keep it open till it gets deployed, fixed by #17

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/1.7.35
