### ISSUE TITLE
Add e2e test for published version

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android-gradle-plugin#163]
Not sure if it's possible since maven central has some sort of delay after publishing a version.
the idea is that we e2e test a published version and detect issues in advance.

https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/2.1.1 didn't embed sentry-cli due to https://github.com/getsentry/sentry-android-gradle-plugin/pull/162 but we needed to be notified about the bug instead of identifying it thru automatized tests.

if not possible to do an e2e test, we can just add a new unit test that verifies that sentry-cli is embedded within the compiled jar

**Comment by bruno-garcia** [comment]
I see. Relying on central is indeed suboptiomal.
Could we download the artifact the release builds produces and:

1. Install it on a fake 'empty app'
2. Run some commands such as release creation?

**Comment by cortinico** [comment]
My 2 cents here: e2e testing a published version has little value as you already released something that could be broken. Imho we could instead setup a workflow that tried to publish a version on MavenLocal and tries to run the Sentry tasks. IMHO this can even be an overkill.

> 2.1.1 (release) didn't embed sentry-cli due to #162 but we needed to be notified about the bug instead of identifying it thru automatized tests.

I believe we could come up with a better solution, that is having the `distZip` task (or whatever distribution task is invoked) relying on an extra task that verifies/download the cli.

Potentially the download task can even be moved from the `buildSrc` project to the `plugin-build` project and have a better API around it (like to query if the CLI is available or not) as now is simple.

**Comment by marandaneto** [comment]
@cortinico 

> I believe we could come up with a better solution, that is having the distZip task (or whatever distribution task is invoked) relying on an extra task that verifies/download the cli.

that is indeed the way of fixing it, for now I just ran `./gradlew tasks` in order to fix the issue and publish a new version, but we obviously can do that better.

I believe your solution does work well, but this issue #163 is more about verifying it independently on how we fix it, guaranteeing that it works either before or after publishing.

if the goal of the test is just to guarantee that sentry-cli is imbedded within the jar, we could simply add a `CI step` that extracts the jar and check the resources folder, or, as suggested, published the version to `mavenLocal` and run it locally.
