### ISSUE TITLE
test-publish.yaml is always being skipped

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android-gradle-plugin#169]
release: https://github.com/getsentry/sentry-android-gradle-plugin/runs/3440741944?check_suite_focus=true
pr: https://github.com/getsentry/sentry-android-gradle-plugin/runs/3440735398?check_suite_focus=true

could it be because of the check `github.event.pull_request.head.repo.full_name == github.repository`?

**Comment by marandaneto** [comment]
iirc the PR I linked to was from a local branch of the repo, wondering if it makes sense to skip this test or not since its a useful test across PRs and releases, do you remember why we've added it? would it be fine to remove this check at all?

**Comment by cortinico** [comment]
> do you remember why we've added it? would it be fine to remove this check at all?

This is the only CI check that is effectively invoking the CLI without a dry-run.

The reason why is not running to all the PRs is that PRs running from external forks don't have access to secrets and can't invoke the CLI correctly without them.

**Comment by marandaneto** [comment]
oh yeah indeed, now I remember, makes sense, thanks.

> I believe we can extend it to run also for merges on local branches (i.e. after a PR has been merged either from a fork or from a local branch).

agreed
