### ISSUE TITLE
Build variants support

### ISSUE THREAD

**Issue by nyarian** [getsentry/sentry-android-gradle-plugin#18]
_SDKs:_
- sentry-android -> 1.7.34

---
Hi.
Is there an option to enable and configure Sentry via Gradle plugin only for certain build variants (e.g. release + certain flavor)? If yes, then how? If no, then will it be supported?

**Comment by marandaneto** [comment]
hey, it's not supported, although its a nice feature request.
no plans for this so far, but we accept PRs :)
We intend to rewrite this plugin, but not in the next few weeks.

**Comment by SaezChristopher** [comment]
Fully interrested in.

**Comment by marandaneto** [comment]
just a small update, you could do this yourself by finding the Gradle task and disabling it on the build script, I did a test and it worked out (if you need this for now).
We also accept PRs :) thanks.

**Comment by SaezChristopher** [comment]
Can you post a sample of the simple plz :)
Thx

**Comment by nEdAy** [comment]
I'm very interested in this feature

**Comment by marandaneto** [comment]
an idea is that we support config for build types and & or flavors, eg:

```
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.debug // to be able to run release mode

            sentry {
                // change configs from release build type
            }
        }
        debug {
            sentry {
                // change configs from debug build type
            }
        }
```

and/or

```
// Specifies one flavor dimension.
    flavorDimensions "version"
    productFlavors {
        demo {
            // Assigns this product flavor to the "version" flavor dimension.
            // If you are using only one dimension, this property is optional,
            // and the plugin automatically assigns all the module's flavors to
            // that dimension.
            dimension "version"
            applicationIdSuffix ".demo"
            versionNameSuffix "-demo"

            sentry {
                // change configs from flavor demo
            }
        }
        full {
            dimension "version"
            applicationIdSuffix ".full"
            versionNameSuffix "-full"

            sentry {
                // change configs from flavor full
            }
        }
    }
```

**Comment by cortinico** [comment]
How do we feel about having instead:

```
sentry {
    // Don't create tasks for the specified build types (e.g. "release")
    ignoredBuildTypes = ["release"]    
    // Don't create tasks for the specified build flavor (e.g. "production")
    ignoredFlavors = ["production"]
    // Don't create tasks for the specified build variants (e.g. "productionRelease")
    ignoredVariants = ["productionRelease"]
}
```

That's the approach that Detekt Gradle plugin is following and it works fine so far. The approach you mentioned @marandaneto it's a bit more elegant but requires to define extensions on AGP types and it couples the plugin even more the the AGP version.

**Comment by marandaneto** [comment]
@cortinico makes sense, I've not thought about the coupling problem, so I'd be fine going this way, we'll lose type check but that's the price you pain since Gradle and AGP APIs change quite often, doing this help us not relying on AGP extensions and breaking when they change it, good idea, thanks!
