### ISSUE TITLE
After SAGP upgrade 1.7 -> 2.1 gradle sync fails to accept 'sentry' config section

### ISSUE THREAD

**Issue by mkilmanas** [getsentry/sentry-android-gradle-plugin#186]
_Android Gradle Plugin:_
**7.0.2**

_Gradle:_
**7.0.2**

_Optimizer:_
- [ ]  ProGuard
- [X]  R8

_Have you created the sentry.properties file?_
- [X]  Yes -> project root
- [ ]  No

_SDKs:_
- [X]  sentry-android -> 5.1.2
- [ ]  sentry-react-native -> which version?

---
I have the following issue:

After upgrading sentry-android-gradle-plugin from 1.7.36 to 2.1.4 (also tried with 2.0.1 - same result) gradle sync in Android studio fails (same way as running `./gradlew`).
Failure points to `app/build.gradle:106` which is the line containing `sentry {` block's start.
When the `sentry { ... }` block is commented out, then gradle sync works.

I have followed both the [migration instructions](https://docs.sentry.io/platforms/android/migration/#migrating-from-iosentrysentry-android-gradle-plugin-1x-to-iosentrysentry-android-gradle-plugin-200) as well as [latest documentation](https://docs.sentry.io/platforms/android/proguard/#gradle-configuration).

I have also tried to remove build dirs as suggested in https://github.com/getsentry/sentry-android-gradle-plugin/issues/113#issuecomment-916317787 but nothing helped

My sentry config section is just
```groovy
sentry {
//    autoProguardConfig true <-- commented out as part of migration to 2.x
    autoUpload file("${project.rootDir.toPath()}/sentry.properties").exists()
}
```

**Steps to reproduce:**
- Upgrade `classpath 'io.sentry:sentry-android-gradle-plugin:1.7.36'` ->  `plugins { id 'io.sentry.android.gradle' version '2.1.4' }`
- Run gradle sync from Android studio or `./gradlew` from CLI (MacOS Big Sur zsh) 

**Actual result:**
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/marijus/Projects/{projectID}/app/build.gradle' line: 106

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_5k69o531q003o3za7vyny51vi.sentry() is applicable for argument types: (build_5k69o531q003o3za7vyny51vi$_run_closure3) values: [build_5k69o531q003o3za7vyny51vi$_run_closure3@f93f3ed]
  Possible solutions: every(), every(groovy.lang.Closure), any(), sync(org.gradle.api.Action), identity(groovy.lang.Closure), getAt(java.lang.String)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Expected result:**
Successful gradle sync

**Comment by marandaneto** [comment]
@mkilmanas check the https://docs.sentry.io/platforms/android/proguard/#gradle-configuration
if its groovy, you are missing the `=`, like: `autoUpload = ...`, if Kotlin, `autoUpload.set(...)`

**Comment by mkilmanas** [comment]
Thanks! That was so simple, yet so not obvious..
Maybe it's worth adding a note in the migration guide to take note of this syntax change?

**Comment by mkilmanas** [comment]
I totally agree that the docs are correct - but on the human perception side, I think it can be still a little bit better, if there was a "Note the slightly different syntax and removed autoProguardConfig option". 
At least that's what tripped me - I got focused on the removed option and missed the changed syntax (the fact that the equality/assignment character which has changed is dark in this theme did not help the case)

**Comment by marandaneto** [comment]
makes sense, will think about something, thanks for the feedback.
worth noting that our docs are also open-source, you can always navigate and click on `Suggest an edit to this page` and suggest improvements.
