### ISSUE TITLE
Split abis in Android Studio 4.0

### ISSUE THREAD

**Issue by headsvk** [getsentry/sentry-android-gradle-plugin#19]
_Android Gradle Plugin:_
**4.0.0**

_Gradle:_
**6.4.1**

_Optimizer:_
- [ ]  ProGuard
- [X]  R8

_Have you created the sentry.properties file?_
- [X]  Yes -> project root
- [ ]  No

_SDKs:_
- [X]  sentry-android -> 2.1.4

---
I have the following issue:

Seems like Android Studio optimizes build times and only creates the apk I need to run on attached device. This results in Sentry throwing errors when trying to upload mappings for the missing apks.
The error is not thrown if I run the release task manually because it creates all apks at once.

**Steps to reproduce:**
Run a release build of an app on a device/emulator. App needs splits configured per abi:
```
    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
            universalApk false
        }
    }
```

**Actual result:**
Build fails with the following error:
```
> Task :app:persistSentryProguardUuidsForAppRelease-x86_64-release FAILED
error: The system cannot find the path specified. (os error 3)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

> Task :app:persistSentryProguardUuidsForAppRelease-x86-release FAILED
error: The system cannot find the path specified. (os error 3)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

> Task :app:persistSentryProguardUuidsForAppRelease-armeabi-v7a-release FAILED
error: The system cannot find the path specified. (os error 3)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

> Task :app:persistSentryProguardUuidsForAppRelease-arm64-v8a-release
> compressing mappings
> uploading mappings
> Uploaded a total of 0 new mapping files
```

I would add the full debug log but I'm not able to make Android Studio on Windows pick up SENTRY_LOG_LEVEL system variable that I set in Windows settings. Any ideas how to add sentry logging to the Android app task?

**Expected result:**
Uploading mappings for missing apks is skipped and doesn't produce errors.

**Comment by marandaneto** [comment]
hey @headsvk thanks for raising this.

can you add `log.level=info` in the `sentry.properties` file?
are you running on `release` mode?

**Comment by marandaneto** [comment]
I can confirm that `{cpuArch}/AndroidManifest.xml` won't exist, AS will generate only the necessary files when running thru AS, good catch.

**Comment by headsvk** [comment]
@marandaneto great! I'll test it as soon as there's a new release :)

**Comment by marandaneto** [comment]
> @marandaneto great! I'll test it as soon as there's a new release :)

:) I'll do a release next Monday.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/1.7.35

**Comment by headsvk** [comment]
@marandaneto works, thanks!
