### ISSUE TITLE
Gradle Plugin - could not parse JSON response 

### ISSUE THREAD

**Issue by TobiasReich** [getsentry/sentry-android-gradle-plugin#21]
_Android Gradle Plugin:_
3.6.3

_Gradle:_
5.6.4

_Optimizer:_
- [ ]  ProGuard
- [X]  R8

_Have you created the sentry.properties file?_
- [X]  Yes -> project root folder (tried in /res too)
- [ ]  No

_SDKs:_
- [X]  sentry-android -> 2.1.6
- [X]  sentry-react-native -> which version?

---
I have the following issue:

So without applying the gradle plugin

`apply plugin: 'io.sentry.android.gradle'`

everything seems to work fine - but the deobfuscation doesnt work. 
Enabling this plugin again I get an error in the build process:

```
could not parse JSON response
caused by: invalid type: map, expected a sequence at line 1 column 1
```

It might be related to the new Rust Proguard release which fixed the R8 de-obfuscating. I remember it worked fine before.

**Comment by marandaneto** [comment]
hey @TobiasReich thanks for raising this, I'll check this out.

**Comment by marandaneto** [comment]
@TobiasReich can you add `log.level=info` in the `sentry.properties` file and copy-paste the logs, please? I just tested it and it worked (latest version, 1.7.35).

Also, which version of the plugin are you working with?

**Comment by marandaneto** [comment]
1.7.34 also just worked fine

**Comment by TobiasReich** [comment]
Hmm, I see, I hope I didnt misconfigure something here.
So this is the debug log. I see, there is a 302 error so I gonna have a look at our configuration, maybe we messed something up. Thanks for the help.


> uploading mappings
  INFO    2020-06-18 11:40:16.517707 +02:00 Issuing a command for Organization: newsenselab Project: android
  DEBUG   2020-06-18 11:40:16.517754 +02:00 request POST https://[...]/android/files/dsyms/
  DEBUG   2020-06-18 11:40:16.517771 +02:00 using token authentication
  DEBUG   2020-06-18 11:40:16.517779 +02:00 sending form data
  DEBUG   2020-06-18 11:40:16.517790 +02:00 retry number 0, max retries: 0
  DEBUG   2020-06-18 11:40:16.681602 +02:00 > POST /api/[...]/android/files/dsyms/ HTTP/1.1
  DEBUG   2020-06-18 11:40:16.681633 +02:00 > Host: [...]
  DEBUG   2020-06-18 11:40:16.681640 +02:00 > Accept: */*
  DEBUG   2020-06-18 11:40:16.681646 +02:00 > Connection: TE
  DEBUG   2020-06-18 11:40:16.681651 +02:00 > TE: gzip
  DEBUG   2020-06-18 11:40:16.681655 +02:00 > User-Agent: sentry-cli/1.54.0
  DEBUG   2020-06-18 11:40:16.682065 +02:00 > Authorization: Bearer 54af4b78***
  DEBUG   2020-06-18 11:40:16.682075 +02:00 > Content-Length: 2814719
  DEBUG   2020-06-18 11:40:16.682081 +02:00 > Content-Type: multipart/form-data; boundary=------------------------94a69854d4037590
  DEBUG   2020-06-18 11:40:18.075186 +02:00 < HTTP/1.1 302 Found
  DEBUG   2020-06-18 11:40:18.075208 +02:00 < Date: Thu, 18 Jun 2020 09:40:18 GMT
  DEBUG   2020-06-18 11:40:18.075217 +02:00 < Content-Type: application/json
  DEBUG   2020-06-18 11:40:18.075235 +02:00 < Content-Length: 218
  DEBUG   2020-06-18 11:40:18.075242 +02:00 < Connection: keep-alive
  DEBUG   2020-06-18 11:40:18.075255 +02:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2020-06-18 11:40:18.075261 +02:00 < X-Content-Type-Options: nosniff
  DEBUG   2020-06-18 11:40:18.075268 +02:00 < Content-Language: en
  DEBUG   2020-06-18 11:40:18.075273 +02:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2020-06-18 11:40:18.075280 +02:00 < Vary: Accept-Language, Cookie
  DEBUG   2020-06-18 11:40:18.075285 +02:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2020-06-18 11:40:18.075291 +02:00 < Location: /api/[...]/files/dsyms/
  DEBUG   2020-06-18 11:40:18.075297 +02:00 < Allow: GET, POST, DELETE, HEAD, OPTIONS
  DEBUG   2020-06-18 11:40:18.075302 +02:00 < Access-Control-Allow-Origin: *
  DEBUG   2020-06-18 11:40:18.075308 +02:00 < Access-Control-Allow-Methods: GET, POST, DELETE, HEAD, OPTIONS
  DEBUG   2020-06-18 11:40:18.075314 +02:00 < X-Frame-Options: deny
  DEBUG   2020-06-18 11:40:18.075361 +02:00 response status: 302
  DEBUG   2020-06-18 11:40:18.075371 +02:00 body: {"slug":"app-android","detail":{
      "message":"Resource has been moved","code":"resource-moved",
      "extra":{"url":"/api/0/[...]/files/dsyms/","slug":"m-sense-legacy-android"}
  }}
  DEBUG   2020-06-18 11:40:18.075964 +02:00 error: running update nagger
  DEBUG   2020-06-18 11:40:18.075985 +02:00 skipping update nagger because session is not attended
error: could not parse JSON response
  caused by: invalid type: map, expected a sequence at line 1 column 1
  DEBUG   2020-06-18 11:40:18.076406 +02:00 client close; no transport to shut down  (from sentry)

**Comment by marandaneto** [comment]
hey @TobiasReich thanks for the log.

please double-check your `sentry.properties` conf.

mainly about `org` and `project`, let me know :)

**Comment by TobiasReich** [comment]
Yea, you are right. I discovered it wasnt configured correctly.
I guess I got confused about the different configuration options of Manifest, config file and in code stuff.
Thanks, problem is solved!
