### ISSUE TITLE
Android Studio 注释快捷点不起效

### ISSUE THREAD

**Issue by githubliuqi** [getsentry/sentry-android-gradle-plugin#22]
Android Studio:
4.0

Android Gradle Plugin:
4.0.0

Gradle:
6.5

Android Studio 注释快捷点不起效。enter不能换行，必须是shift+enter才能换行。java和C++代码没有智能提示和函数跳转，gradle脚本有时候也没有提示。

**Comment by marandaneto** [comment]
@githubliuqi sorry we only speak English here.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
