### ISSUE TITLE
Automatically attach SentryInterceptor for OkHttp and Apollo

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-android-gradle-plugin#222]
Since we have some basis for bytecode manipulation now, we can utilise that knowledge and attach SentryInterceptor for okhttp and apollo clients automatically to avoid any manual work from the user's site

**Comment by philipphofmann** [comment]
Things to consider:
- Make this feature opt-in, because we want feedback first. In the next major, we enable this per default.
- Point this out in the docs.
- More than one endpoint, maybe want to track one and not the other.
- Multiple Gradle plugins instrumenting OkHttp or Apollo
