### ISSUE TITLE
Upload isn't working

### ISSUE THREAD

**Issue by blinkev** [getsentry/sentry-android-gradle-plugin#23]
Hi! I added a gradle plugin and all other things from the doc https://docs.sentry.io/platforms/android/#proguard
But the plugin doesn't upload my mappings when I run presentation:installMyAppProductionRelease
I added env variable SENTRY_LOG_LEVEL=debug and logs are:

> Task :presentation:persistSentryProguardUuidsForMyAppProductionReleaseMyApp-production-universal-release
  INFO    2020-07-02 12:10:31.197359 +03:00 Loaded config from /Users/blinkev/.sentryclirc
  DEBUG   2020-07-02 12:10:31.197948 +03:00 sentry-cli version: 1.47.1, platform: "darwin", architecture: "x86_64"
  INFO    2020-07-02 12:10:31.197967 +03:00 sentry-cli was invoked with the following command line: "/var/folders/hh/hwlv3qqx62jb8bggw7v7fcq00000gn/T/.sentry-cli7303535485387916602.exe" "upload-proguard" "--android-manifest" "/Users/blinkev/StudioProjects/MyApp_v4/presentation/build/intermediates/merged_manifests/myAppProductionRelease/universal/AndroidManifest.xml" "--write-properties" "/Users/blinkev/StudioProjects/MyApp_v4/presentation/build/intermediates/merged_assets/myAppProductionRelease/out/sentry-debug-meta.properties" "/Users/blinkev/StudioProjects/MyApp_v4/presentation/build/outputs/mapping/myAppProduction/release/mapping.txt" "--no-upload"
  DEBUG   2020-07-02 12:10:31.464134 +03:00 SHA1 for mapping file '/Users/blinkev/StudioProjects/MyApp_v4/presentation/build/outputs/mapping/myAppProduction/release/mapping.txt': 'ea7395f5d4bd0c5997f3a72e6441e6aa7d755a0f'
> compressing mappings
> skipping upload.
BUILD SUCCESSFUL in 1m 17s

As you can see it generates UUID for mappings but doesn't upload them o_O
In my project I also have crashlytics and I see a gradle task uploadCrashlyticsMappingFileMyAppProductionRelease running in the end but I don't see the same task for sentry.

**Comment by marandaneto** [comment]
@blinkev hey, please update this issue with the bug report template, so I know which version you are working with and also other things.

**Comment by marandaneto** [comment]
@blinkev are you for some reason overwriting the plugin's default values?
https://docs.sentry.io/platforms/android/#gradle-configuration

it looks like you've set `autoUpload` to false, default is true, that's why you've got `skipping upload`.

if it's the case, please close the issue and if not, as stated before, more context would be very helpful, see `bug report template`.

**Comment by blinkev** [comment]
@marandaneto Hi! Ok, here you are:

_Android Gradle Plugin:_
**3.5.1**

_Gradle:_
**5.4.1**

_Optimizer:_
- [x]  ProGuard
- [ ]  R8

_Have you created the sentry.properties file?_
- [ ]  Yes -> where?
- [x]  No

_SDKs:_
- [x]  sentry-android -> 1.7.27
- [ ]  sentry-react-native -> which version?

---
I have the following issue:

The description is above. I can add that I didn't export SENTRY_ORG variable (is it necessary?). By the way, if it is, what should I use as my org, I didn't find that setting in my sentry project settings page, is it "Subject Prefix" param?

**Steps to reproduce:**
I added sentry to my project, it sends reports but doesn't upload proguard files

**Actual result:**
Upload proguard files

**Expected result:**
Doesn't upload proguard files

**Comment by marandaneto** [comment]
@blinkev thanks.

https://docs.sentry.io/clients/java/integrations/#proguard

there are all the steps, either you export the envs or you create the sentry.properties file in the root folder.

for org, go to menu, organization settings and in the general section, you will have the org name under `Name`.

let me know if you managed to make it work, thanks.

**Comment by blinkev** [comment]
@marandaneto Adding SENTRY_ORG didn't help, continue to print "skipping upload". Maybe there is some log file where I can see why it is skipping?

**Comment by marandaneto** [comment]
create the file `sentry.properties` as suggested here https://docs.sentry.io/clients/java/integrations/#gradle-integration and be sure that the plugin conf. is enabled https://docs.sentry.io/clients/java/integrations/#gradle-configuration

**Comment by CarsonRedeye** [comment]
My auth token for upload recently got delete from sentry.io. Maybe this is a related issue?

**Comment by marandaneto** [comment]
> My auth token for upload recently got delete from sentry.io. Maybe this is a related issue?

I don't think so, their case is different, there's no exported envs nor sentry.properties, basically plugin is not configured at all if I got this right.
An invalid token will be probably non authorized, denied, etc...

**Comment by marandaneto** [comment]
I'll close this as invalid, please reopen this issue if you have the system envs or the file configured and still running the same problem, thanks.
