### ISSUE TITLE
Add `includeProguardMapping` property to completely enable or disable the feature

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android-gradle-plugin#238]
Today we only have `autoUpload` which means sentry-cli is run in dry-mode, so the file isn't uploaded, but the `SentryGenerateProguardUuidTask` task is still executed and the file `sentry-debug-meta.properties` is still generated.

The idea is that this feature works in conjunction with `autoUpload`, which means:

if `includeProguardMapping` is disabled, the task `SentryGenerateProguardUuidTask` bails out since the user does not want to do anything with proguard mapping file, same for SentryUploadProguardMappingsTask.

if the `includeProguardMapping` is enabled, but `autoUpload` disabled, it works as it is today, it generates the `sentry-debug-meta.properties` with the generated id, and the user can later upload manually via sentry-cli

the name can be different, but I guess `includeProguardMapping` makes more sense since the plugin does some other stuff too.
we could technically deprecate `autoUpload` and rename it to `autoUploadProguardMapping`, but fallback to `autoUpload` because of compatibility.

**Comment by cortinico** [comment]
> if the `includeProguardMapping` is enabled, but `autoUpload` disabled, it works as it is today

So I suppose we have `includeProguardMapping` as default to true right?

**Comment by marandaneto** [comment]
> > if the `includeProguardMapping` is enabled, but `autoUpload` disabled, it works as it is today
> 
> So I suppose we have `includeProguardMapping` as default to true right?

yes
