### ISSUE TITLE
Publish to jcenter

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-android-gradle-plugin#25]
Latest version is 1.7.35 but jcenter has it up to 1.7.30:

https://bintray.com/beta/#/getsentry/sentry-java/io.sentry:sentry-android-gradle-plugin?tab=overview

Is it possible to publish to jcenter too?

**Comment by marandaneto** [comment]
it's available on jcenter due to the synchronization with bintray when we've started using it.

we'd need to apply a new Gradle plugin in order to do it, I'd prefer to do it when we come to rewrite this plugin altogether.

**Comment by marandaneto** [comment]
for now, I've updated the release drafter to link the maven central link on the GH release eg https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/1.7.35

**Comment by marandaneto** [comment]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
