### ISSUE TITLE
Sentry plugin prints out warnings/errors when using latest AGP 4.1.0-rc03

### ISSUE THREAD

**Issue by patrickusiewicz** [getsentry/sentry-android-gradle-plugin#27]
_Android Gradle Plugin:_
**4.1.0-rc03**

_Gradle:_
**6.6.1**

_Optimizer:_
- [ ]  ProGuard
- [ ]  R8

_Have you created the sentry.properties file?_
- [X]  Yes ->  Project root folder
- [ ]  No

_SDKs:_
- [X]  sentry-android -> 2.3.0
- [ ]  sentry-react-native -> which version?

---
I have the following issue:
When building my Android project using the AGP 4.1.0-rc03 together with newest Sentry Gradle plugin
I observed the following warnings/errors in the terminal: 
```
findAndroidManifestFileDir 1: Could not get unknown property 'manifestOutputDirectory' for task ':app:processDebugManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.
findAndroidManifestFileDir 2: Could not get unknown property 'manifestOutputDirectory' for task ':app:processDebugManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.
findAndroidManifestFileDir 3: Could not get unknown property 'manifestOutputFile' for task ':app:processDebugManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.
Cannot query the value of this property because it has no value available.
findAndroidManifestFileDir 1: Could not get unknown property 'manifestOutputDirectory' for task ':app:processReleaseManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.
findAndroidManifestFileDir 2: Could not get unknown property 'manifestOutputDirectory' for task ':app:processReleaseManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.
findAndroidManifestFileDir 3: Could not get unknown property 'manifestOutputFile' for task ':app:processReleaseManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.
```
After reading [link](https://medium.com/androiddevelopers/new-apis-in-the-android-gradle-plugin-f5325742e614) from android developers medium I can see that AGP 4.1 introduced new variant apis. Maybe the changes should be introduced into Sentry Gradle plugin?
I also found that the Bugsnag Gradle plugin also had the same [issue](https://github.com/bugsnag/bugsnag-android-gradle-plugin/issues/194) with changes introduced in the AGP 4.1. 

Besides the warnings observed in the terminal I didn't find any issues with Sentry. Forced app exceptions were catched by the Sentry library and uploaded to sentry.io.

**Comment by marandaneto** [comment]
hey @patrickusiewicz thanks for that, we'll investigate it and come back to you asap.

**Comment by pvtai** [comment]
> hey @patrickusiewicz thanks for that, we'll investigate it and come back to you asap.

@marandaneto Could you please tell me, is this error coming from android studio or is it from the gradle plugin?
Thank you

**Comment by lukas1** [comment]
@pvtai yes, it's error that comes up from the gradle plugin and has nothing to do with Android studio. You'll get this error even by building project from command line, using simple `./gradlew build`

It's obviously an issue in this gradle plugin, based on the report on Bugsnag Gradle plugin the issue seems to be, that this plugin uses private API, which was removed in AGP 4.1.

**Comment by marandaneto** [comment]
yep, we'll need to fix this, now it's GA and not RC anymore.
https://developer.android.com/studio/releases/gradle-plugin#4-1-0

**Comment by afj88** [comment]
It't because of this issue that after updating to AS 4.1 and using gradle-6.5 with com.android.tools.build:gradle:4.1.0 i'm getting this error?

`Execution failed for task ':app:processDevBaseDebugManifest'.
> Could not find method getBundleManifestOutputDirectory() for arguments [] on task ':app:processDevBaseDebugManifest' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.`

The code generatin this error is the same that worked until yesterday (gradle-6.1.1 and com.android.tools.build:gradle:4.0.1)

`android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def processorTask = output.processManifestProvider.getOrNull()
            processorTask.doLast { task ->
                def directory = task.getBundleManifestOutputDirectory().asFile.get()
                def srcManifestFile = "$directory/AndroidManifest.xml"
                def manifestContent = new File(srcManifestFile).getText()
                def xml = new XmlParser(false, false).parseText(manifestContent)
                def app = xml.application[0]
                app.activity.eachWithIndex { activity, idx ->
                   ....
                }

                def serializeContent = XmlUtil.serialize(xml)
                new File("${project.buildDir}/intermediates/merged_manifests/${variant.name}/AndroidManifest.xml").write(serializeContent)
            }
        }
    }`

**Comment by pvtai** [comment]
Currently, I temporarily downgrade the gradle version to 6.1.1 and the gradle plugin to 4.0.1 to run the project.

**Comment by marandaneto** [comment]
looking into it now.

**Comment by marandaneto** [comment]
@afj88 this looks like something else and not related to the Sentry Plugin unless you have more logs.

**Comment by lukas1** [comment]
not the OP, but applying sentry plugin I get this message. NOT applying the sentry plugin, I do not get that error.

**Comment by marandaneto** [comment]
> not the OP, but applying sentry plugin I get this message. NOT applying the sentry plugin, I do not get that error.

my comment was specifically about https://github.com/getsentry/sentry-android-gradle-plugin/issues/27#issuecomment-708233465

**Comment by marandaneto** [comment]
#28 should fix it, need to do a few more tests.

**Comment by marandaneto** [comment]
I will publish a new version tomorrow morning :)

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/1.7.36

**Comment by patrickusiewicz** [comment]
@marandaneto thank you for the update!
