### ISSUE TITLE
Sentry shows "A proguard mapping file does not contain line info" even though the mapping file does contain it

### ISSUE THREAD

**Issue by mpetrychko** [getsentry/sentry-android-gradle-plugin#275]
_Sentry Gradle Plugin:_
**2.1.5**

_Android Gradle Plugin:_
**7.0.4**

_Gradle:_
**7.2**

_Optimizer:_
- [ ]  R8

_Have you created the sentry.properties file?_
- [ ]  Yes -> in the root directory of the project

_SDKs:_
- [ ]  sentry-android -> 5.6.1

---
I have the following issue:

When trying to upload the mapping generated by proguard, it's uploaded successfully, I can see it in the project settings on sentry, but my crash reports are not deobfuscated showing an error:
![Screenshot 2022-02-04 at 16 52 42](https://user-images.githubusercontent.com/99031661/152549919-1cbbfbc4-0bf5-4626-ace4-e3d4b421bff7.png)
The proguard-rules.pro file contains the rule to keep the line numbers **-keepattributes SourceFile,LineNumberTable;-keepattributes *Annotation***, and I can see the line numbers in the generated mapping file.

Here is my sentry gradle configuration:
`sentry {

    includeProguardMapping = true
    autoUploadProguardMapping = true
    tracingInstrumentation {
        enabled = false
    }
}`

**Actual result:**
- the mapping file is not recognized

**Expected result:**
- the mapping file is recognized

**Comment by romtsn** [comment]
hm, are you sure you're using version `2.1.5`? the gradle config you posted wouldn't compile, because these options are only available starting from `3.0.0-beta` actually

**Comment by mpetrychko** [comment]
yeah, you are right, sorry, I was just trying **3.0.0-beta** to see if it would make any difference, and copied the configuration for it, but anyway it didn't work.

**Comment by romtsn** [comment]
hm, could you share you `proguard-rules.pro` file? Also, make sure that it's actually in the right location and is picked up by gradle

**Comment by mpetrychko** [comment]
yes, sure. here are the rules:
<pre>
# Uncomment this to preserve the line number information for
# debugging stack traces.
-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
-renamesourcefileattribute SourceFile
</pre>

the proguard file is in the `app` directory, so it should be picked up by gradle. also the sentry sdk library has these rules defined as well, so they are merged into the configuration file by proguard. just to be sure that the mapping file does contain the line numbers, see this snippet of mapping:
<pre>
# compiler: R8
# compiler_version: 3.0.76
# min_api: 21
# pg_map_id: 55d9ad0
# common_typos_disable
android.support.customtabs.ICustomTabsCallback -> a.a:
android.support.customtabs.ICustomTabsCallback$Stub -> a.a$a:
    1:2:void <init>():44:45 -> <init>
    1:3:android.support.customtabs.ICustomTabsCallback asInterface(android.os.IBinder):56:58 -> asInterface
    4:4:android.support.customtabs.ICustomTabsCallback asInterface(android.os.IBinder):60:60 -> asInterface
    1:1:android.support.customtabs.ICustomTabsCallback getDefaultImpl():399:399 -> getDefaultImpl
    1:1:boolean onTransact(int,android.os.Parcel,android.os.Parcel,int):188:188 -> onTransact
    2:2:boolean onTransact(int,android.os.Parcel,android.os.Parcel,int):165:165 -> onTransact
</pre>

**Comment by romtsn** [comment]
@marandaneto thoughts? I could think of something wrong on the backend/symbolic site, but I guess somebody would've complained already

**Comment by marandaneto** [comment]
@mpetrychko can you link us to a Sentry's issue that shows off the problem? That would help us debug the issue and check its meta data.
@Swatinem may be able to help us too since he worked on the symbolication.

**Comment by Swatinem** [comment]
I checked the above snipped and it runs fine through `rust-proguard`. I’m not sure which version of that is being used as part of the gradle pipeline. In particular if it has this fix here: https://github.com/getsentry/rust-proguard/pull/21 but that has been part of a released version for quite some time.

The first mapping `    1:2:void ():44:45 -> ` looks a bit weird in that it does not have either an original or obfuscated name, but the parser does not seem to care either, and it parses just fine.

**Comment by mpetrychko** [comment]
> @mpetrychko can you link us to a Sentry's issue that shows off the problem? That would help us debug the issue and check its meta data. @Swatinem may be able to help us too since he worked on the symbolication.

I am not sure if its not against our security policies. can you share what information exactly do you need?

**Comment by romtsn** [comment]
@mpetrychko a link to your project+issue is enough, nobody can access it except you and sentry team it will be hidden behind the authwall

**Comment by mpetrychko** [comment]
We actually using sentry as on premises software, are you still going to be able to access it?

**Comment by mpetrychko** [comment]
that's a good point, thanks. I'll try to find out if they have an up-to-date instance and get back to you asap.

**Comment by marandaneto** [comment]
@mpetrychko any update on this? thanks.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
