### ISSUE TITLE
unable to resolve class io.sentry.android.gradle.InstrumentationFeature

### ISSUE THREAD

**Issue by huhuang03** [getsentry/sentry-android-gradle-plugin#290]
_Android Gradle Plugin:_
**7.1.1**

_Gradle:_
**7.2*

_Optimizer:_
- [N]  ProGuard
- [Y]  R8

_Have you created the sentry.properties file?_
- [Y]  Yes -> In sentry.io
- [ ]  No

_SDKs:_
- [Y]  sentry-android -> 5.6.1
- [N]  sentry-react-native 

---
I have the following issue:
`unable to resolve class io.sentry.android.gradle.InstrumentationFeature`

The description goes here ...

**Steps to reproduce:**
- Follow https://docs.sentry.io/platforms/android/gradle/ set up the build.gradle
- Run ./gradlew build
- Got the exception.

**Comment by huhuang03** [comment]
Remove `import io.sentry.android.gradle.InstrumentationFeature` will work.

But I think maybe should modify the https://docs.sentry.io/platforms/android/gradle?

**Comment by romtsn** [comment]
thank for the report. Which version of Sentry android gradle plugin are you using? 2.1.5?

**Comment by huhuang03** [comment]
Yes, it's 2.1.5.

**Comment by romtsn** [comment]
Ok, we have a note that this is only available from 3.0.0 onwards [here](https://docs.sentry.io/platforms/android/gradle/#:~:text=Default%20is%20enabled.-,//%20Only%20available%20v3.0.0%20and%20above.,-tracingInstrumentation%20%7B%0A%20%20%20%20%20%20enabled%20%3D%20true).

But it's probably worth adding it also to the import itself, I'll update the docs.
