### ISSUE TITLE
ProGuard mappings are not being uploaded anymore

### ISSUE THREAD

**Issue by code-schreiber** [getsentry/sentry-android-gradle-plugin#298]
_Sentry Android Gradle Plugin:_
I've tried with **3.0.0** and **2.1.5**

_Gradle:_
com.android.tools.build:gradle:**7.1.1**

_Optimizer:_
- [ ]  ProGuard
- [x]  R8

_Have you created the sentry.properties file?_
- [x]  Yes -> where? Yes, 2 years ago and is in the Android's project root folder
- [ ]  No

_SDKs:_
- [x]  sentry-android -> which version? **5.6.1**
- [ ]  sentry-react-native -> which version?

---
I have the following issue:

We have been using Sentry for a while now, and crash reports used to show de-obfuscated, we noticed more and more obfuscated crashes and discovered that the mapping files haven't been uploaded anymore for some months, even though production builds were created and released continuously. We now have taken a closer look at possible root causes for some days, and are sadly out of ideas. All settings, like `SENTRY_DSN` have stayed the same and no build errors have been shown.

The two concrete questions that I am looking for an answer:
1. Why are we not seeing any build errors, but https://sentry.io/settings/example-org/projects/example-android/proguard/ shows no new mappings? (See screenshot in **Actual result**)
2. Why are we seeing some obfuscated and some non-obfuscated elements in a stacktrace, where a mouse-hover tooltip hides important info? (See screenshot in **Actual result**)

**Steps to reproduce:**
1. Make sure that sentry.properties contains the correct settings (project, org and token)
2. Make sure that `autoUpload` is set to true (`includeProguardMapping` and `autoUploadProguardMapping` when using Sentry Android Gradle Plugin v3.0.0)
3. Call `./gradlew assembleExampleRelease`
4. The mapping file is created as expected and can be found at project/app/build/outputs/mapping/productionRelease/mapping.txt
5. No build error is shown, but mapping does not show up in https://sentry.io/settings/example-org/projects/example-android/proguard/

**Actual result:**
<img width="400"  src="https://user-images.githubusercontent.com/759086/159528083-a13ada66-dfdc-4171-83b3-d819db857f02.png">
  
<img width="700"  src="https://user-images.githubusercontent.com/759086/159527545-ed04d86e-5063-456a-b1b0-7fd09fa61bb4.png">

**Expected result:**
- https://sentry.io/settings/example-org/projects/example-android/proguard/ should contain mappings of each release build
- Stacktraces should show all class names with lines
- The build command `./gradlew assembleExampleRelease` should fail or at least show a warning if upload fails

**Comment by romtsn** [comment]
my first guess would be that your org/project slug changed, and you haven't updated the `sentry.properties` file (similar to #252)

If that's not the case, could you paste the gradle output here, but run the build with `--info` flag? Additionally, you could also set `export SENTRY_LOG_LEVEL=info`  env variable, to have a more verbose log of the bundled cli (the uploading of the proguard files is done using sentry-cli)

**Comment by code-schreiber** [comment]
Thanks for your suggestions!
`defaults.project` and `defaults.org` in sentry.properties look correct, those haven't seem to have changed.

I added` SENTRY_LOG_LEVEL=info` to sentry.properties and run `./gradlew assembleExampleRelease --info`, I don't see a Sentry step. Another thing that might be relevant: When I put a wrong `auth.token` or `defaults.project`, the build continues as well, shouldn't an error occur if Sentry is unable to do its magic? I would expect a sentry Gradle step to fail.

`./gradlew assembleExampleRelease --info` very long output: [gradle run.txt](https://github.com/getsentry/sentry-android-gradle-plugin/files/8331447/gradle.run.txt)

**Comment by romtsn** [comment]
hmm, from the logs it looks like the sentry tasks are not run at all. Are you sure the plugin is applied to the right project?

**Comment by marandaneto** [comment]
@code-schreiber did you check this out?

**Comment by code-schreiber** [comment]
I've been asking myself the exact question, thanks for your input, it helped me look closer in the right direction.

The codebase is a single-module Android project, it does not have any special Gradle configuration that is different than the classic new Android project. Looking deeper into it it seems this is a classic problem of basic configuration not working but also not failing.

The problem originated when migrating the Sentry Gradle plugin from v1 to v2. The documentation does not state that the configuration needs to be moved to the specific module, so it was kept in the top-level build.gradle file
https://docs.sentry.io/platforms/android/migration/#migrating-from-iosentrysentry-android-gradle-plugin-1x-to-iosentrysentry-android-gradle-plugin-200
Moving the plugins block from the top level Gradle file to the :app level Gradle file solved this issue.
```
plugins {
    id "io.sentry.android.gradle" version "3.0.0"
}
```


How can other Sentry users avoid this problem in the future? Some ideas:
- Making the migration documentation more explicit
- Making the Sentry Gradle plugin fail the build if not configured correctly, the `sentry { }` in the :app module compliled and run without problems, but the upload never happened and never failed

**Comment by romtsn** [comment]
Thanks for your feedback, that's very valuable. I think we can do both actually, update the migration doc and fail the build/give a warning if there's no `com.android.application` plugin found.

FWIW, we mention here that the plugin should be applied to the `app` module -> https://docs.sentry.io/platforms/android/gradle/#install, but I agree we can improve the experience here.

**Comment by code-schreiber** [comment]
Thanks for your help and for this very helpful product 🙇 
  
  ----
> FWIW, we mention here that the plugin should be applied to the `app` module

This is exactly the place that helped me when taking a closer look 👌
