### ISSUE TITLE
Warn users if the plugin is not applied to the Android app project

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-android-gradle-plugin#301]
We could check if the project has `com.android.application` in the plugins list, and if not, warn/fail the build. Follow-up from #298

**Comment by marandaneto** [comment]
Today we just bail if the plugin `com.android.application` isn't available, wondering how we would do that if the plugin isn't being applied in the first place.
It'd make sense for people applying the plugin in an Android library tho.
