### ISSUE TITLE
Inject enabled features into the sentry-android sdk

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-android-gradle-plugin#308]
We need to find a way to inject enabled features of the gradle plugin (auto-instrumentation, auto-installation, dexguard, etc.) into the Android SDK as part of the `integrations` list (https://github.com/getsentry/sentry-java/issues/1885).

Potential solutions:
* Inject into the AndroidManifest and read it at runtime
* Write into a file (similar to proguard-uuid) and read it at runtime
* Use bytecode manipulation to update the integrations list

**Comment by markushi** [comment]
Let's inject this information to the app `AndroidManifest.xml`, together with the proguard mapping UUID.
