### ISSUE TITLE
AbstractInstallStrategy should warn the user about a new sentry-something version installed

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-android-gradle-plugin#324]
### Description

This strategy could issue a warning if it counts more than one occurence of the sentry-android-core/sentry-android-okhttp/etc module in the dependency tree, which could happen in case if it comes as a transitive dependency AND our auto-installation kicks in.

We could warn a user that we've upgraded his sentry-android-something version to the latest and advice him to explicitly specify it via configuration `sentryVersion`. We only do this for the upgrade (so if they have a higher transitive version, that's probably what they want anyway and we don't warn)

**Comment by philipphofmann** [comment]
Shouldn't this be the build system's job that resolves the dependencies?

**Comment by romtsn** [comment]
what do you mean by "this" exactly? Warning the user? It won't do it, it will just resolve it to the latest, but we could notify the user that we auto-installed a higher version of the sdk, so they are aware of potential issues and it's not a silent update.

**Comment by romtsn** [comment]
no, we want to print a warning to inform the user that *we auto-installed* a new mismatching version of the sentry sdk, because the auto-installation feature is on by default, and they might not be aware of it.
