### ISSUE TITLE
An option to control integration of Android dependencies

### ISSUE THREAD

**Issue by beigirad** [getsentry/sentry-android-gradle-plugin#331]
### Problem Statement

I didn't understand why some Android dependencies will be install automatically. But it's not my request and I can accept the risk of incompatible versions issue or other thing that comes in #282. I always check dependency tree in each project.

So I think it's better to provide an option to control this feature/integration.

Now I can't bump to 3.1 and remained on 3.0

**Comment by romtsn** [comment]
It's already possible and is also mentioned in the [docs](https://docs.sentry.io/platforms/android/gradle/#configure):
```
sentry {
  autoInstallation.enabled = false
}
```

Is that what you are looking for? If not, please reopen the issue, thanks!
