### ISSUE TITLE
how to set LOG LEVEL using gradle plugin

### ISSUE THREAD

**Issue by arjun1194** [getsentry/sentry-android-gradle-plugin#332]
### Problem Statement

how to set LOG_LEVEL  using the gradle plugin
![image](https://user-images.githubusercontent.com/35815360/174831961-09545703-bd92-4203-ae84-8d9b6f8aaa63.png)

i am getting the above error, but dont know how to set the log level using the gradle plugin

### Solution Brainstorm

i was hoping to find something like this, but doesnt exist
```
sentry {

logLevel = info|debug

}

```

**Comment by romtsn** [comment]
Sorry, we don't currently expose a dsl option for that. Could you just `export SENTRY_LOG_LEVEL=debug`  into your env variables in terminal? Then it should give you the debug output.
