### ISSUE TITLE
Android Gradle Plugin - Configuration by build type

### ISSUE THREAD

**Issue by mduong** [getsentry/sentry-android-gradle-plugin#34]
Is there a way to set the [configuration properties](https://docs.sentry.io/platforms/android/proguard/#gradle-configuration) of the Gradle plugin on a build type by build type basis?

I was hoping something like this would work, but alas, does not:
```groovy
android {
    buildTypes {
        debug {
            sentry {
                autoUpload false
            }
        }

        staging {
            sentry {
                autoUpload false
            }
        }

        release {
            sentry {
                autoUpload true
            }
        }
    }
}
```

**Comment by marandaneto** [comment]
hey @mduong thanks for raising this, unfortunately not ootb, but you can do it manually.
dup of #18
