### ISSUE TITLE
Redirect users to the wizard after plugin installation

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-android-gradle-plugin#345]
### Description

Upon the first gradle sync/run after the plugin has been install, we can show a popup/link which would redirect users to the wizard, so we can automatically infer the org, the project and the auth token to fill in the `sentry.properties` file, therefore make the setup even more seamless.

**Comment by adinauer** [comment]
Related to https://github.com/getsentry/team-mobile/issues/26

**Comment by romtsn** [comment]
Since we put our bets on the [sentry-cli wizard](https://github.com/getsentry/sentry-wizard/issues/316), let's close this until further notice. We can revive this if we see there's still a need for this for e.g. Windows users
