### ISSUE TITLE
Android Studio build gradle cannot upgrade from 4.0.2 to 4.1.0

### ISSUE THREAD

**Issue by WenLonG12345** [getsentry/sentry-android-gradle-plugin#36]
_Android Gradle Plugin:_
**1.7.36**

_Gradle:_
**6.5**

_Have you created the sentry.properties file?_
Yes -> in Android.Manifest

_SDKs:_
sentry-android -> 3.1.0

---
I have the following issue:

Hi, I have issue regarding to upgrading Android Studio from 4.0.2 to 4.1.0.

Here is the error stack. 

A problem occurred configuring project ':app'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
  	[class java.lang.String, class java.lang.String]
  	[class java.io.File, class java.lang.String]

![Screenshot_6](https://user-images.githubusercontent.com/39330565/98316087-b00cdd80-2014-11eb-95bc-899566121ab8.png)
 
I am not sure here is the right place to ask about this but I had tried to search for the correct Sentry Android repo to ask my question but can't find any. Please give me some suggestion and this error.  Thank you very much 👍

**Comment by marandaneto** [comment]
dup #35 ?

**Comment by WenLonG12345** [comment]
Thanks so much! 
I couldn't found it in any places at first. 
solved my problem by by upgrading `io.sentry:sentry-android-gradle-plugin:1.7.23` to `io.sentry:sentry-android-gradle-plugin:1.7.36`
