### ISSUE TITLE
It is not possible to disable auto installation (sentry.autoInstallation.enabled = false, does not work)

### ISSUE THREAD

**Issue by michal-luszczuk** [getsentry/sentry-android-gradle-plugin#366]
### Gradle Version

7.5.1

### AGP Version

7.2.2

### Version

3.1.4

### Sentry SDK Version

6.0.0, 6.3.1, any...

### Steps to Reproduce

1. Install `io.sentry:sentry-android-gradle-plugin:3.1.4` to the project where timber, okhttp and fragments are used
2. In the `app/build.gradle` **try to turn off auto installation** by adding code block:
````
 autoInstallation {
        enabled = false
        sentryVersion = '6.0.0' //this line should not matter)
}
````
3. Sync the project

### Expected Result

`io.sentry:sentry-android-fragment` or `io.sentry:sentry-android-timber` or `io.sentry:sentry-android-okhttp` **should not be added to the dependencies**

### Actual Result

Dependencies for `io.sentry:sentry-android-okhttp:6.0.0`, `io.sentry:sentry-android-timber:6.0.0`, `io.sentry:sentry-android-fragment:6.0.0` are added to the dependencies

**Comment by romtsn** [comment]
Closing this with no response for over a month, please feel free to reopen with more details. Thanks!
