### ISSUE TITLE
Sentry user feedback support

### ISSUE THREAD

**Issue by theo-jedi** [getsentry/sentry-android-gradle-plugin#38]
Hello! What about user feedback feature?

_Sentry API: [https://docs.sentry.io/platforms/android/enriching-events/user-feedback/](https://docs.sentry.io/platforms/android/enriching-events/user-feedback/)_

**Comment by marandaneto** [comment]
I don't follow, what's the question? please issues related to the Android SDK should be opened here https://github.com/getsentry/sentry-java

**Comment by theo-jedi** [comment]
Sorry my mistake, I misused the libraries. Thanks for your work, incredible tool!
