### ISSUE TITLE
Broken post release script

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-android-gradle-plugin#388]
### Description

Release build failed after merging the branch back into `main` in our `post-release.sh` because it tried to switch to `main` even though it already was on the branch. See https://github.com/getsentry/craft/issues/421 for more details and links to builds and logs.

**Comment by romtsn** [comment]
on Java we actually removed it entirely, so probably should do the same here https://github.com/getsentry/sentry-java/commit/2c18613e370da8a1a18391f6d9cb6f3e5c4f1f83
