### ISSUE TITLE
Add app context to ProGuard mappings uploaded.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-android-gradle-plugin#40]
Pass additional information to sentry-cli to augment what we know about the `mappings.txt` we're uploading.
The goal is to surface more information in the `ProGuard` page in Sentry Settings.

Data to pass to sentry-cli, app's:

* name
* id
* version

See also: https://github.com/getsentry/sentry-java/issues/954

sentry-cli already accepts some extra fields:
https://github.com/getsentry/sentry-cli/blob/master/src/commands/upload_proguard.rs#L41-L72

But we might need to extend it, and add support on the server. Needs discussion.

**Comment by marandaneto** [comment]
turns out that https://github.com/getsentry/sentry-cli/blob/master/src/commands/upload_proguard.rs#L41-L72 is dead code so sentry-cli needs to support such new properties and Sentry UI should offer a way to display and filter such new properties

**Comment by markushi** [comment]
@jan-auer it looks like we had a similar feature in the distant past: https://github.com/getsentry/sentry/pull/10246 Any chance you remember why it was removed?
