### ISSUE TITLE
Gradle's Configuration caching is broken after 3.3.0 version

### ISSUE THREAD

**Issue by audkar** [getsentry/sentry-android-gradle-plugin#407]
### Gradle Version

7.5.1

### AGP Version

7.3.1

### Version

3.3.0

### Sentry SDK Version

6.7.0

### Steps to Reproduce

1. Apply sentry-android-gradle-plugin
2. Build android application `gradle :app:assembleDebug`

---

ours sentry config in Gradle:
```kotlin
    autoUploadProguardMapping.set(true)
    uploadNativeSymbols.set(false)
    includeNativeSources.set(false)
    autoInstallation.enabled.set(false)
    tracingInstrumentation.enabled.set(false)
    includeDependenciesReport.set(false)
//    ignoredBuildTypes.set(listOf("debug"))
```

If I ignore `debug` build type, Gradle's configuration cache works as expected. [Suspect code](https://github.com/getsentry/sentry-android-gradle-plugin/blame/b807e95be4aa1d188548b0f67559986b233afb67/plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryExternalDependenciesReportTask.kt#L31)

This regression added ~1min to our builds.

### Expected Result

```
BUILD SUCCESSFUL in 19s
3555 actionable tasks: 4 executed, 3551 up-to-date

Configuration cache entry stored.
```

### Actual Result

```
BUILD SUCCESSFUL in 12s
3556 actionable tasks: 3 executed, 1 from cache, 3552 up-to-date

Configuration cache entry discarded.
```

**Comment by romtsn** [comment]
hmm, so even if you disable the task it still breaks the configuration cache? I mean the `includeDependenciesReport.set(false)` flag.

I guess we'd need to find a way to not register the task at all if it's disabled, rather than using `onlyIf` in the init block...

**Comment by audkar** [comment]
> so even if you disable the task it still breaks the configuration cache? 

Yes.

**Comment by romtsn** [comment]
There are 2 problems here:
1. We should fix the `includeDependenciesReport` flag to actually disable the task and its configuration completely, so it doesn't break the config cache.
2. We should support the new Gradle 7.5. feature, which does not break the config cache.

Maybe we could also disable it for debug builds

**Comment by romtsn** [comment]
@audkar version `3.4.0` of the plugin should fix both of the issues:
* `includeDependenciesReport`  will not register the task anymore when disabled, therefore will not invalidate the configuration cache
* When you're on Gradle 7.5+ the task should respect configuration cache

please, give it a try

**Comment by audkar** [comment]
Yup. Can confirm that the issue was fixed for us. Thank you :bow:
