### ISSUE TITLE
Gradle Plugin for Java Applications

### ISSUE THREAD

**Issue by leonard84** [getsentry/sentry-android-gradle-plugin#429]
### Problem Statement

Currently, sentry only has a Gradle plugin for Android builds that integrates tightly into AGP.

We are developing Java applications, and want to use the release announcement as well as proguard mapping file upload functionality in a regular `java` Gradle build.

### Solution Brainstorm

Extract common functionality from the `sentry-android-gradle-plugin` into a shared component and create a `sentry-gradle-plugin` that offers tasks to announce a release as well as upload proguard mapping files.

**Comment by romtsn** [comment]
hi @leonard84, thanks for the request. We have #403 for tracking that already, would you mind upvoting that issue and writing a comment summarizing your requirements? We'd like to consolidate feedback/requirements under a single issue.

We do not have release announcement as a feature at the moment, but I think we could add it (you mean auto-generating/deriving release name during the build by that, correct?). 

Also, could you elaborate on what kind of JVM apps you're developing (so we could add them to our samples and test) and what obfuscation tool are you using and how (proguard or r8? is it a custom task or through the proguard gradle plugin? etc.)

Thank you!
