### ISSUE TITLE
Add the ability to supply auth token through the Gradle Plugin extension

### ISSUE THREAD

**Issue by R4md4c** [getsentry/sentry-android-gradle-plugin#440]
### Problem Statement

We depend on hosting our project's credentials via a single .properties  file which includes all the credentials/token needed to build the project, however, for Sentry it seems that we have to maintain a separate `sentry.properties` to include the token there, so I was asking if we could basically supply the auth token via the Sentry Plugin extension and read it from our central `.properties` file instead?

### Solution Brainstorm

I know that Sentry supports specifying an auth token, orgId and projectId via the sentry.properties file, but I think being able to specify these three params via the extension provides more flexibility for the user to supply these parameters via different means e.g. reading it from a file other than `sentry.properties`. 

So I can imagine something like 

```
sentry {
    orgId = providers.gradleProperty('sentryOrgId')
    projectId = providers.gradleProperty('sentryProjectId')
    authToken = providers.gradleProperty('sentryAuthToken')
}
```

**Comment by romtsn** [comment]
In addition, we should also provide an easier way to set the debug log level, e.g.

```gradle
sentry {
  debug = true
}
```
instead of juggling environment variables.

**Comment by markushi** [comment]
Let's focus on providing auth properties within this task.
