### ISSUE TITLE
A proguard mapping file does not contain line info.

### ISSUE THREAD

**Issue by mfperminov** [getsentry/sentry-android-gradle-plugin#460]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.3.1

### Proguard

Enabled

### Version

3.4.2

### Steps to Reproduce

I build release version of an app, mappings files are succefully uploaded and appeared in Debug files section by sentry gradle plugin. When I see an issue there is an error

_A proguard mapping file does not contain line info
Mapping Uuid | {uuid from debug file}_

Proguard files settings
```
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
```
R8 version is 3.3.83
Found old issue https://github.com/getsentry/sentry-java/issues/688, but there is no help

### Expected Result

stack trace is retraced

### Actual Result

stack trace is not retraced

**Comment by romtsn** [comment]
hey, but can you confirm the line numbers are present in the actual `mapping.txt` file?

**Comment by mfperminov** [comment]
Yes, example of generated mappings.txt
![image](https://user-images.githubusercontent.com/31574119/228929093-a0c4ceab-3acc-4465-9a53-5ca37e72b9f5.png)

**Comment by romtsn** [comment]
> Yes, example of generated mappings.txt ![image](https://user-images.githubusercontent.com/31574119/228929093-a0c4ceab-3acc-4465-9a53-5ca37e72b9f5.png)

great, thanks, we'll investigate from our side then!

**Comment by mfperminov** [comment]
original code OnboardingActivity.kt 153:162
```
act_onboarding__btnMain.setOnLongClickListener(object : View.OnLongClickListener {
            override fun onLongClick(v: View?): Boolean {
                try {
                    error("This is sentry test")
                } catch (e: Exception) {
                    Sentry.captureException(e)
                }
                return true
            }
        })
```
clipping from mapping.txt
```
    com.tabee.android.presentation.screen.onboarding.ac.OnboardingActivity com.tabee.android.presentation.screen.onboarding.ac.OnboardingActivity$showPrivacyView$1$$InternalSyntheticLambda$1$29d4ea26f6eb72cdedc0c5c8772b1239d867d5d07f0c548a992eb80cf0a424bc$0.f$0 -> a
    void com.tabee.android.presentation.screen.onboarding.ac.OnboardingActivity$showPrivacyView$1$$InternalSyntheticLambda$1$29d4ea26f6eb72cdedc0c5c8772b1239d867d5d07f0c548a992eb80cf0a424bc$0.<init>(com.tabee.android.presentation.screen.onboarding.ac.OnboardingActivity) -> <init>
      # {"id":"com.android.tools.r8.synthesized"}
    void com.tabee.android.presentation.screen.onboarding.ac.OnboardingActivity$showPrivacyView$1$$InternalSyntheticLambda$1$29d4ea26f6eb72cdedc0c5c8772b1239d867d5d07f0c548a992eb80cf0a424bc$0.run() -> run
      # {"id":"com.android.tools.r8.synthesized"}
com.tabee.android.presentation.screen.onboarding.ac.OnboardingActivity$showPrivacyView$2 -> com.tabee.android.presentation.screen.onboarding.ac.OnboardingActivity$h:
# {"id":"sourceFile","fileName":"OnboardingActivity.kt"}
    1:4:boolean onLongClick(android.view.View):155:155 -> onLongClick
    5:13:boolean onLongClick(android.view.View):156:156 -> onLongClick
    14:18:boolean onLongClick(android.view.View):158:158 -> onLongClick
com.tabee.android.presentation.screen.onboarding.ac.OnboardingActivity$showPrivacyView$3 -> com.tabee.android.presentation.screen.onboarding.ac.OnboardingActivity$i:
# {"id":"sourceFile","fileName":"OnboardingActivity.kt"}
```
this is how it looks like in Sentry
![image](https://user-images.githubusercontent.com/31574119/228934262-8c2d0136-dd4a-4489-9a61-1496600f51b6.png)
![image](https://user-images.githubusercontent.com/31574119/228934322-3e5fe2dd-1118-436a-99a6-5bd5ea236520.png)

**Comment by mfperminov** [comment]
Yes, looks like this

**Comment by adinauer** [comment]
@mfperminov can you please check if you can download the mapping file by going to the Sentry UI, Project Settings, ProGuard and there try to download the relevant file?

**Comment by mfperminov** [comment]
Yes, I can download it, debug id matches uuid in issues
![Screenshot_2023-03-31_12-01-21](https://user-images.githubusercontent.com/31574119/229076626-ffbddec4-55dc-4f10-ac48-5fb8dfef7be1.png)

**Comment by mfperminov** [comment]
Later I will check it with different combinations of r8, agp and sentry plugin, will write results later

**Comment by mfperminov** [comment]
I update sentry plugin to latest 3.4.3 version and tried again. First, I delete old debug file, made an release build, checked that new mapping was uploaded and now error shows that I do not have proguard file at all, but it points to an file with old uuid, that I previously deleted
Maybe I miss setup in AndroidManifest?

**Comment by romtsn** [comment]
@mfperminov can you try updating AGP version to 7.4+? This should resolve the issue I believe

**Comment by mfperminov** [comment]
Yes, I updated to agp 7.4.2 and now it works, thanks!
