### ISSUE TITLE
Cannot use Sentry for a specific build only

### ISSUE THREAD

**Issue by georgkrause** [getsentry/sentry-android-gradle-plugin#463]
### Gradle Version

7.6.0

### AGP Version

7.0.0

### Code Minifier/Optimizer

None

### Version

3.4.3

### Sentry SDK Version

6.17.0

### Steps to Reproduce

Add sentry to android app, with `apply false`.
Only apply it for Debug builds
Run `./gradlew assembleRelease`

### Expected Result

Gradle builds a release built without sentry

### Actual Result

It fails because Sentry tries to upload source maps, which cannot be disabled because the plugin is not applied for this specific build.

**Comment by romtsn** [comment]
hi @georgkrause, could you please share how exactly do you apply the plugin for debug builds, and what is the error your get?

**Comment by georgkrause** [comment]
Sure:

```kotlin
// app/build.gradle.kts

plugins {
...
  id("io.sentry.android.gradle") version "3.4.3" apply false
...
}

android {
  ...
  buildTypes {
    getByName("debug") {
      ...
      apply(plugin = "io.sentry.android.gradle")
      ...
    }
  }
}
```

Now I get something like

```
> Task :app:dataBindingMergeDependencyArtifactsRelease UP-TO-DATE
[sentry] sentry-android-okhttp won't be installed because the current version is lower than the minimum supported version (3.13.0)

> Task :app:uploadSentryProguardMappingsRelease FAILED
> compressing mappings
> uploading mappings
error: An organization slug is required (provide with --org)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:uploadSentryProguardMappingsRelease'.
> Process 'command '/tmp/.sentry-cli7312389467539933532.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

If I add

```
sentry {
  includeProguardMapping.set(false)
}
```

I get 

```
> Configure project :app
e: /home/georg/workspace/funkwhale/android/app/build.gradle.kts:280:1: Unresolved reference: sentry
e: /home/georg/workspace/funkwhale/android/app/build.gradle.kts:281:3: Unresolved reference: includeProguardMapping

FAILURE: Build failed with an exception.

* Where:
Build file '/home/georg/workspace/funkwhale/android/app/build.gradle.kts' line: 280

* What went wrong:
Script compilation errors:

  Line 280: sentry {
            ^ Unresolved reference: sentry

  Line 281:   includeProguardMapping.set(false)
              ^ Unresolved reference: includeProguardMapping

2 errors

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

If I apply the plugin globally, the latter works, but I do not want to have sentry in all builds

**Comment by romtsn** [comment]
I genuinely think this syntax is not supposed to work as you expect:

```gradle
android {
  ...
  buildTypes {
    getByName("debug") {
      ...
      apply(plugin = "io.sentry.android.gradle")
      ...
    }
  }
}
```

For this to work, AGP has to provide some special per-variant handling, but they do not do that as far as I know. That's why the plugin is applied to all variants, because it just uses the standard Gradle plugin application block.

---
If your goal is to only have the plugin work for debug builds, you can easily achieve this by configuring sentry to ignore release build types as mentioned in the [docs](https://docs.sentry.io/platforms/android/gradle/#variant-filtering):
```gradle.kts
plugins {
...
  id("io.sentry.android.gradle") version "3.4.3"
...
}

android {
  ...
  buildTypes {
    getByName("debug") {
      ...
      ...
    }
  }
}

sentry {
    ignoredBuildTypes.add("release")
}
```
Would that help with your case?

**Comment by georgkrause** [comment]
@romtsn Thank you for the hint! I already considered this actually, but its not fully clear to me what this ignoring actually means. Will Sentry just not send anything for a ignored build or will it not even run? I want to make sure there is no sentry code running in the final APK

**Comment by georgkrause** [comment]
> For this to work, AGP has to provide some special per-variant handling, but they do not do that as far as I know. That's why the plugin is applied to all variants, because it just uses the standard Gradle plugin application block.

If this is true I am wondering why I cannot configure sentry like I showed in the last example above. For me it looks like sentry is not known to Gradle, am I missing something?

**Comment by romtsn** [comment]
> @romtsn Thank you for the hint! I already considered this actually, but its not fully clear to me what this ignoring actually means. Will Sentry just not send anything for a ignored build or will it not even run? I want to make sure there is no sentry code running in the final APK

https://github.com/getsentry/sentry-android-gradle-plugin/blob/8d5ef9055fc86b1ede53384cd638b56f434cdb50/plugin-build/src/main/kotlin/io/sentry/android/gradle/AppConfig.kt#L38 
it will basically not do anything, not configure any tasks, not create any tasks, so it should feel like there's not sentry plugin applied to the build.

The only thing it will still try to do is to auto-install Sentry Android SDK and integrations, but you can also disabled it
```kotlin
sentry {
  autoInstallation.enabled.set(false)
}
```

**Comment by romtsn** [comment]
> > For this to work, AGP has to provide some special per-variant handling, but they do not do that as far as I know. That's why the plugin is applied to all variants, because it just uses the standard Gradle plugin application block.
> 
> If this is true I am wondering why I cannot configure sentry like I showed in the last example above. For me it looks like sentry is not known to Gradle, am I missing something?

it's because you do not apply the plugin for the app module, but still trying to configure it (the order of plugin application matters here). I guess if you'd move it inside where you apply the plugin, then it'd probably work, but would look weird to me:

```gradle.kts
android {
  ...
  buildTypes {
    getByName("debug") {
      ...
      apply(plugin = "io.sentry.android.gradle")
      sentry.includeProguardMapping.set(false)
    }
  }
}

// alternatively you could use afterEvaluate, but this is also wrong
afterEvaluate {
  sentry.includeProguardMapping.set(false)
}
```

**Comment by georgkrause** [comment]
> it's because you do not apply the plugin for the app module, but still trying to configure it (the order of plugin application matters here).

In this case I would assume it wouldn't do anything, but it does try to upload the source maps. 

However, I slowly get the intention its not possible to have sentry only available in some builds using this method. Maybe I will come up with another approach. Thank you for your help!
