### ISSUE TITLE
Auto instrument OkHttp client with SentryOkHttpEventListener

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-android-gradle-plugin#477]
### Description

Once the [SentryOkHttpEventListener pr](https://github.com/getsentry/sentry-java/pull/2659) is merged, we could autoinstrument the OkHttp clients with it, other than the `SentryOkHttpInterceptor`.
The only thing to take care of is that OkHttp allows only one `EventListener` at a time, so we shouldn't add ours if the user already set one.
We can do this by either changing the default `OkHttpClient.Builder` constructor and inject our listener or by using a wrapper around it

**Comment by kahest** [comment]
@stefanosiano has this been resolved with https://github.com/getsentry/sentry-android-gradle-plugin/pull/504 and https://github.com/getsentry/sentry-android-gradle-plugin/pull/508?
