### ISSUE TITLE
Release with `craft`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-android-gradle-plugin#48]
https://github.com/getsentry/craft

Set the version on the docs: https://docs.sentry.io/platforms/android/proguard/

manage changelog, push to repositories etc

**Comment by iker-barriocanal** [comment]
- Changelog is managed by the [pre](https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/scripts/bump-version.sh) and [post](https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/scripts/post-release.sh) release scripts.
- GitHub and the release registry are [already managed](https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/.craft.yml#L6-L9) by Craft.
- Doing the actual release with Craft will be done when https://github.com/getsentry/sentry-android-gradle-plugin/pull/149 gets merged.
