### ISSUE TITLE
Improve up-to-date checking for ProGuard mapping and source bundle upload

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-android-gradle-plugin#485]
### Description

Currently the IDs for ProGuard mapping and source bundle are always generated.

We use `outputs.upToDateWhen { false }`.

They should only be generated if inputs (i.e. proguard mapping file / source) change.

We should use source inputs (used for CollectSourcesTask) as input for GenerateBundleIdTask to inherit up-to-date checking.

tbd more details for ProGuard

**Comment by romtsn** [comment]
this was resolved by #634
