### ISSUE TITLE
How do I allow Sentry to fail during the build phase?

### ISSUE THREAD

**Issue by rakuyoMo** [getsentry/sentry-android-gradle-plugin#487]
### Description

Our self-built Sentry service is not stable, for example, it may sometimes throw 404 or 503 errors. At this time the ipa build may have succeeded, but the CI pipeline failed due to sentry-cli failure.

We want to use Sentry to upload debug information without affecting the status of CI pipeline, how to implement this feature?

Because we are using this plugin, we may not be able to make this step as a separate job?This is how I currently understand it.

**Comment by romtsn** [comment]
We don't provide a configuration option for that out of the box, but you can achieve that via configuring the gradle task as follows:
```kts
tasks.withType<SentryUploadProguardMappingsTask> {
    setIgnoreExitValue(true)
}
```

Would that be sufficient for you?

**Comment by rakuyoMo** [comment]
> We don't provide a configuration option for that out of the box, but you can achieve that via configuring the gradle task as follows:
> 
> ```kotlin
> tasks.withType<SentryUploadProguardMappingsTask> {
>     setIgnoreExitValue(true)
> }
> ```
> 
> Would that be sufficient for you?

This setting does not work, and the task still blocks subsequent processes after reporting an error, and eventually fails to generate the ipa file.

**Comment by romtsn** [comment]
> > We don't provide a configuration option for that out of the box, but you can achieve that via configuring the gradle task as follows:
> > ```kotlin
> > tasks.withType<SentryUploadProguardMappingsTask> {
> >     setIgnoreExitValue(true)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would that be sufficient for you?
> 
> This setting does not work, and the task still blocks subsequent processes after reporting an error, and eventually fails to generate the ipa file.

can you provide more details or a reproducible sample? I just tested it on one of our sample projects and it worked just fine.

**Comment by romtsn** [comment]
@rakuyoMo have you had a chance to look into this again? Is your issue resolved now? thanks

**Comment by rakuyoMo** [comment]
> @rakuyoMo have you had a chance to look into this again? Is your issue resolved now? thanks

Sorry, we've been a little busy with work lately, so we don't have time to keep trying this for now. 
But it's coming soon, and we expect to try again next week.

**Comment by rakuyoMo** [comment]
We solved this problem and the above code is valid. 

The problem is that the `--continue` parameter is added to the package, i.e. using `. /gradlew assembleRelease --continue` command to perform the packaging operation. 

We did not add this parameter before, so `setIgnoreExitValue` did not take effect.
