### ISSUE TITLE
Sentry properties multiple apps module in same project

### ISSUE THREAD

**Issue by nicolasjafelle** [getsentry/sentry-android-gradle-plugin#5]
I am testing Sentry crash report with the proguard plugin in our Android Apps.
My main concern if it is possible to have different `sentry.properties` in the same project.

Our project has two apps module but it seems the `sentry.properties` goes in the project root level:
```
project
--> sentry.properties
    --> app1
    --> app2
```

Is it possible to be like this?

```
project
    --> app1
    --> sentry.properties
    --> app2
    --> sentry.properties
```

Thanks in advance!

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
