### ISSUE TITLE
Auto install Sentry SDK and integrations for Java

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-android-gradle-plugin#503]
### Problem Statement

For Android we already auto install the Sentry SDK and other Sentry dependencies if the project uses libraries we have integrations for. We should provide the same functionality for Backend, Desktop, etc.

### Solution Brainstorm

Copy what's available for Android.

**Comment by smeubank** [comment]
auto configure extra features in plugin and potentially bytecode manipulation

**Comment by smeubank** [comment]
consider ways to add telemetry to plugin (similar to JS bundler plugins) or something more generically in sentry-cli similar to user-agent approach
