### ISSUE TITLE
When building locally the plugin should not interact with the Sentry API when no auth token is configured

### ISSUE THREAD

**Issue by alexkops** [getsentry/sentry-android-gradle-plugin#525]
### Problem Statement

Given: A Spring Boot project with gradle and the sentry gradle plugin configured.
When running `gradle build` on a project locally and no Sentry auth token set, the task `sentryBundleSourcesJava` is executed nevertheless and tries to interact with the Sentry API (unsuccessfully: `Authentication credentials were not provided. (http status: 401)`).
Even when the setting `includeSourceContext.set(false)` is given.

### Solution Brainstorm

I'd like to have the property to either skip all Sentry tasks completely, or otherwise do a dry run which doesn't interact with the API.
Something like 
```
sentry {
   enabled = System.getenv("SENTRY_AUTH_TOKEN") != null
}
```

So far our workaround is:
``` 
tasks.withType(BundleSourcesTask::class.java) {
    enabled = System.getenv("SENTRY_AUTH_TOKEN") != null
}
```

That's fine, too. Maybe that just needs to documented somewhere.

**Comment by adinauer** [comment]
Thanks for the report @alexkops that's an oversight on our part. We'll talk about how we wanna fix, then update here.

**Comment by adinauer** [comment]
We'll make sure we honor the `includeSourceContext` option and skip tasks related to source context unless set to `true`.
We can't specifically look for the auth token option / variable etc. because there's lots of ways of configuring `sentry-cli` so checking `includeSourceContext` ist the next best thing.

**Comment by Omar-Salem** [comment]
@alexkops solution did not work for me, got error ` Could not get unknown property 'java' for task ':sentryBundleSourcesJava' `

so I wrapped the `sentry` block in an if condition.
