### ISSUE TITLE
Only run debug symbol upload on CI

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-android-gradle-plugin#529]
### Problem Statement

I want to only upload debug symbols on CI, but not on local release builds.

### Solution Brainstorm

Add an option which disables the upload, which can be set via environment variables or via the gradle configuration.

**Comment by romtsn** [comment]
https://github.com/getsentry/sentry-android-gradle-plugin/blob/6e2c35fa32bc089939046afc4d590ea965777ffe/examples/android-ndk/build.gradle#L42

This is already possible, or are you looking for something different?

**Comment by ueman** [comment]
Thanks, I didn't know that option.
In order to disable all uploads on local non-CI, I would have to set 
```groovy
 autoUploadNativeSymbols = CI.INSTANCE.canAutoUpload()
 autoUploadProguardMapping = CI.INSTANCE.canAutoUpload()
```

Is that correct? 

Where does the `CI.INSTANCE.canAutoUpload()` come from? When I add that to my Gradle file, I get the following issue:
```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'CI' for extension 'sentry' of type io.sentry.android.gradle.extensions.SentryPluginExtension
```
I'm still using Groovy files, if that matters.

BTW, `autoUploadNativeSymbols` isn't mentioned on https://docs.sentry.io/platforms/android/configuration/gradle/

**Comment by romtsn** [comment]
> Thanks, I didn't know that option. In order to disable all uploads on local non-CI, I would have to set
> 
> ```groovy
>  autoUploadNativeSymbols = CI.INSTANCE.canAutoUpload()
>  autoUploadProguardMapping = CI.INSTANCE.canAutoUpload()
> ```
> 
> Is that correct?

Yes, that's right.

> Where does the `CI.INSTANCE.canAutoUpload()` come from? When I add that to my Gradle file, I get the following issue:
> 
> ```
> Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'CI' for extension 'sentry' of type io.sentry.android.gradle.extensions.SentryPluginExtension
> ```
> 
> I'm still using Groovy files, if that matters.

This is our custom method that checks for the presence of SENTRY_AUTH_TOKEN env variable that is only present on CI in our case (I think this is what you'd like to do as well). https://github.com/getsentry/sentry-android-gradle-plugin/blob/6e2c35fa32bc089939046afc4d590ea965777ffe/buildSrc/src/main/java/Dependencies.kt#L59-L64

> BTW, `autoUploadNativeSymbols` isn't mentioned on [docs.sentry.io/platforms/android/configuration/gradle](https://docs.sentry.io/platforms/android/configuration/gradle/)

Right, we missed it. I'll update the docs, thanks!

**Comment by ueman** [comment]
Thank you, that was helpful. I'll mark this issue as resolved.
