### ISSUE TITLE
Execution failed for task ':app:uploadSentryProguardMappingsRelease'

### ISSUE THREAD

**Issue by VahidGarousi** [getsentry/sentry-android-gradle-plugin#551]
### Gradle Version

8.2

### AGP Version

8.1.1

### Code Minifier/Optimizer

R8

### Version

3.12.0

### Sentry SDK Version

6.28.0

### Steps to Reproduce

Just Generate signed apk in release mode ( widout sentry.properties or with sentry.properteis) file

### Expected Result

i want to  uploadSentryProguardMappingsRelease task succedd

### Actual Result

> Task :app:uploadSentryProguardMappingsRelease FAILED
Execution failed for task ':app:uploadSentryProguardMappingsRelease'.
> Process 'command 'cmd'' finished with non-zero exit value -1073741515

**Comment by adinauer** [comment]
Hello @VahidGarousi can you please enable `debug` and rerun? It should give you a more detailed error message from `sentry-cli`.

`build.gradle`:

```
...
sentry {
  debug = true // or debug.set(true) if you're using build.gradle.kts
}
...
```

**Comment by romtsn** [comment]
@VahidGarousi you can also just look at the entire gradle log - somewhere in the middle of it, where the `uploadSentryProguardMappingsRelease` has been run, should the exact reason why it's failed. You can start your gradle build with `--console=plain` for convenient output as well

**Comment by VahidGarousi** [comment]
I did what you said, the error is as follows:
```
> Task :app:uploadSentryProguardMappingsStagingRelease
  INFO    2023-09-04 15:29:05.586986 +03:30 Loaded file referenced by SENTRY_PROPERTIES (D:\app\sentry.properties)
  DEBUG   2023-09-04 15:29:05.589237200 +03:30 sentry-cli version: 2.20.3, platform: "windows", architecture: "i686"
  INFO    2023-09-04 15:29:05.589267 +03:30 sentry-cli was invoked with the following command line: "C:\Users\VE937~1.GAR\AppData\Local\Temp\.sentry-cli6620988688368794775.exe" "--log-level=debug" "upload-proguard" "--uuid" "4cef618b-668a-4424-8d11-78977d026cf8" "D:\app\build\outputs\mapping\stagingRelease\mapping.txt" "--version-code" "1" "--app-id" "staging" "--version" "1.0.0"
error: memory map length overflows isize
  DEBUG   2023-09-04 15:29:06.371679400 +03:30 skipping update nagger because session is not attended
```

**Comment by VahidGarousi** [comment]
this is my gradle.properties file

```
org.gradle.jvmargs=-Xmx8g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g -XX:MaxPermSize=512m

```

**Comment by romtsn** [comment]
sounds very similar to https://github.com/getsentry/sentry-cli/issues/1267, perhaps we should look for similar patterns (like parsing big files as mentioned in that issue?)

**Comment by VahidGarousi** [comment]
I noticed an issue, is the size of the Mapping in this path 
```
app\build\outputs\mapping\stagingRelease 
```
file equal to 2,511,733 KB, is it normal?

**Comment by romtsn** [comment]
@VahidGarousi 2,5 GB no, that doesn't look normal. I don't think we support uploading files of more than 1 GB size. How big is your application? Could you also share your proguard/r8 rules?

**Comment by romtsn** [comment]
@lianyagang this is unrelated, you have to specify a flavour which you want to upload your proguard mappings for, e.g. `uploadSentryProguardMappingsGoogleRelease` instead of generic `uploadSentryProguardMappingsRelease`

**Comment by romtsn** [comment]
@VahidGarousi I've just confirmed internally, this is a limitation you're hitting on a 32-bit Windows, where we can only support mappings of 2G or less. I'd suggest you tweak your proguard/r8 configuration or find out why the mapping file is so huge.

**Comment by VahidGarousi** [comment]
@romtsn I will check the point you mentioned and let you know the result

**Comment by VahidGarousi** [comment]
I evaluated most of the libraries I had and modified their ProGuard
But when I generate signed apk with the following configuration ,

```
         isDebuggable = true
            signingConfig = signingConfigs.getByName("release")
            isMinifyEnabled = true
            isShrinkResources = true
            versionNameSuffix = BuildType.RELEASE.versionNameSuffix
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
```



 I encounter the following:


```

> Task :app:l8DexDesugarLibStagingRelease
Info: Proguard configuration rule does not match anything: `-keepclassmembers class j$.util.concurrent.ConcurrentHashMap$TreeBin {
  int lockState;
}`
Info: Proguard configuration rule does not match anything: `-keepclassmembers class j$.util.concurrent.ConcurrentHashMap {
  int sizeCtl;
  int transferIndex;
  long baseCount;
  int cellsBusy;
}`
Info: Proguard configuration rule does not match anything: `-keepclassmembers class j$.util.concurrent.ConcurrentHashMap$CounterCell {
  long value;
}`
Info: Proguard configuration rule does not match anything: `-keepclassmembers class j$.util.IntSummaryStatistics {
  long count;
  long sum;
  int min;
  int max;
}`
Info: Proguard configuration rule does not match anything: `-keepclassmembers class j$.util.LongSummaryStatistics {
  long count;
  long sum;
  long min;
  long max;
}`
Info: Proguard configuration rule does not match anything: `-keepclassmembers class j$.util.DoubleSummaryStatistics {
  long count;
  double sum;
  double min;
  double max;
}`
```

**Comment by VahidGarousi** [comment]
@romtsn  please check this

**Comment by markushi** [comment]
@VahidGarousi any chance you had some time to look into this?

**Comment by markushi** [comment]
@VahidGarousi We're closing this issue for now, if you have to look into it and still think the issue is on our end, feel free to re-open it.

**Comment by J0306** [comment]
> 我会检查你提到的一点，让你知道结果

请问您解决了该问题吗  我现在也遇到了

**Comment by syedjiba** [comment]
I'm also getting the same issue.

**Comment by markushi** [comment]
@syedjiba @J0306 could share some log outputs? The comments above mention how to enable debugging. 
On top of that: Are you using a self-hosted sentry? If so, tweaking your config (especially `limits.max_api_file_upload_size` and `limits.max_api_chunk_upload_size` might help) - [see the docs](https://docs.sentry.io/product/relay/options/#relay) for more details about this.

**Comment by markushi** [comment]
Closing this for now since we haven't heard back from you. If you still think the issue persists, please leave a comment!
