### ISSUE TITLE
Issue with kotlin version update to 1.8.0 or above

### ISSUE THREAD

**Issue by droideveloper** [getsentry/sentry-android-gradle-plugin#564]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.2 above

### Proguard

Enabled

### Version

6.29.0

### Steps to Reproduce

when I just bump to kotlin version to 1.8.0 or above
I suspect issue comes from "io.sentry.kotlin.compiler.gradle"

### Expected Result

success

### Actual Result

e: java.lang.NullPointerException
        at io.sentry.compose.JetpackComposeTracingIrExtension.generate(JetpackComposeTracingIrExtension.kt:56)

**Comment by droideveloper** [comment]
Hey @romtsn 👋 ,
sorry for inconvenience, it looks like issue was in our end the way we apply plugin on all modules, I think when I filter for android or android-library, it did not try to run it on java modules, we could close it.

**Comment by romtsn** [comment]
hi @droideveloper thanks for coming back. I was about to post a question asking additional details, because our plugin is currently running with kotlin 1.8.0 on our samples, so there should be no problem with that. But glad that you figured it out yourself. I'm gonna close the issue, thanks again!
