### ISSUE TITLE
io.sentry.jvm.gradle: Failed to parse org auth token {token} 

### ISSUE THREAD

**Issue by dmitry-cherkas** [getsentry/sentry-android-gradle-plugin#571]
### Gradle Version

8.1.1

### AGP Version

-

### Code Minifier/Optimizer

None

### Version

3.13.0

### Sentry SDK Version

6.3.0

### Steps to Reproduce

I'm trying to set up  [Source Context](https://docs.sentry.io/platforms/java/guides/logback/source-context/) with `io.sentry.jvm.gradle:3.13.0` for a self-hosted Sentry `23.8.0`.

When I run `./gradlew assemble`, the build is failing with an error:
```
> Task :sentryBundleSourcesJava FAILED
16 actionable tasks: 10 executed, 6 up-to-date
error: Failed to parse org auth token {token}
  caused by: invalid type: null, expected a string at line 1 column 34
```

I see that my token contains `url: null`, which is probably what's causing the issue:
```
{
  "iat": 1697044638.32975,
  "url": null,
  "region_url": "https://....",
  "org": "..."
}
```

I've found this CLI tickets that seem to be related: https://github.com/getsentry/sentry-cli/issues/1765 and a fix is already implemented here: https://github.com/getsentry/sentry-cli/issues/1763 , but apparently the Gradle plugin is using an older version of CLI, since even with the `SENTRY_URL` env variable defined, I'm still getting the same error.

### Expected Result

Gradle plugin should make use of the latest Sentry CLI that supports `url: null` in the `authToken`(smth like this: https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/415).

Ideally, Gradle plugin should expose a configuration option to allow passing the `--url` parameter to the Sentry CLI, or it should be possible to re-define the url via `SENTRY_URL` environment variable.

### Actual Result

When I run `./gradlew assemble`, the build is failing with an error:
```
> Task :sentryBundleSourcesJava FAILED
16 actionable tasks: 10 executed, 6 up-to-date
error: Failed to parse org auth token {token}
  caused by: invalid type: null, expected a string at line 1 column 34
```

**Comment by adinauer** [comment]
Thanks for opening this issue and doing all the investigation for us @dmitry-cherkas. We'll bump sentry-cli and release a new version of the gradle plugin.

**Comment by adinauer** [comment]
It's already been bumped, we'll do a release soon.
