### ISSUE TITLE
Stacktraces not deobfuscating despite mapping.txt upload

### ISSUE THREAD

**Issue by markberginzeller** [getsentry/sentry-android-gradle-plugin#583]
### Description

Running gradle version 8.3,
AGP version 8.1.1

Running Sentry configuration
```
sentry {
    includeSourceContext.set(true)
    includeProguardMapping.set(true)
    autoUploadProguardMapping.set(true)
}
```

Can see that mapping.txt upload properly works and it associates to the correct version in Sentry.
However when looking at Sentry.io the stacktrace is still obsfucated.

Have added to proguard-rules.pro
```
# Sentry
-keep class io.sentry.** { *; }
-dontwarn io.sentry.**
```

Can see that `sentry-debug-meta.properties` is packaged in with the apk assets with the ProguardUuids matching what I expect.
Is there any other trouble shooting steps that I've missed?

Thanks!

<img width="1466" alt="Screenshot 2023-10-23 at 4 57 41 pm" src="https://github.com/getsentry/sentry-android-gradle-plugin/assets/124638350/c4242672-a326-4e3c-8305-7d0ecb4f85d3">
<img width="548" alt="Screenshot 2023-10-23 at 4 58 49 pm" src="https://github.com/getsentry/sentry-android-gradle-plugin/assets/124638350/a9c7f820-56aa-46c9-89c0-5aea3bbfc5e9">

**Comment by markberginzeller** [comment]
It's an Android project using sentry.io.
Took a look at the payload and can't find a `proguard_uuid` field listed.

Is there anything else needed other than a `sentry-debug-meta.properties` under the root assets?

**Comment by romtsn** [comment]
@markberginzeller apologies, I was wrong, it's just called `proguard`, so should look similar to this in the event payload:

```json
  "debug_meta": {
    "images": [
      {
        "uuid": "467ade76-6d0b-11ed-a1eb-0242ac120002",
        "type": "proguard"
      }
    ]
  },
```

Having `sentry-debug-meta.properties` under the root assets with the proper uuid should be enough so the SDK retrieves it at runtime and sends along with every event. If you don't have `proguard` in your event payloads, but you can see it in assets from the same build/apk, I'd ask you to create a reproducible sample so we could investigate.

**Comment by markberginzeller** [comment]
All good!  After your response I went digging into the sdk sourcecode for it's initialisation, lead me down to the realisation that during our setup I had used a `Sentry.init` initialisation rather than `SentryAndroid.init`.... Silly mistake to make!

Thanks for the support, closing the thread 👍
