### ISSUE TITLE
Sentry Room integration breaks Room Kotlin CodeGen

### ISSUE THREAD

**Issue by G00fY2** [getsentry/sentry-android-gradle-plugin#585]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.1.2

### Proguard

Enabled

### Version

6.32.0

### Steps to Reproduce

- set up a project with `androidx.room:room-*:2.6.0`
- use KSP and set [`room.generateKotlin` to true](https://developer.android.com/jetpack/androidx/releases/room#2.6.0)
- build project with R8 enabled

### Expected Result

Compilation should succeed

### Actual Result

R8 fails in Room Dao classes:
`R8: java.lang.NullPointerException: Cannot read field "d" because "<parameter1>" is null`

First I did not have Sentry in mind when we faced this issue. Therefore also check out the issue in the Android issue tracker created by me: https://issuetracker.google.com/issues/306360975

**Comment by romtsn** [comment]
Hi, indeed sounds like an incompatible change have been made to Room's generated code, which breaks our auto-instrumentation. We'll look into this, thanks for reporting!

**Comment by stefanosiano** [comment]
I put the generated classes and the updated config in a new branch, so we can test it: https://github.com/getsentry/sentry-android-gradle-plugin/tree/fix/room-generate-kotlin

**Comment by markushi** [comment]
Let's look at the generated bytecode of the room classes. We're suspecting the lack of the return state in Kotlin (as opposed to Java) to be the culprit.

**Comment by ninniuz** [comment]
Hi guys, do you have any update on this? It is currently blocking us from adopting Room Kotlin CodeGen :(

**Comment by G00fY2** [comment]
@ninniuz but you know that you can [disable Sentries room integration](https://docs.sentry.io/platforms/android/integrations/file-io/#configure), right?

This is how we workaround this (ofc you loos track of your Room metrics).

**Comment by ninniuz** [comment]
@G00fY2 yes I know :) But I would like to keep the Room integration on and was wondering if there was any progress on this issue first.

**Comment by romtsn** [comment]
we're taking a look into this tomorrow :)

**Comment by stefanosiano** [comment]
hey @ninniuz 
we released the 4.2.0 version of our plugin that should fix this issue.
Please, let us know if anything doesn't work as expected
