### ISSUE TITLE
getMappingFile is obsolete

### ISSUE THREAD

**Issue by mike-burns** [getsentry/sentry-android-gradle-plugin#6]
A Gradle upgrade (5.6.4) gave me a new warning:

> WARNING: API 'variant.getMappingFile()' is obsolete and has been replaced with 'variant.getMappingFileProvider()'.
> It will be removed at the end of 2019.                                                                                                   
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance. 

I ran gradle with `-Pandroid.debug.obsoleteApi=true` and it indicates that [it's coming from Sentry](https://github.com/getsentry/sentry-java/blob/v1.7.31_gradle_plugin/sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy#L236).

So, just making sure this is on your radar.

**Comment by marandaneto** [comment]
hey @mike-burns thanks for raising this issue.
Which AGP version are you working with? thanks.

**Comment by marandaneto** [comment]
@mike-burns AGP has introduced the new mapping provider, I'll release it on the next version :) thanks.

**Comment by mike-burns** [comment]
That was fast. Thank you!

**Comment by marandaneto** [comment]
@mike-burns hey, I'm not in hurry to deploy this because it's just a warning, it still works normally, maybe I get some time to do it next week :) stay tuned.

**Comment by marandaneto** [comment]
@mike-burns @MBratkowski @dzwicker @y0sh33 done :)
https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/v1.7.32
