### ISSUE TITLE
Support DexGuard

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android-gradle-plugin#60]
The Sentry Gradle Plugin currently supports ProGuard and R8 but fails to find DexGuard Gradle's tasks.

The tasks have a different prefix name, we'd need to look up for them too as we do for ProGuard and R8

See: https://github.com/getsentry/sentry-android-gradle-plugin/blob/master/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy#L139-L142

https://www.guardsquare.com/en/products/proguard/manual/gradleplugin

**Comment by marandaneto** [comment]
@cortinico do you have any experience with DexGuard?
we probably just need to find out its task names and add here https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryTasksProvider.kt#L16-L28
everything else should work ootb.

**Comment by cortinico** [comment]
> @cortinico do you have any experience with DexGuard?

Sadly not, but I see two ways to approach this:
* Find the task by name. Easier but a bit error prone
* Depend on the DexGuard Gradle plugin as `compileOnly` an get the `TaskProvider` instance from them

**Comment by marandaneto** [comment]
> > @cortinico do you have any experience with DexGuard?
> 
> Sadly not, but I see two ways to approach this:
> 
> * Find the task by name. Easier but a bit error prone
> * Depend on the DexGuard Gradle plugin as `compileOnly` an get the `TaskProvider` instance from them

the 2nd is the ideal one, if possible, we only use the `minify` tasks by name because they don't have a `TaskProvider` or not accessible at least for Plugin developers iirc

**Comment by cortinico** [comment]
Just a heads up, I started working on this one. The implementation is not yet completed but I hope to be able to share a PR in 1/2 weeks 👍

**Comment by romtsn** [comment]
@cortinico thanks a bunch, do you have access to dexguard to test it out though?

**Comment by cortinico** [comment]
> @cortinico thanks a bunch, do you have access to dexguard to test it out though?

Nope, I've been testing with the standalone Proguard setup suggested here https://www.guardsquare.com/manual/setup/gradleplugin

**Comment by romtsn** [comment]
@cortinico we've been in the talks with guardsquare and I think I can get you a developer license for dexguard - I will contact them today.

Also, I think we should probably just follow the current setup with finding a task by name, wdyt?

Last note, you could also take a look at how bugsnag does it, I think it has some good clues:
https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/3f08a0804366e2169b84abe15acbeff30f53e503/src/main/kotlin/com/bugsnag/android/gradle/internal/DexguardCompat.kt
https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/3f08a0804366e2169b84abe15acbeff30f53e503/src/main/groovy/com/bugsnag/android/gradle/GroovyCompat.groovy
