### ISSUE TITLE
findSentryVersion not detecting applied sdk version

### ISSUE THREAD

**Issue by G00fY2** [getsentry/sentry-android-gradle-plugin#603]
### Gradle Version

8.5.0

### AGP Version

8.1.4

### Code Minifier/Optimizer

None

### Version

3.14.0

### Sentry SDK Version

7.0.0

### Steps to Reproduce

1. Define io.sentry:sentry-android dependency in app module using bom (io.sentry:sentry-bom + io.sentry:sentry-android)
2. Apply io.sentry.android.gradle plugin to the app module
3. Set gradle log level to INFO
4. Sync project

### Expected Result

The sentry gradle plugin should detect the sentry sdk version (e.g. 7.0.0 in our case), since it is added as a dependency.

### Actual Result

We see the following gradle log while syncing:
> [sentry] sentry-android was successfully installed with version: 6.32.0

So looks like the [findSentryVersion](https://github.com/getsentry/sentry-android-gradle-plugin/blob/863441913866e48d69147b082fae32191cb4cf6d/plugin-build/src/main/kotlin/io/sentry/android/gradle/autoinstall/AutoInstall.kt#L67) in the sentry gradle plugin does not find the sentry sdk version from the dependencies and falls back to the default version.

**Comment by romtsn** [comment]
yeah, we don't consider bom version at the moment, that'd be a good enhancement, thanks for reporting 👍

**Comment by G00fY2** [comment]
> yeah, we don't consider bom version at the moment, that'd be a good enhancement, thanks for reporting 👍

I see. Would still say thats more like a potentially critical issue than an improvement. Also the docs don't mention anything about this limitation. The release notes for [4.1.0](https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/4.1.0) also just say 

> If you have directly defined one of the core versions, we will use that to install integrations
which is actually not true if using the BOM.
