### ISSUE TITLE
okhttp crumbs missing

### ISSUE THREAD

**Issue by mrzbn** [getsentry/sentry-android-gradle-plugin#606]
### Gradle Version

7.3.3

### AGP Version

7.2.2

### Code Minifier/Optimizer

None

### Version

4.0.0

### Sentry SDK Version

7.0.0

### Steps to Reproduce

1. add dependency and plugin
2. throw an Exception
3. okhttp crumbs missing

### Expected Result

display okhttp crumbs

### Actual Result

---

**Comment by markushi** [comment]
Hey @mrzbn, thanks for reaching out!
Could describe your setup a bit more? Are you performing OkHttp requests within your app module or do you have an extra module for that?

As an intermediate step you can try to manually setup your `OkHttpClient` with our sentry integrations. 

Here's an example:
```kotlin
 val client = OkHttpClient.Builder()
      .eventListener(SentryOkHttpEventListener())
      .addInterceptor(SentryOkHttpInterceptor())
      .build()
```

**Comment by mrzbn** [comment]
@markushi I have multiple modules that initiate OkHttp. I tried to manually add the SentryOkHttpEventListener and SentryOkHttpInterceptor to all of OkHttp builders, but still no http breadcrumbs are showing.

**Comment by mrzbn** [comment]
I see two versions of okhttp in my "external libraries". v4.5.0 and v4.9.3.

**Comment by litrik** [comment]
I have the same issue. All my OkHttp calls are from inside the main `app` module.
 - Sentry 7.0.0
 - Sentry plugin 4.0.0
 - OkHttp 4.12

Manually adding `.addInterceptor(SentryOkHttpInterceptor())` does not solve the issue

**Comment by romtsn** [comment]
hey, could you please provide a reproducible sample? I've just tried it on our [sample app](https://github.com/getsentry/sentry-android-gradle-plugin/blob/994a5debe1e153351aa73009709e6fc2e9807693/examples/android-instrumentation-sample/src/main/java/io/sentry/samples/instrumentation/network/TrackService.kt#L15-L22), and it works just fine, without the need to manually declare interceptor or event listener, with the version 4.9.3 of okhttp:
![image](https://github.com/getsentry/sentry-android-gradle-plugin/assets/4999776/65b81a27-c522-4daf-9bba-c8435e5c7481)
![image](https://github.com/getsentry/sentry-android-gradle-plugin/assets/4999776/aaa68bb0-acfd-4097-9d8c-60392d1a4227)

Also, could you share the version of sentry-okhttp-android that you use? You can find it out via `./gradlew app:dependencies`

**Comment by romtsn** [comment]
Ok, I think I know what's going on. @stefanosiano it looks like we should actually add a breadcrumb before finishing the `callRootSpan` here, because if it's null, we'll return early, but we should add breadcrumbs regardless of the span state:
https://github.com/getsentry/sentry-java/blob/1f3652d529c2bd977c6e04f64b9cdb50d19a0358/sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpEvent.kt#L142

**Comment by stefanosiano** [comment]
> Ok, I think I know what's going on. @stefanosiano it looks like we should actually add a breadcrumb before finishing the `callRootSpan` here, because if it's null, we'll return early, but we should add breadcrumbs regardless of the span state: https://github.com/getsentry/sentry-java/blob/1f3652d529c2bd977c6e04f64b9cdb50d19a0358/sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpEvent.kt#L142

yes, we currently don't send the breadcrumb if no span is created

**Comment by mrzbn** [comment]
@stefanosiano how can I create a span?

**Comment by stefanosiano** [comment]
@mrzbn spans are created automatically, as long as perfomance monitoring is enabled (the `tracesSampleRate` option is set) and a transaction is running
so, if there is no transaction running, the SDK doesn't start a span, and that null check returns before sending the breadcrumb. We have to fix this in the SDK, but should be quick
