### ISSUE TITLE
Debug Meta Properties File Generation Breaks Build Caching

### ISSUE THREAD

**Issue by gilday** [getsentry/sentry-android-gradle-plugin#616]
### Gradle Version

8.5.0

### AGP Version

0

### Code Minifier/Optimizer

None

### Version

4.1.0

### Sentry SDK Version

7.1.0

### Steps to Reproduce

Can reproduce with a simple Gradle Java project (Android not relevant) that has one Java source file.

1. execute `./gradlew classes`
2. execute `./gradlew classes` repeatedly, and note that the task is always "up to date", because no source files have changed.

```
BUILD SUCCESSFUL in 383ms
1 actionable task: 1 up-to-date
```

3. introduce Sentry plugin and configure it to include source context

```kotlin
plugins {
    id("java")
    id("io.sentry.jvm.gradle") version "4.1.0"
}

group = "org.example"

sentry {
    includeSourceContext = true
}

repositories {
    mavenCentral()
}
```

4. execute `./gradlew classes` repeatedly, and note that Sentry tasks are run repeatedly, despite not having changed any of their inputs.

```
BUILD SUCCESSFUL in 1s
5 actionable tasks: 3 executed, 2 up-to-date
```

### Expected Result

The meta properties file should not be regenerated if none of its inputs have changed. Regenerating this file causes other Gradle tasks (such as the `application` plugin's `distTar` task or a Docker image building task) to re-run needlessly thus negatively impacting build times.

### Actual Result

Sentry tasks that generate the meta properties file explicitly disable Gradle's build caching (see [SentryGenerateDebugMetaPropertiesTask](https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryGenerateDebugMetaPropertiesTask.kt#L21)).

**Comment by adinauer** [comment]
Thanks for the report. I guess we'll have to find a good way to check if a new UUID should be generated because even with removing the `outputs.upToDateWhen { false }` from `SentryGenerateDebugMetaPropertiesTask` the build cache would still be disabled by tasks generating UUIDs (and `GenerateBundleIdTask`, `SentryGenerateProguardUuidTask`).

@romtsn iirc you already had a plan on how to deal with this, is that correct?

**Comment by romtsn** [comment]
Yep, it's related to #285 (or actually, maybe it's even a duplicate and we could close this one?). I will take a look at this this or next week, I have had a branch with explorations somewhere. Most likely we'd have to use checksums of a proguard mapping file or classpath (for source context) instead of a random UUID

**Comment by adinauer** [comment]
While this is closely related to #285 I'd say we can keep this open since it's not entirely the same thing and we could fix the ProGuard issue while still leaving the other parts unresolved. This seems more generic.

**Comment by gilday** [comment]
> Most likely we'd have to use checksums of a proguard mapping file or classpath (for source context) instead of a random UUID

But what about projects that do not use Proguard? My use case is a backend Java projects, not an Android plugin. Like most backend Java projects, this project does not use Proguard.

I think you can use a UUID, so long as the check for "does a new UUID need to be generated" works. Presently, this task is effectively disabling Gradle's up-to-date check. Instead, I would think that this task should declare its inputs to be the source files that are packaged in the bundle. Maybe the same `ConfigurableFileCollection` input that the `CollectSourcesTask` uses. In that case, Gradle will only run the generate ID task when some source file has changed and therefore a new bundle needs to be created.

**Comment by adinauer** [comment]
The current behaviour is also causing issues with dev tools that auto deploy on changes, see #628
