### ISSUE TITLE
Sentry-gradle + Skaffold causes infinite restarts with Spring Boot

### ISSUE THREAD

**Issue by jasonab** [getsentry/sentry-android-gradle-plugin#628]
### Gradle Version

8.5

### AGP Version

Kotlin 1.9.22

### Code Minifier/Optimizer

None

### Version

4.1.1

### Sentry SDK Version

Spring Boot 7.1.0

### Steps to Reproduce

Kotlin + Spring Boot + Gradle

Adding the Sentry Gradle plugin, then running my local dev environment with Skaffold sync, causes Skaffold to infinitely loop its sync. Spring barely finishes starting up before it is killed and auto-restarted because of changes in disk caused by the Gradle plugin. Using Sentry Spring Boot Starter lib directly does not exhibit this behavior.

### Expected Result

Spring starts up correctly and continues running

### Actual Result

Spring is constantly restarted by Skaffold because of file changes on disk

**Comment by stefanosiano** [comment]
@adinauer Can you have a look into it?

**Comment by adinauer** [comment]
@jasonab I've never used skaffold, can you please provide a minimum reproducible sample?

**Comment by jasonab** [comment]
My honest answer is, "no, I can't" because it would require providing not only a code sample, but a k8s cluster definition and a skaffold config to sync the code.

I know that the file change is in the `resources` directory, but I can't tell what file is being written or changed to cause the sync.

**Comment by romtsn** [comment]
🤔 could you try disable dependencies report? 

```
sentry {
  includeDependenciesReport = false // or .set(false) for .kts
}
```
another culprit could be telemetry:
```
sentry {
  telemetry = false // or .set(false) for .kts
}
```

**Comment by jasonab** [comment]
I will explore those options, thank you

**Comment by jasonab** [comment]
@romtsn I tried using those flags, both separately and together, but did not see any change - skaffold still sees constant file changes to be synced. It appears that every single file in my `/resources` directory is being touched, somehow. There are no actual changes happening, but Skaffold sees them as being modified.

**Comment by adinauer** [comment]
@jasonab have you enabled source context in the gradle plugin? If so, can you please try disabling it.

```
sentry {
  includeSourceContext = false // or .set(false) for .kts
}
```

Might also be `sentry-debug-meta.properties` that changes. If so this issue would be linked to #616

@romtsn is there a way to disable `SentryGenerateDebugMetaPropertiesTask` without us changing the code?

@jasonab is there a way to run gradle with debug logging to see what sentry tasks execute before a restart?

**Comment by adinauer** [comment]
> It appears that every single file in my /resources directory is being touched

Ah I missed the "every" when first reading. Hmm I wouldn't know how we cause this. Maybe @romtsn has some ideas.

**Comment by jasonab** [comment]
I tried setting `includeSourceContext` explicity to `false`, but that had no effect.

Here are the Gradle tasks that run to generate the jar:

> Task :_skaffoldFailIfJibOutOfDate
> Task :bootBuildInfo
> Task :checkKotlinGradlePluginConfigurationErrors
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :generateGitProperties UP-TO-DATE
> Task :collectExternalDependenciesForSentry UP-TO-DATE
> Task :generateSentryBundleIdJava SKIPPED
> Task :generateSentryDebugMetaPropertiesjava
> Task :processResources
> Task :classes

> Task :jib

After looking at the Skaffold logs in debug mode, I believe that it is the `sentry-debug-meta.properties` that is changing. If I do a `watch` on that file, I see the timestamp increment regularly while the dev loop is running. I can only assume that the file is updated late in the Gradle build cycle, causing Skaffold to believe that it has changed, and forcing the infinite loop.

I'm not sure why this causes Skaffold to sync the entire `resources` directory (which it clearly is), but certainly no other files are changing on my local machine.

**Comment by adinauer** [comment]
@jasonab thanks for checking.

```Task :generateSentryDebugMetaPropertiesjava```

Yeah this also indicates `sentry-debug-meta.properties`. We'll look into it.

**Comment by romtsn** [comment]
@jasonab I think you can work it around for now as follows:
```
import io.sentry.android.gradle.tasks.SentryGenerateDebugMetaPropertiesTask

// or maybe some env variable indicating that Skaffold is running
if (gradle.startParameter.taskNames.any { it.contains("jib" }) {
  tasks.withType<SentryGenerateDebugMetaPropertiesTask>() {
    enabled = false
  }
}
```
