### ISSUE TITLE
Upload source context also for `assemble${variantName}` tasks

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-android-gradle-plugin#635]
### Description

Currently, the source context is only uploaded for `bundle${variantName}` tasks.

I think it would make sense to also upload the source context for the assemble task as they are used a lot for testing the app release locally. The Android crashes miss the source context for those test releases at the moment.

**Comment by romtsn** [comment]
We actually already hook into assemble tasks [here](https://github.com/getsentry/sentry-android-gradle-plugin/blob/be07360434deba32874ac282f2b559dd25154c7b/plugin-build/src/main/kotlin/io/sentry/android/gradle/util/tasks.kt#L87-L89), but only for the `release` build type - did you perhaps test it with `assembleDebug` ?

**Comment by krystofwoldrich** [comment]
@romtsn I tried `assembleRelease` and `bundleRelease` tasks. I only see a hook to `assemble` task, I don't know if it exists in plain Android apps, bun in RN only `assemble${variantName}` exists.

https://github.com/getsentry/sentry-android-gradle-plugin/blob/1af7131a6a5b86256ba0968066121a7d91447369/plugin-build/common/src/main/kotlin/io/sentry/gradle/common/JavaVariant.kt#L24

**Comment by romtsn** [comment]
It's here https://github.com/getsentry/sentry-android-gradle-plugin/blob/1af7131a6a5b86256ba0968066121a7d91447369/plugin-build/src/agp74/kotlin/io/sentry/android/gradle/AGP74Compat.kt#L39-L40. Which version of AGP you were testing on?

**Comment by krystofwoldrich** [comment]
Android Gradle plugin 8.1.1 and SAGP 3.11.1 and 4.2.0 both have the same result.

**Comment by romtsn** [comment]
Closed by #639
