### ISSUE TITLE
sentry-cli path never considered up-to-date

### ISSUE THREAD

**Issue by lbloder** [getsentry/sentry-android-gradle-plugin#651]
### Description

Follow-Up on: https://github.com/getsentry/sentry-android-gradle-plugin/pull/634

Currently, tasks that depend on  the `sentry-cli` are never considered `up-to-date` and thus will be executed at every run, if the `sentry-cli` path is generated by extracting the packaged `sentry-cli` executable from the `jar` and placing it into a temp folder. This causes the `sentry-cli` path to change at every run and marks all dependent tasks `out-of-date`.

Affected tasks:
- `UploadSourceBundleTask`
- `BundleSourcesTask`
- `SentryUploadProguardMappingsTask`

**Comment by romtsn** [comment]
@lbloder just one note - if the build is run with `--configuration-cache` then the sentry-cli path is preserved as part of the config cache between builds, so maybe that's alright as it is now?

**Comment by adinauer** [comment]
Should we document this somewhere?

**Comment by romtsn** [comment]
yeah we could, but also - it's always been like that :P

**Comment by lbloder** [comment]
@markushi depends on whether we actually want to implement this. But not immediately, because I'm out of office for the next two weeks.

I guess if it works with `--configuration-cache` we should be fine. 

What do you all think?

**Comment by romtsn** [comment]
I think it's alright, we could mention configuration cache somewhere in the docs perhaps, and if this issue doesn't get any traction from the community in a while, we just close it.

**Comment by kahest** [comment]
Let's make sure we verify that any solution to this issue also fixes https://github.com/getsentry/sentry-android-gradle-plugin/issues/670#issuecomment-1994601135

**Comment by kozaxinan** [comment]
> @markushi depends on whether we actually want to implement this. But not immediately, because I'm out of office for the next two weeks.
> 
> I guess if it works with `--configuration-cache` we should be fine.
> 
> What do you all think?

Not that wouldnt be fine.
1. Not every one uses configuration cache
2. After gradle 8.6, sharing configuration cache on CI becomes much simpler. We started sharing CC cache and now Sentry invalidates CC on every run.
3.

**Comment by PhilGlass** [comment]
@kozaxinan see #670.

Our workaround for now is to install the Sentry CLI to a known location in our Docker image and set `cli.executable=/opt/bin/sentry-cli` in `sentry.properties`.

**Comment by kozaxinan** [comment]
I tried disabling telemetry and now it is working.
tbh, we use self hosted sentry. Telemetry should be disabled already. I will keep eye on it. If this works, we will be able to save around 5-6 minutes on CI.

**Comment by romtsn** [comment]
@kozaxinan which version of the plugin you're using btw?

**Comment by romtsn** [comment]
@PhilGlass @kozaxinan version 4.4.0 has been shipped with both fixes (dexguard and sentry-cli config cache), please give it a try and let us know if you still face any issues. Thanks for your patience!

**Comment by kozaxinan** [comment]
According to initial tests, the new version fixed the cc issue. Thank you.
