### ISSUE TITLE
`generateSentryDebugMetaProperties` cache busts by adding a timestamp to the `sentry-meta-debug.properties`

### ISSUE THREAD

**Issue by danielamsel-toast** [getsentry/sentry-android-gradle-plugin#653]
### Gradle Version

8.5.0

### AGP Version

8.2.2

### Code Minifier/Optimizer

None

### Version

4.2.0

### Sentry SDK Version

7.1.0

### Steps to Reproduce

1. Assemble android app with sentry android gradle plugin + build cache enabled
2. Assemble again, noticing that the assemble step does not cache

### Expected Result

Assembling the application a second time results in a cache hit

### Actual Result

Assembling the application, and open the `sentry-debug-meta.properties` file in the generated assets and observe that a timestamp is commented in the second line of the file like the following
```
#Generated by sentry-android-gradle-plugin
#Fri Feb 09 12:09:39 MST 2024
io.sentry.build-tool=gradle
```

This appears to be from using `java.util.Properties` [props.store](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#store-java.io.Writer-java.lang.String-) inside the [task action](https://github.com/getsentry/sentry-android-gradle-plugin/blob/ef9e3598a3ac9396be4b96383fc8ba3e64e8efff/plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryGenerateDebugMetaPropertiesTask.kt#L42).

**Comment by romtsn** [comment]
hi @danielamsel-toast we've just release version `4.3.0` - could you give it a try? It should improve the task so it's not running if the sources or mapping file have not changed, and should be at least `UP-TO-DATE`. Thanks

**Comment by romtsn** [comment]
Right, it still invalidates the cache, we'll provide a fix!

**Comment by markushi** [comment]
Let's provide a custom implementation which does not print timestamps into the `.properties` file.

**Comment by romtsn** [comment]
@danielamsel-toast version 4.3.1 is out, please give it a try and let us know if that works, thanks! https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/4.3.1

**Comment by danielamsel-toast** [comment]
Works great! Thank you so much Sentry team!
