### ISSUE TITLE
Upgrading to 4.3.0 adds multiple test dependencies to root project class path.

### ISSUE THREAD

**Issue by devPalacio** [getsentry/sentry-android-gradle-plugin#656]
### Gradle Version

8.5

### AGP Version

8.2.1

### Code Minifier/Optimizer

None

### Version

4.3.0

### Sentry SDK Version

7.3.0

### Steps to Reproduce

Using tool of choice, compare the class path of the root project with Sentry Gradle Plugin 4.2.0 and 4.3.0. I noticed this issue with https://github.com/dropbox/dependency-guard

### Expected Result

Classpath stays mostly stable, besides dependency upgrades.

### Actual Result

These additional dependencies were added with the upgrade to 4.3.0
```
org.codehaus.groovy:groovy-all:3.0.13
org.codehaus.groovy:groovy-ant:3.0.13
org.codehaus.groovy:groovy-astbuilder:3.0.13
org.codehaus.groovy:groovy-cli-picocli:3.0.13
org.codehaus.groovy:groovy-console:3.0.13
org.codehaus.groovy:groovy-datetime:3.0.13
org.codehaus.groovy:groovy-docgenerator:3.0.13
org.codehaus.groovy:groovy-groovydoc:3.0.13
org.codehaus.groovy:groovy-groovysh:3.0.13
org.codehaus.groovy:groovy-jmx:3.0.13
org.codehaus.groovy:groovy-json:3.0.13
org.codehaus.groovy:groovy-jsr223:3.0.13
org.codehaus.groovy:groovy-macro:3.0.13
org.codehaus.groovy:groovy-nio:3.0.13
org.codehaus.groovy:groovy-servlet:3.0.13
org.codehaus.groovy:groovy-sql:3.0.13
org.codehaus.groovy:groovy-swing:3.0.13
org.codehaus.groovy:groovy-templates:3.0.13
org.codehaus.groovy:groovy-test-junit5:3.0.13
org.codehaus.groovy:groovy-test:3.0.13
org.codehaus.groovy:groovy-testng:3.0.13
org.codehaus.groovy:groovy-xml:3.0.13
org.codehaus.groovy:groovy:3.0.13
org.junit.jupiter:junit-jupiter-api:5.8.2
org.junit.jupiter:junit-jupiter-engine:5.8.2
org.junit.platform:junit-platform-commons:1.8.2
org.junit.platform:junit-platform-engine:1.8.2
org.junit.platform:junit-platform-launcher:1.8.2
org.junit:junit-bom:5.8.2
org.opentest4j:opentest4j:1.2.0
org.testng:testng:7.5
org.webjars:jquery:3.5.1
```

Are these dependencies required to be on the class path now?

**Comment by romtsn** [comment]
hi @devPalacio do you mean the _build_ classpath (plugins) or the _app_ classpath? I don't see us adding any new dependencies to the app classpath, but yes, we now explicitly depend on `asm` and `asm-commons` in the plugin but that should be the case for you already anyway if you apply AGP. I'm not sure if asm depends on any of the deps you mentioned tbh.

**Comment by devPalacio** [comment]
Hey there, I'm referencing the `build` classpath. Does the addition of ASM transitively bring in junit and the other test dependencies as well?

**Comment by romtsn** [comment]
> Hey there, I'm referencing the `build` classpath. Does the addition of ASM transitively bring in junit and the other test dependencies as well? Based on their POMs they should be rather slim dependencies.

Yeah, that's what I'm looking at as well, but it doesn't seem like they are the culprit here. You can see that we are not declaring any other dependencies (except io.sentry:sentry, which also has no dependencies): https://github.com/getsentry/sentry-android-gradle-plugin/blob/1f738d8ac768f61ab6be57901a9d3914940989a5/plugin-build/build.gradle.kts#L65-L66

Btw, you shouldn't apply our gradle plugin to the root project in theory, it has no effect there, only where `com.android.application` is applied.

**Comment by markushi** [comment]
Could be related to the groovy version bump we did recently: https://github.com/getsentry/sentry-android-gradle-plugin/commit/726d0d243ebf77e4aced395a2c3c3960032eab23#diff-75b31066e97e27961c3c9e9668c539a133d73c10398dc76552df3f0119810ac0

**Comment by devPalacio** [comment]
> > Hey there, I'm referencing the `build` classpath. Does the addition of ASM transitively bring in junit and the other test dependencies as well? Based on their POMs they should be rather slim dependencies.
> 
> Yeah, that's what I'm looking at as well, but it doesn't seem like they are the culprit here. You can see that we are not declaring any other dependencies (except io.sentry:sentry, which also has no dependencies):
> 
> https://github.com/getsentry/sentry-android-gradle-plugin/blob/1f738d8ac768f61ab6be57901a9d3914940989a5/plugin-build/build.gradle.kts#L65-L66
> 
> Btw, you shouldn't apply our gradle plugin to the root project in theory, it has no effect there, only where `com.android.application` is applied.

I'm just loading it onto the build classpath with `apply false`. 

If I get a chance to dig in a little deeper I'll try to bisect where these test dependencies got added on a sample project. The only change I made when all these dependencies were added to the build class path was the sentry and sentry gradle plugin version bump.

**Comment by romtsn** [comment]
> Could be related to the groovy version bump we did recently: [726d0d2#diff-75b31066e97e27961c3c9e9668c539a133d73c10398dc76552df3f0119810ac0](https://github.com/getsentry/sentry-android-gradle-plugin/commit/726d0d243ebf77e4aced395a2c3c3960032eab23#diff-75b31066e97e27961c3c9e9668c539a133d73c10398dc76552df3f0119810ac0)

this is it I think, this plugin probably adds some deps to the build classpath under-the-hood. I will dig into that soon

**Comment by devPalacio** [comment]
Seeing the following dependencies added bumping from 4.2.0 to 4.3.1
```
com.beust:jcommander:1.78
com.thoughtworks.qdox:qdox:1.12.1
dev.gradleplugins:gradle-api:7.6
info.picocli:picocli:4.6.3
io.sentry.android.gradle:io.sentry.android.gradle.gradle.plugin:4.3.1
io.sentry:sentry-android-gradle-plugin:4.3.1
jline:jline:2.14.6
org.apache.ant:ant-antlr:1.10.12
org.codehaus.groovy:groovy-all:3.0.13
org.codehaus.groovy:groovy-ant:3.0.13
org.codehaus.groovy:groovy-astbuilder:3.0.13
org.codehaus.groovy:groovy-cli-picocli:3.0.13
org.codehaus.groovy:groovy-console:3.0.13
org.codehaus.groovy:groovy-datetime:3.0.13
org.codehaus.groovy:groovy-docgenerator:3.0.13
org.codehaus.groovy:groovy-groovydoc:3.0.13
org.codehaus.groovy:groovy-groovysh:3.0.13
org.codehaus.groovy:groovy-jmx:3.0.13
org.codehaus.groovy:groovy-json:3.0.13
org.codehaus.groovy:groovy-jsr223:3.0.13
org.codehaus.groovy:groovy-macro:3.0.13
org.codehaus.groovy:groovy-nio:3.0.13
org.codehaus.groovy:groovy-servlet:3.0.13
org.codehaus.groovy:groovy-sql:3.0.13
org.codehaus.groovy:groovy-swing:3.0.13
org.codehaus.groovy:groovy-templates:3.0.13
org.codehaus.groovy:groovy-test-junit5:3.0.13
org.codehaus.groovy:groovy-test:3.0.13
org.codehaus.groovy:groovy-testng:3.0.13
org.codehaus.groovy:groovy-xml:3.0.13
org.codehaus.groovy:groovy:3.0.13
org.junit.jupiter:junit-jupiter-api:5.8.2
org.junit.jupiter:junit-jupiter-engine:5.8.2
org.junit.platform:junit-platform-commons:1.8.2
org.junit.platform:junit-platform-engine:1.8.2
org.junit.platform:junit-platform-launcher:1.8.2
org.junit:junit-bom:5.8.2
org.opentest4j:opentest4j:1.2.0
org.testng:testng:7.5
org.webjars:jquery:3.5.1
```

I'm not confident that this has been resolved

**Comment by romtsn** [comment]
You're right, I'm not sure why the gradle scan didn't not show it when I published it locally, must've been some caching issue or something. I'm gonna re-open and look into this again

**Comment by devPalacio** [comment]
Thanks for the continued investigation into this, looking forward to the release!

**Comment by romtsn** [comment]
@devPalacio this has been shipped, let us know if it's still a problem and apologies for the back-and-forths. Thanks!

**Comment by devPalacio** [comment]
Issue is resolved, thank you!
