### ISSUE TITLE
Support K2 compiler

### ISSUE THREAD

**Issue by devPalacio** [getsentry/sentry-android-gradle-plugin#698]
### Problem Statement

[K2 Compiler](https://kotlinlang.org/docs/k2-compiler-guide.html) will be stable with the Kotlin 2.0 release, making an issue to track when `io.sentry.SentryKotlinCompilerPlugin` is compatible with K2.

**Comment by kahest** [comment]
Thanks for creating the issue 🙏

**Comment by jamesarich** [comment]
Kotlin 2.0.0 compiler merge to kotlin repo announced here: https://twitter.com/kotlin/status/1785238489635684525
more info on migration here: https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compiler.html

**Comment by kahest** [comment]
Quick update - this is [in progress](https://github.com/getsentry/sentry-android-gradle-plugin/pull/716)

**Comment by markushi** [comment]
Another quick update: You can expect a `4.7.0` release today which adds support for K2!

**Comment by kahest** [comment]
Release is out: [4.7.0](https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/4.7.0)

**Comment by dev-gvs** [comment]
I tried the new version and got the following error:

```
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/ir/expressions/IrStatementOrigin$DEFAULT_VALUE
	at io.sentry.compose.JetpackComposeTracingIrExtension$generate$transformer$1.wrapExpression(JetpackComposeTracingIrExtension.kt:179)
	at io.sentry.compose.JetpackComposeTracingIrExtension$generate$transformer$1.visitCall(JetpackComposeTracingIrExtension.kt:157)
```

**Comment by markushi** [comment]
@dev-gvs Which version of Kotlin are you using for your project? The mentioned missing class still exists in [2.0.0](https://github.com/JetBrains/kotlin/blob/2.0.0/compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/IrStatementOrigin.kt#L97), and we've verified functionality across a few different versions (1.8.x, 1.9.x as well as 2.0.0).

**Comment by LukStankovic** [comment]
> > I tried the new version and got the following error:
> > ```
> > java.lang.NoClassDefFoundError: org/jetbrains/kotlin/ir/expressions/IrStatementOrigin$DEFAULT_VALUE
> > 	at io.sentry.compose.JetpackComposeTracingIrExtension$generate$transformer$1.wrapExpression(JetpackComposeTracingIrExtension.kt:179)
> > 	at io.sentry.compose.JetpackComposeTracingIrExtension$generate$transformer$1.visitCall(JetpackComposeTracingIrExtension.kt:157)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Full stacktrace
> 
> same here - kotlin 2.0 and sentry plugin 4.7.0:
> 
> ```
> java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.ir.expressions.impl.IrGetObjectValueImpl.<init>(int, int, org.jetbrains.kotlin.ir.types.IrType, org.jetbrains.kotlin.ir.symbols.IrClassSymbol)'
> 	at io.sentry.compose.JetpackComposeTracingIrExtension$generate$transformer$1.wrapExpression(JetpackComposeTracingIrExtension.kt:234)
> 	at io.sentry.compose.JetpackComposeTracingIrExtension$generate$transformer$1.visitCall(JetpackComposeTracingIrExtension.kt:157)```
> ```

Same here, kotlin 2.0, sentry plugin 4.7.0 😢

**Comment by kahest** [comment]
Thanks for the quick tests and reports - I reopened this issue, we'll prio this

**Comment by markushi** [comment]
Quick update: `4.7.1` is out (it may take a few more minutes until it's available via maven), please give it a try and let us know if the issues mentioned above are now fixed.

**Comment by jamesarich** [comment]
Worked for me @markushi - compiled without error

**Comment by LukStankovic** [comment]
Working for me as well 🎉  Thanks ❤️

**Comment by kahest** [comment]
Thanks everybody for testing and reporting back, that's really helpful and appreciated ❤️
