### ISSUE TITLE
Mapping upload via sentry-cli not working (Found 0 debug information files)

### ISSUE THREAD

**Issue by tobi512** [getsentry/sentry-android-gradle-plugin#699]
### Gradle Version

8.5

### AGP Version

8.1.1

### Code Minifier/Optimizer

R8

### Version

4.x

### Sentry SDK Version

7.x (transitive via sentry-react-native)

### Steps to Reproduce

Hey guys, 
we had a failed upload in one of our release builds and now tried to upload the source files manually via sentry-cli to see proper de-obfuscated crashes but the upload fails with the following log:

```
sentry-cli debug-files upload -o <our-org> -p <our-project> mapping/

> Found 0 debug information files
> No debug information files found
```

The folder "mapping" contains the mapping file for the correct build (downloaded from our CI) and it looks identical to other mapping files that we already uploaded successfully. Could you please tell us what we're missing here?

It seems like the mapping file is somehow checked by sentry-cli and it does not pass any checks, but we don't know what exactly happens internally...

PS: Not sure if this repo is the best fit for the issue but didn't find a better place so feel free to move it or tell us where to place it.

Thanks & cheers, 
Tobias

### Expected Result

Mapping files is uploaded successfully and we see de-obfuscated crashes.

### Actual Result

Upload fails and no mapping files is uploaded. Log:

```
> Found 0 debug information files
> No debug information files found
```

**Comment by romtsn** [comment]
hey, the command for uploading proguard mappings is slightly different:
```bash
sentry-cli upload-proguard --uuid  "<random_uuid_that_has_to_be_passed_to_the_sdk_at_runtime>" -o <org> -p <project> path/to/mapping.txt
```

you have to provide relative file path (not a folder, but the actual mapping file) as well as a UUID that you should pass to the SDK at runtime (e.g. via `options.proguardUuid` or `io.sentry.proguard-uuid` in the manifest). You can read up more on this here: https://docs.sentry.io/platforms/android/enhance-errors/proguard/

Let me know if there are further questions!

**Comment by tobi512** [comment]
Thanks for the quick reply!

Works with your approach, the upload was successful, closing... 👍
