### ISSUE TITLE
Sentry Gradle Plugin not compatible with Gradle 7.0

### ISSUE THREAD

**Issue by JvmName** [getsentry/sentry-android-gradle-plugin#70]
_Gradle:_
7.0

---
I have the following issue:

Gradle throws an error because `SentryProguardConfigTask` is not properly annotated: 

```
:app:addSentryProguardSettingsForRelease FAILED	
FAILURE: Build failed with an exception.	
* What went wrong:	
A problem was found with the configuration of task ':app:addSentryProguardSettingsForRelease' (type 'SentryProguardConfigTask').	
  - Type 'SentryProguardConfigTask' property 'applicationVariant' is missing an input or output annotation.	
    Reason: A property without annotation isn't considered during up-to-date checking.	
    Possible solutions:	
      1. Add an input or output annotation.	
      2. Mark it as @Internal.	
    Please refer to https://docs.gradle.org/7.0-rc-2/userguide/validation_problems.html#missing_annotation for more details about this problem.	
```
There might be other tasks that also require annotation, I didn't check. 

**Steps to reproduce:**
just run a release build (`gw :app:assembleRelease`) using Gradle 7.0

**Actual result:**
failure

**Expected result:**
success

**Comment by marandaneto** [comment]
@JvmName thanks for reporting.

you can disable the proguard task actually, See https://docs.sentry.io/platforms/android/proguard/#gradle-configuration

this is likely going to be fixed by https://github.com/getsentry/sentry-android-gradle-plugin/pull/50 too

**Comment by JvmName** [comment]
Oh cool, I'll check that out! 

Since Gradle 7.0 is in GA, might I suggest profiling against [the problems Gradle will complain](https://docs.gradle.org/7.0/userguide/validation_problems.html) about preemptively.

**Comment by pvegh** [comment]
Disabling it means no deobfuscation, right? 
Also V2 will probably take a while to release.

Can we have a hotfix please, so that we can use gradle 7 today?

**Comment by looploooop** [comment]
@pvegh 
Deobfuscation is still working fine for me with Gradle 7.0 and the disabled proguard task.

**Comment by marandaneto** [comment]
> Disabling it means no deobfuscation, right?
> Also V2 will probably take a while to release.

See https://docs.sentry.io/platforms/android/proguard/#gradle-configuration

    // Only enable it if you are using sentry-android <= v1.7,
    // sentry-android >= v2.0 already does it automatically.
    autoProguardConfig false

it really depends on which SDK version yo uare working on

**Comment by pvegh** [comment]
Oh sorry I think I misunderstood this first.The suggested fix is not about the flag to upload the mapping, my bad.
Removing autoProguardConfig seems

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/2.0.0-alpha.3 removes completely the `autoProguardConfig` and Proguard task, so I'll close it, thanks
