### ISSUE TITLE
Gradle plugin expects DSN for build

### ISSUE THREAD

**Issue by jasonab** [getsentry/sentry-android-gradle-plugin#703]
### Integration

sentry

### Java Version

21

### Version

4.5.1

### Steps to Reproduce

`gradle clean build`

### Expected Result

No error message from Sentry

### Actual Result

error: Auth token is required for this request. Please run `sentry-cli login` and try again!

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

**Comment by romtsn** [comment]
I believe this should be tackled by https://github.com/getsentry/sentry-android-gradle-plugin/pull/708 now

**Comment by romtsn** [comment]
hey @jasonab the issue has been addressed in the version 4.6.0, which just has been published. Please give it a try and let us know. Thank you!

**Comment by jasonab** [comment]
yes, I can confirm the problem is fixed - thanks!
