### ISSUE TITLE
Incompatible with Crashlytics 3.0

### ISSUE THREAD

**Issue by barry-irvine** [getsentry/sentry-android-gradle-plugin#704]
### Gradle Version

8.7.0

### AGP Version

8.4.0

### Code Minifier/Optimizer

R8

### Version

4.5.1

### Sentry SDK Version

7.8.0

### Steps to Reproduce

Build a project with both latest Sentry and Crashlytics plugins

### Expected Result

The project builds.

### Actual Result

The project fails to build

Circular dependency between the following tasks:
:app:debugSentryGenerateIntegrationListTask
\--- :app:processDebugMainManifest
     \--- :app:extractDeepLinksDebug
          \--- :app:injectCrashlyticsMappingFileIdDebug
               \--- :app:kspDebugKotlin
                    \--- :app:processDebugResources
                         +--- :app:mapDebugSourceSetPaths
                         |    \--- :app:injectCrashlyticsMappingFileIdDebug (*)
                         +--- :app:mergeDebugResources
                         |    \--- :app:injectCrashlyticsMappingFileIdDebug (*)
                         +--- :app:parseDebugLocalResources
                         |    \--- :app:packageDebugResources
                         |         \--- :app:injectCrashlyticsMappingFileIdDebug (*)
                         +--- :app:processDebugManifest
                         |    \--- :app:debugSentryGenerateIntegrationListTask (*)
                         \--- :app:processDebugManifestForPackage
                              \--- :app:processDebugManifest (*)

**Comment by romtsn** [comment]
hey, I think it's a problem on the Crashlytics side, see here: https://github.com/firebase/firebase-android-sdk/issues/5925. After they ship their fix, you should not face this issue as well. I'm gonna close it and we can re-open if it's still a problem after that (although I still think it's for firebase to fix). Thanks!
