### ISSUE TITLE
Release Bundle: There are no artifacts in this archive.

### ISSUE THREAD

**Issue by sakibanda** [getsentry/sentry-android-gradle-plugin#710]
### Gradle Version

8.4 (Tried with 8.7 still same issue)

### AGP Version

8.3.2

### Code Minifier/Optimizer

R8

### Version

4.4.0

### Sentry SDK Version

7.9.0

### Steps to Reproduce

Creating release bundle from android studio. with following sentry gradle config.

sentry {
    org = "superstore-43"
    projectName = "amazeai"
    authToken = System.getenv("SENTRY_AUTH_TOKEN")

    debug = true
    includeSourceContext = true
    includeProguardMapping = true
    autoUploadProguardMapping = true
    autoUploadNativeSymbols = true
    uploadNativeSymbols = true
    //additionalSourceDirsForSourceContext
    includeNativeSources = true
    dexguardEnabled = false
    includeDependenciesReport = true
    telemetry = true
    autoInstallation {
        enabled = true
        sentryVersion = "7.9.0"
    }
    tracingInstrumentation {
        enabled.set(true)
        features.set(EnumSet.allOf(InstrumentationFeature::class.java) - InstrumentationFeature.OKHTTP)
        logcat {
            enabled = true
            minLevel = LogcatLevel.WARNING
        }
    }
}

### Expected Result

Uploaded Artifacts should show under Release Bundle in Sentry console.

### Actual Result

> Task :app:sentryUploadSourceBundleRelease
> Found 3 debug information files (3 with embedded sources)
> Prepared debug information files for upload
> Uploaded 1 missing debug information file
> File upload complete:

  UPLOADED 78182bab-fcdc-4a5f-ba67-e5379441b886 (78182bab-fcdc-4a5f-ba67-e5379441b886.zip;  sources)
  DEBUG   2024-05-17 13:17:25.364333400 +05:30 sentry-cli version: 2.28.6, platform: "windows", architecture: "i686"
  INFO    2024-05-17 13:17:25.364466900 +05:30 sentry-cli was invoked with the following command line: "D:\Android\AmazeAI\app\build\tmp\sentry-cli-2.28.6.exe" "--log-level=debug" "--header" "sentry-trace:b44e8593429d4029b9817b16813f2d46-7ec25ae766a64461-1" "--header" "baggage:sentry-environment=Android,sentry-public_key=xxxxx,sentry-release=4.4.0,sentry-sample_rate=1,sentry-sampled=true,sentry-trace_id=b44e8593429d4029b9817b16813f2d46,sentry-transaction=gradle%20build%20Android" "debug-files" "upload" "--type=jvm" "--org" "superstore-43" "--project" "amazeai" "D:\Android\AmazeAI\app\build\intermediates\sentry\release\source-bundle"
  INFO    2024-05-17 13:17:25.364510200 +05:30 Issuing a command for Organization: superstore-43 Project: amazeai
  DEBUG   2024-05-17 13:17:25.364934500 +05:30 request GET https://sentry.io/api/0/organizations/superstore-43/chunk-upload/
  DEBUG   2024-05-17 13:17:25.364964800 +05:30 using token authentication
  DEBUG   2024-05-17 13:17:25.364984400 +05:30 retry number 0, max retries: 0
  DEBUG   2024-05-17 13:17:25.452312300 +05:30 > GET /api/0/organizations/superstore-43/chunk-upload/ HTTP/1.1
  DEBUG   2024-05-17 13:17:25.452374700 +05:30 > Host: sentry.io
  DEBUG   2024-05-17 13:17:25.452392500 +05:30 > Accept: */*
  DEBUG   2024-05-17 13:17:25.452408 +05:30 > Connection: TE
  DEBUG   2024-05-17 13:17:25.452432400 +05:30 > TE: gzip
  DEBUG   2024-05-17 13:17:25.452453700 +05:30 > sentry-trace:b44e8593429d4029b9817b16813f2d46-7ec25ae766a64461-1
  DEBUG   2024-05-17 13:17:25.452476100 +05:30 > baggage:sentry-environment=Android,sentry-public_keykey=xxxxxxxxxxxxxxxxxx,sentry-release=4.4.0,sentry-sample_rate=1,sentry-sampled=true,sentry-trace_id=b44e8593429d4029b9817b16813f2d46,sentry-transaction=gradle%20build%20Android
  DEBUG   2024-05-17 13:17:25.452509700 +05:30 > User-Agent: sentry-cli/2.28.6
  DEBUG   2024-05-17 13:17:25.453577 +05:30 > Authorization: Bearer sntrys_e***
  DEBUG   2024-05-17 13:17:26.682061300 +05:30 < HTTP/1.1 200 OK
  DEBUG   2024-05-17 13:17:26.682129200 +05:30 < server: nginx
  DEBUG   2024-05-17 13:17:26.682152 +05:30 < date: Fri, 17 May 2024 07:47:26 GMT
  DEBUG   2024-05-17 13:17:26.682174 +05:30 < content-type: application/json
  DEBUG   2024-05-17 13:17:26.682196400 +05:30 < vary: Accept-Encoding,Accept-Language, Cookie
  DEBUG   2024-05-17 13:17:26.682219600 +05:30 < allow: GET, POST, HEAD, OPTIONS
  DEBUG   2024-05-17 13:17:26.682247900 +05:30 < access-control-allow-methods: GET, POST, HEAD, OPTIONS
  DEBUG   2024-05-17 13:17:26.682290500 +05:30 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding, sentry-trace, baggage, X-CSRFToken
  DEBUG   2024-05-17 13:17:26.682315700 +05:30 < access-control-expose-headers: X-Sentry-Error, X-Sentry-Direct-Hit, X-Hits, X-Max-Hits, Endpoint, Retry-After, Link
  DEBUG   2024-05-17 13:17:26.682338800 +05:30 < access-control-allow-origin: *
  DEBUG   2024-05-17 13:17:26.682360800 +05:30 < x-sentry-rate-limit-remaining: 39
  DEBUG   2024-05-17 13:17:26.682384100 +05:30 < x-sentry-rate-limit-limit: 40
  DEBUG   2024-05-17 13:17:26.682406 +05:30 < x-sentry-rate-limit-reset: 1715932047
  DEBUG   2024-05-17 13:17:26.682427500 +05:30 < x-sentry-rate-limit-concurrentremaining: 24
  DEBUG   2024-05-17 13:17:26.682449100 +05:30 < x-sentry-rate-limit-concurrentlimit: 25
  DEBUG   2024-05-17 13:17:26.682476200 +05:30 < content-language: en
  DEBUG   2024-05-17 13:17:26.682500600 +05:30 < x-frame-options: deny
  DEBUG   2024-05-17 13:17:26.682524100 +05:30 < x-content-type-options: nosniff
  DEBUG   2024-05-17 13:17:26.682545 +05:30 < x-xss-protection: 1; mode=block
  DEBUG   2024-05-17 13:17:26.682580400 +05:30 < content-security-policy: frame-src app.pendo.io demo.arcade.software js.stripe.com sentry.io; frame-ancestors 'self' *.sentry.io; script-src 'self' 'unsafe-inline' 'report-sample' s1.sentry-cdn.com js.sentry-cdn.com browser.sentry-cdn.com statuspage-production.s3.amazonaws.com static.zdassets.com aui-cdn.atlassian.com connect-cdn.atl-paas.net js.stripe.com 'strict-dynamic' cdn.pendo.io data.pendo.io pendo-io-static.storage.googleapis.com pendo-static-5634074999128064.storage.googleapis.com; worker-src blob:; style-src * 'unsafe-inline'; base-uri 'none'; img-src * blob: data:; object-src 'none'; media-src *; connect-src 'self' *.algolia.net *.algolianet.com *.algolia.io sentry.io *.sentry.io s1.sentry-cdn.com o1.ingest.sentry.io api2.amplitude.com app.pendo.io data.pendo.io reload.getsentry.net t687h3m0nh65.statuspage.io sentry.zendesk.com ekr.zdassets.com maps.googleapis.com; default-src 'none'; font-src * data:; report-uri https://o1.ingest.sentry.io/api/54785/security/?sentry_key=xxxxxxxxxxxxxxxxxx&sentry_release=8186d5c967ca88b398b1f131839c7e3e24e3bf92
  DEBUG   2024-05-17 13:17:26.682604300 +05:30 < x-envoy-attempt-count: 1
  DEBUG   2024-05-17 13:17:26.682625700 +05:30 < x-envoy-upstream-service-time: 64
  DEBUG   2024-05-17 13:17:26.682647600 +05:30 < x-served-by: getsentry-web-rpc-production-747bd694b-xgbp6
  DEBUG   2024-05-17 13:17:26.682671 +05:30 < x-sentry-proxy-url: http://10.2.0.67:8999/api/0/organizations/superstore-43/chunk-upload/
  DEBUG   2024-05-17 13:17:26.682693900 +05:30 < x-served-by: getsentry-control-web-default-common-production-59cd999b6f6v2cj
  DEBUG   2024-05-17 13:17:26.682716200 +05:30 < x-served-by: frontend-default-747768fd88-nkr7p
  DEBUG   2024-05-17 13:17:26.682738200 +05:30 < strict-transport-security: max-age=31536000; includeSubDomains; preload
  DEBUG   2024-05-17 13:17:26.682759600 +05:30 < via: 1.1 google
  DEBUG   2024-05-17 13:17:26.682786700 +05:30 < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  DEBUG   2024-05-17 13:17:26.682818300 +05:30 < Transfer-Encoding: chunked
  DEBUG   2024-05-17 13:17:26.682885600 +05:30 response status: 200
  DEBUG   2024-05-17 13:17:26.682914 +05:30 body: {"url":"https://us.sentry.io/api/0/organizations/superstore-43/chunk-upload/","chunkSize":8388608,"chunksPerRequest":64,"maxFileSize":2147483648,"maxRequestSize":33554432,"concurrency":8,"hashAlgorithm":"sha1","compression":["gzip"],"accept":["debug_files","release_files","pdbs","sources","bcsymbolmaps","il2cpp","portablepdbs","artifact_bundles","artifact_bundles_v2"]}
  DEBUG   2024-05-17 13:17:26.752032700 +05:30 request POST https://sentry.io/api/0/projects/superstore-43/amazeai/files/difs/assemble/
  DEBUG   2024-05-17 13:17:26.752165400 +05:30 using token authentication
  DEBUG   2024-05-17 13:17:26.752244200 +05:30 json body: {"ea15e30c5fbc46a2f2aecca5b70d084f16e8664d":{"name":"dbfbd353-cac3-4684-b943-a233d16df603.zip","debug_id":"dbfbd353-cac3-4684-b943-a233d16df603","chunks":["ea15e30c5fbc46a2f2aecca5b70d084f16e8664d"]},"caf984e1f24915e1f03e80ecf88e7e7590c733a6":{"name":"e6f88aaa-a0b6-431a-b1c5-92f9038ac6bf.zip","debug_id":"e6f88aaa-a0b6-431a-b1c5-92f9038ac6bf","chunks":["caf984e1f24915e1f03e80ecf88e7e7590c733a6"]},"369395e4cc51b598a319d2eddfa8520ad352e0ac":{"name":"78182bab-fcdc-4a5f-ba67-e5379441b886.zip","debug_id":"78182bab-fcdc-4a5f-ba67-e5379441b886","chunks":["369395e4cc51b598a319d2eddfa8520ad352e0ac"]}}
  DEBUG   2024-05-17 13:17:26.752266600 +05:30 retry number 0, max retries: 5
  DEBUG   2024-05-17 13:17:26.752599 +05:30 > POST /api/0/projects/superstore-43/amazeai/files/difs/assemble/ HTTP/1.1
  DEBUG   2024-05-17 13:17:26.752626300 +05:30 > Host: sentry.io
  DEBUG   2024-05-17 13:17:26.752636900 +05:30 > Accept: */*
  DEBUG   2024-05-17 13:17:26.752655200 +05:30 > Connection: TE
  DEBUG   2024-05-17 13:17:26.752666700 +05:30 > TE: gzip
  DEBUG   2024-05-17 13:17:26.752676700 +05:30 > sentry-trace:b44e8593429d4029b9817b16813f2d46-7ec25ae766a64461-1
  DEBUG   2024-05-17 13:17:26.752689100 +05:30 > baggage:sentry-environment=Android,sentry-public_key=xxxxxxxxxxxxxxxxxx,sentry-release=4.4.0,sentry-sample_rate=1,sentry-sampled=true,sentry-trace_id=b44e8593429d4029b9817b16813f2d46,sentry-transaction=gradle%20build%20Android
  DEBUG   2024-05-17 13:17:26.752701100 +05:30 > User-Agent: sentry-cli/2.28.6
  DEBUG   2024-05-17 13:17:26.752733400 +05:30 > Authorization: Bearer sntrys_e***
  DEBUG   2024-05-17 13:17:26.752748900 +05:30 > Content-Type: application/json
  DEBUG   2024-05-17 13:17:26.752758200 +05:30 > Content-Length: 598
  DEBUG   2024-05-17 13:17:27.190285400 +05:30 < HTTP/1.1 200 OK
  DEBUG   2024-05-17 13:17:27.190362700 +05:30 < server: nginx
  DEBUG   2024-05-17 13:17:27.190385200 +05:30 < date: Fri, 17 May 2024 07:47:27 GMT
  DEBUG   2024-05-17 13:17:27.190421900 +05:30 < content-type: application/json
  DEBUG   2024-05-17 13:17:27.190446900 +05:30 < vary: Accept-Encoding,Accept-Language, Cookie
  DEBUG   2024-05-17 13:17:27.190473200 +05:30 < allow: POST, OPTIONS
  DEBUG   2024-05-17 13:17:27.190495700 +05:30 < access-control-allow-methods: POST, OPTIONS
  DEBUG   2024-05-17 13:17:27.190522500 +05:30 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding, sentry-trace, baggage, X-CSRFToken
  DEBUG   2024-05-17 13:17:27.190548400 +05:30 < access-control-expose-headers: X-Sentry-Error, X-Sentry-Direct-Hit, X-Hits, X-Max-Hits, Endpoint, Retry-After, Link
  DEBUG   2024-05-17 13:17:27.190574100 +05:30 < access-control-allow-origin: *
  DEBUG   2024-05-17 13:17:27.190593100 +05:30 < x-sentry-rate-limit-remaining: 39
  DEBUG   2024-05-17 13:17:27.190612400 +05:30 < x-sentry-rate-limit-limit: 40
  DEBUG   2024-05-17 13:17:27.190639900 +05:30 < x-sentry-rate-limit-reset: 1715932048
  DEBUG   2024-05-17 13:17:27.190661800 +05:30 < x-sentry-rate-limit-concurrentremaining: 24
  DEBUG   2024-05-17 13:17:27.190692200 +05:30 < x-sentry-rate-limit-concurrentlimit: 25
  DEBUG   2024-05-17 13:17:27.190714100 +05:30 < content-language: en
  DEBUG   2024-05-17 13:17:27.190740600 +05:30 < x-frame-options: deny
  DEBUG   2024-05-17 13:17:27.190765400 +05:30 < x-content-type-options: nosniff
  DEBUG   2024-05-17 13:17:27.190786400 +05:30 < x-xss-protection: 1; mode=block
  DEBUG   2024-05-17 13:17:27.190816800 +05:30 < content-security-policy: connect-src 'self' *.algolia.net *.algolianet.com *.algolia.io sentry.io *.sentry.io s1.sentry-cdn.com o1.ingest.sentry.io api2.amplitude.com app.pendo.io data.pendo.io reload.getsentry.net t687h3m0nh65.statuspage.io sentry.zendesk.com ekr.zdassets.com maps.googleapis.com; style-src * 'unsafe-inline'; base-uri 'none'; object-src 'none'; default-src 'none'; worker-src blob:; script-src 'self' 'unsafe-inline' 'report-sample' s1.sentry-cdn.com js.sentry-cdn.com browser.sentry-cdn.com statuspage-production.s3.amazonaws.com static.zdassets.com aui-cdn.atlassian.com connect-cdn.atl-paas.net js.stripe.com 'strict-dynamic' cdn.pendo.io data.pendo.io pendo-io-static.storage.googleapis.com pendo-static-5634074999128064.storage.googleapis.com; font-src * data:; media-src *; frame-src app.pendo.io demo.arcade.software js.stripe.com sentry.io; img-src * blob: data:; frame-ancestors 'self' *.sentry.io; report-uri https://o1.ingest.sentry.io/api/54785/security/?sentry_key=xxxxxxxxxxxxxxxxxx&sentry_release=8186d5c967ca88b398b1f131839c7e3e24e3bf92
  DEBUG   2024-05-17 13:17:27.190843600 +05:30 < x-envoy-attempt-count: 1
  DEBUG   2024-05-17 13:17:27.190866300 +05:30 < x-envoy-upstream-service-time: 113
  DEBUG   2024-05-17 13:17:27.190887700 +05:30 < x-served-by: getsentry-web-rpc-production-747bd694b-hc97x
  DEBUG   2024-05-17 13:17:27.190910500 +05:30 < x-sentry-proxy-url: http://10.2.0.67:8999/api/0/projects/superstore-43/amazeai/files/difs/assemble/
  DEBUG   2024-05-17 13:17:27.190934100 +05:30 < x-served-by: getsentry-control-web-default-common-production-59cd999b6fkm94z
  DEBUG   2024-05-17 13:17:27.190955500 +05:30 < x-served-by: frontend-default-747768fd88-xbqvn
  DEBUG   2024-05-17 13:17:27.190977300 +05:30 < strict-transport-security: max-age=31536000; includeSubDomains; preload
  DEBUG   2024-05-17 13:17:27.190998600 +05:30 < via: 1.1 google
  DEBUG   2024-05-17 13:17:27.191019 +05:30 < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  DEBUG   2024-05-17 13:17:27.191038600 +05:30 < Transfer-Encoding: chunked
  DEBUG   2024-05-17 13:17:27.193564700 +05:30 response status: 200
  DEBUG   2024-05-17 13:17:27.193593400 +05:30 body: {"ea15e30c5fbc46a2f2aecca5b70d084f16e8664d":{"state":"ok","detail":null,"missingChunks":[],"dif":{"id":"618466777","uuid":"dbfbd353-cac3-4684-b943-a233d16df603","debugId":"dbfbd353-cac3-4684-b943-a233d16df603","codeId":null,"cpuName":"unknown","objectName":"dbfbd353-cac3-4684-b943-a233d16df603.zip","symbolType":"sourcebundle","headers":{"Content-Type":"application/x-sentry-bundle+zip"},"size":325914,"sha1":"ea15e30c5fbc46a2f2aecca5b70d084f16e8664d","dateCreated":"2024-05-17T07:09:52.003940Z","data":{"type":"src","features":["sources"]}}},"caf984e1f24915e1f03e80ecf88e7e7590c733a6":{"state":"ok","detail":null,"missingChunks":[],"dif":{"id":"618470420","uuid":"e6f88aaa-a0b6-431a-b1c5-92f9038ac6bf","debugId":"e6f88aaa-a0b6-431a-b1c5-92f9038ac6bf","codeId":null,"cpuName":"unknown","objectName":"e6f88aaa-a0b6-431a-b1c5-92f9038ac6bf.zip","symbolType":"sourcebundle","headers":{"Content-Type":"application/x-sentry-bundle+zip"},"size":325914,"sha1":"caf984e1f24915e1f03e80ecf88e7e7590c733a6","dateCreated":"2024-05-17T07:15:48.183553Z","data":{"type":"src","features":["sources"]}}},"369395e4cc51b598a319d2eddfa8520ad352e0ac":{"state":"not_found","missingChunks":["369395e4cc51b598a319d2eddfa8520ad352e0ac"]}}
  DEBUG   2024-05-17 13:17:29.836064 +05:30 request POST https://sentry.io/api/0/projects/superstore-43/amazeai/reprocessing/
  DEBUG   2024-05-17 13:17:29.836124500 +05:30 using token authentication
  DEBUG   2024-05-17 13:17:29.836152600 +05:30 retry number 0, max retries: 0
  DEBUG   2024-05-17 13:17:29.836544100 +05:30 > POST /api/0/projects/superstore-43/amazeai/reprocessing/ HTTP/1.1
  DEBUG   2024-05-17 13:17:29.836570600 +05:30 > Host: sentry.io
  DEBUG   2024-05-17 13:17:29.836596100 +05:30 > Accept: */*
  DEBUG   2024-05-17 13:17:29.836614700 +05:30 > Connection: TE
  DEBUG   2024-05-17 13:17:29.836635700 +05:30 > TE: gzip
  DEBUG   2024-05-17 13:17:29.836662200 +05:30 > sentry-trace:b44e8593429d4029b9817b16813f2d46-7ec25ae766a64461-1
  DEBUG   2024-05-17 13:17:29.836684100 +05:30 > baggage:sentry-environment=Android,sentry-public_key=xxxxxxxxxxxxxxxxxx,sentry-release=4.4.0,sentry-sample_rate=1,sentry-sampled=true,sentry-trace_id=b44e8593429d4029b9817b16813f2d46,sentry-transaction=gradle%20build%20Android
  DEBUG   2024-05-17 13:17:29.836706400 +05:30 > User-Agent: sentry-cli/2.28.6
  DEBUG   2024-05-17 13:17:29.836766700 +05:30 > Authorization: Bearer sntrys_e***
  DEBUG   2024-05-17 13:17:29.836787600 +05:30 > Content-Length: 0
  DEBUG   2024-05-17 13:17:30.222757600 +05:30 < HTTP/1.1 200 OK
  DEBUG   2024-05-17 13:17:30.222847900 +05:30 < server: nginx
  DEBUG   2024-05-17 13:17:30.222869500 +05:30 < date: Fri, 17 May 2024 07:47:30 GMT
  DEBUG   2024-05-17 13:17:30.222893200 +05:30 < content-type: text/html; charset=utf-8
  DEBUG   2024-05-17 13:17:30.222916400 +05:30 < vary: Accept-Encoding,Accept-Language, Cookie
  DEBUG   2024-05-17 13:17:30.222941 +05:30 < allow: POST, OPTIONS
  DEBUG   2024-05-17 13:17:30.222963300 +05:30 < access-control-allow-methods: POST, OPTIONS
  DEBUG   2024-05-17 13:17:30.222989400 +05:30 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding, sentry-trace, baggage, X-CSRFToken
  DEBUG   2024-05-17 13:17:30.223014900 +05:30 < access-control-expose-headers: X-Sentry-Error, X-Sentry-Direct-Hit, X-Hits, X-Max-Hits, Endpoint, Retry-After, Link
  DEBUG   2024-05-17 13:17:30.223042200 +05:30 < access-control-allow-origin: *
  DEBUG   2024-05-17 13:17:30.223065 +05:30 < x-sentry-rate-limit-remaining: 39
  DEBUG   2024-05-17 13:17:30.223087 +05:30 < x-sentry-rate-limit-limit: 40
  DEBUG   2024-05-17 13:17:30.223108600 +05:30 < x-sentry-rate-limit-reset: 1715932051
  DEBUG   2024-05-17 13:17:30.223142 +05:30 < x-sentry-rate-limit-concurrentremaining: 24
  DEBUG   2024-05-17 13:17:30.223161 +05:30 < x-sentry-rate-limit-concurrentlimit: 25
  DEBUG   2024-05-17 13:17:30.223183100 +05:30 < content-language: en
  DEBUG   2024-05-17 13:17:30.223203500 +05:30 < x-frame-options: deny
  DEBUG   2024-05-17 13:17:30.223225500 +05:30 < x-content-type-options: nosniff
  DEBUG   2024-05-17 13:17:30.223246700 +05:30 < x-xss-protection: 1; mode=block
  DEBUG   2024-05-17 13:17:30.223276800 +05:30 < content-security-policy: frame-src app.pendo.io demo.arcade.software js.stripe.com sentry.io; frame-ancestors 'self' *.sentry.io; script-src 'self' 'unsafe-inline' 'report-sample' s1.sentry-cdn.com js.sentry-cdn.com browser.sentry-cdn.com statuspage-production.s3.amazonaws.com static.zdassets.com aui-cdn.atlassian.com connect-cdn.atl-paas.net js.stripe.com 'strict-dynamic' cdn.pendo.io data.pendo.io pendo-io-static.storage.googleapis.com pendo-static-5634074999128064.storage.googleapis.com; object-src 'none'; font-src * data:; img-src * blob: data:; base-uri 'none'; connect-src 'self' *.algolia.net *.algolianet.com *.algolia.io sentry.io *.sentry.io s1.sentry-cdn.com o1.ingest.sentry.io api2.amplitude.com app.pendo.io data.pendo.io reload.getsentry.net t687h3m0nh65.statuspage.io sentry.zendesk.com ekr.zdassets.com maps.googleapis.com; media-src *; worker-src blob:; style-src * 'unsafe-inline'; default-src 'none'; report-uri https://o1.ingest.sentry.io/api/54785/security/?sentry_key=xxxxxxxxxxxxxxxxxx&sentry_release=8186d5c967ca88b398b1f131839c7e3e24e3bf92
  DEBUG   2024-05-17 13:17:30.223311 +05:30 < x-envoy-attempt-count: 1
  DEBUG   2024-05-17 13:17:30.223332400 +05:30 < x-envoy-upstream-service-time: 64
  DEBUG   2024-05-17 13:17:30.223603600 +05:30 < x-served-by: getsentry-web-rpc-production-747bd694b-t8wj9
  DEBUG   2024-05-17 13:17:30.223693800 +05:30 < x-sentry-proxy-url: http://10.2.0.67:8999/api/0/projects/superstore-43/amazeai/reprocessing/
  DEBUG   2024-05-17 13:17:30.223727400 +05:30 < x-served-by: getsentry-control-web-default-common-production-59cd999b6f6v9w5
  DEBUG   2024-05-17 13:17:30.223762900 +05:30 < x-served-by: frontend-default-747768fd88-b47lc
  DEBUG   2024-05-17 13:17:30.223790400 +05:30 < strict-transport-security: max-age=31536000; includeSubDomains; preload
  DEBUG   2024-05-17 13:17:30.223811300 +05:30 < via: 1.1 google
  DEBUG   2024-05-17 13:17:30.223833200 +05:30 < Content-Length: 0
  DEBUG   2024-05-17 13:17:30.223870500 +05:30 < Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  DEBUG   2024-05-17 13:17:30.223918700 +05:30 response status: 200
  DEBUG   2024-05-17 13:17:30.223941 +05:30 body: 
  DEBUG   2024-05-17 13:17:30.224035700 +05:30 skipping update nagger because session is not attended

DEBUG: Capturing transaction: e09c1cc1bc96470e9a454a2adf3bc9d6
DEBUG: UncaughtExceptionHandlerIntegration removed.
INFO: Closing SentryClient.
DEBUG: Serializing object: {"transaction":"gradle build Android","start_timestamp":1715931884.842993,"timestamp":1715932050.237264,"spans":[{"start_timestamp":1715931890.751089,"timestamp":1715931890.755075,"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"043261d6e22a4d0d","parent_span_id":"553db98bfeae4f9c","op":"3379458255_SentryGenerateIntegrationListTask_Decorated","origin":"manual","data":{}},{"start_timestamp":1715931895.802364,"timestamp":1715931895.803361,"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"b1c4802d0f834559","parent_span_id":"553db98bfeae4f9c","op":"3379458255_GenerateBundleIdTask_Decorated","origin":"manual","data":{}},{"start_timestamp":1715932010.383088,"timestamp":1715932010.385083,"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"9d35eb85c90c444f","parent_span_id":"553db98bfeae4f9c","op":"3379458255_SentryGenerateProguardUuidTask_Decorated","origin":"manual","data":{}},{"start_timestamp":1715932010.386079,"timestamp":1715932010.388072,"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"8c6175bd74314a9a","parent_span_id":"553db98bfeae4f9c","op":"3379458255_SentryGenerateDebugMetaPropertiesTask_Decorated","origin":"manual","data":{}},{"start_timestamp":1715932029.359251,"timestamp":1715932041.032662,"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"5fce5b0440ff445d","parent_span_id":"553db98bfeae4f9c","op":"3379458255_SentryUploadProguardMappingsTask_Decorated","origin":"manual","data":{}},{"start_timestamp":1715932041.034657,"timestamp":1715932044.410360,"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"5aadf7f75d004eef","parent_span_id":"553db98bfeae4f9c","op":"3379458255_SentryUploadNativeSymbolsTask_Decorated","origin":"manual","data":{}},{"start_timestamp":1715932044.423319,"timestamp":1715932044.713062,"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"0e565057abc44e1e","parent_span_id":"553db98bfeae4f9c","op":"3379458255_CollectSourcesTask_Decorated","origin":"manual","data":{}},{"start_timestamp":1715932044.731002,"timestamp":1715932045.321227,"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"2056e3e088ba4bb7","parent_span_id":"553db98bfeae4f9c","op":"3379458255_BundleSourcesTask_Decorated","origin":"manual","data":{}},{"start_timestamp":1715932045.327207,"timestamp":1715932050.236267,"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"7ec25ae766a64461","parent_span_id":"553db98bfeae4f9c","op":"3379458255_UploadSourceBundleTask_Decorated","origin":"manual","data":{}}],"type":"transaction","transaction_info":{"source":"custom"},"event_id":"e09c1cc1bc96470e9a454a2adf3bc9d6","contexts":{"runtime":{"name":"JetBrains s.r.o.","version":"17.0.9"},"trace":{"trace_id":"b44e8593429d4029b9817b16813f2d46","span_id":"553db98bfeae4f9c","op":"build","origin":"manual"}},"sdk":{"name":"sentry.java","version":"6.31.0","packages":[{"name":"maven:io.sentry:sentry","version":"6.31.0"}],"integrations":["UncaughtExceptionHandler","ShutdownHook"]},"tags":{"AGP_VERSION":"8.3.2","includeNativeSources":"true","ignoredBuildTypes_set":"false","tracing_enabled":"true","includeSourceContext":"true","autoInstallation_enabled":"true","uploadNativeSymbols":"true","autoUpload":"true","includeDependenciesReport":"true","SDK_VERSION":"7.6.0","dexguardEnabled":"false","tracing_features":"[DATABASE, FILE_IO, COMPOSE]","tracing_logcat_minLevel":"WARNING","tracing_debug":"false","tracing_forceInstrumentDependencies":"false","SENTRY_CLI_VERSION":"2.28.6","ignoredVariants_set":"false","debug":"true","GRADLE_VERSION":"8.4","includeProguardMapping":"true","additionalSourceDirsForSourceContext_set":"false","BUILD_SYSTEM":"gradle","tracing_logcat_enabled":"true","autoInstallation_sentryVersion":"7.9.0","autoUploadNativeSymbols":"true","autoUploadProguardMapping":"true","ignoredFlavors_set":"false","step":"3379458255_UploadSourceBundleTask_Decorated"},"release":"4.4.0","environment":"Android","platform":"java","user":{"id":"superstore-43"},"server_name":"Dev-PC"}
DEBUG: Envelope sent successfully.
DEBUG: Envelope flushed
DEBUG: Serializing object: {"sid":"322700c6-2cdc-4d05-9a4d-ebbed0d5c09f","started":"2024-05-17T07:44:44.842Z","status":"exited","seq":1715932050238,"errors":0,"duration":165.396,"timestamp":"2024-05-17T07:47:30.238Z","attrs":{"release":"4.4.0","environment":"Android"}}
DEBUG: Envelope sent successfully.
DEBUG: Envelope flushed
DEBUG: Shutting down

**Comment by sakibanda** [comment]
Upgrade to 4.4.1 worked but from 4.5.0 its taking too long no debug info either.

**Comment by sakibanda** [comment]
My mistake, i am able to see the uploaded files under Debug Files & ProGuard Mappings

**Comment by sakibanda** [comment]
Is it ok that there are no artifacts when using android gradle plugin?

**Comment by sakibanda** [comment]
Another update with the mapping files in place.

On one issue, some of the stack track shows non obfuscated code but some don't show. Here is the screenshot for issue :  5368870546 project id : 4507061607006208

Any reason why complete source code is not showing?

![image](https://github.com/getsentry/sentry-android-gradle-plugin/assets/150966/709dd4b7-124e-4234-adf6-aae1915d1aa6)

**Comment by markushi** [comment]
Hi @sakibanda, thanks for reaching out and providing all the details!

As far as I can see the debug id for your ProGuard mapping file is not being sent by your app, which then makes it unable for our backend to deobfuscate the stacktraces.

Could you describe your Gradle setup a bit more? Do you have different built types / flavors configured?
Our Sentry Android Gradle plugin should automatically embed the ProGuard mapping debug id into your APK. You can check this the following way:

```shell
unzip -p <path-to-app.apk> assets/sentry-debug-meta.properties
```

**Comment by sakibanda** [comment]
Hi @markushi 

Thanks for your reply.

Its working now somehow. Earlier, I was using same number for version code and version name, but after changing this to different values. I was able to see deobfuscated stacktraces like Issue ID: 5382719429

Gradle setup is as usual one debug build without any minify and obfuscation. And one release build with minify and obfuscation. Here are the details from gradle file:
```
    sentry {
        org = "xxxx"
        projectName = "xxxx"
        authToken = System.getenv("SENTRY_AUTH_TOKEN")
    
        debug = true
        includeSourceContext = true
        includeProguardMapping = true
        autoUploadProguardMapping = true
        autoUploadNativeSymbols = true
        uploadNativeSymbols = true
        includeNativeSources = true
        dexguardEnabled = false
        includeDependenciesReport = true
        telemetry = true
        autoInstallation {
            enabled = true
            sentryVersion = "7.9.0"
        }
        tracingInstrumentation {
            enabled.set(true)
            features.set(EnumSet.allOf(InstrumentationFeature::class.java) - InstrumentationFeature.OKHTTP)
            logcat {
                enabled = true
                minLevel = LogcatLevel.WARNING
            }
        }
    }
    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            ndk.debugSymbolLevel = "FULL"
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("debug")
        }
        debug{
            signingConfig = signingConfigs.getByName("debug")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
```

**Comment by markushi** [comment]
@sakibanda thanks for getting back. Yes, this looks way better now! I'm closing this now, if you encounter any other issue feel free to re-open or create a new issue.
