### ISSUE TITLE
Execution failed for AsmClassesTransform

### ISSUE THREAD

**Issue by satyasivaprasad** [getsentry/sentry-android-gradle-plugin#714]
### Gradle Version

7.1.3

### AGP Version

7.1.3

### Code Minifier/Optimizer

Proguard

### Version

7.9.0

### Sentry SDK Version

4.6.0

### Steps to Reproduce

Execution failed for AsmClassesTransform:

### Expected Result

Execution failed for task ':app:mergeExtDexQa'.
> Could not resolve all files for configuration ':app:qaRuntimeClasspath'.
   > Failed to transform vivalink-libs-core-1.4.aar (vigo.vivalink.libs:vivalink-libs-core:1.4) to match attributes {artifactType=android-dex, asm-transformed-variant=qa, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AsmClassesTransform: /Users/siva/.gradle/caches/transforms-3/ae04c72823ca4937fa0d7b4659b6f560/transformed/jetified-vivalink-libs-core-1.4-runtime.jar.
         > java.lang.ArrayIndexOutOfBoundsException (no error message)

* Try:

### Actual Result

Error should be solved

**Comment by romtsn** [comment]
hi @satyasivaprasad, thanks for the report, we'll take a look and get back to you soon!

**Comment by satyasivaprasad** [comment]
@romtsn  Any update?

**Comment by kahest** [comment]
Hey @satyasivaprasad no updates as of now, we'll follow up on this issue once we managed to repro it or if we have questions.

**Comment by markushi** [comment]
@satyasivaprasad from the stacktrace we can see `vigo.vivalink.libs:vivalink-libs-core:1.4`, is this a private library which is obfuscated?

**Comment by romtsn** [comment]
@satyasivaprasad most likely we won't be able to fix the issue without having access to the library, but you can work this around by excluding its classes from instrumentation as follows:

```kotlin
// in your app/build.gradle.kts
sentry {
  tracingInstrumentation {
  	excludes.set(setOf("vigo/vivalink/**"))
  }
}

```

**Comment by romtsn** [comment]
@satyasivaprasad have you had a chance to take a look at our suggestions?

**Comment by satyasivaprasad** [comment]
after adding 

"sentry {
  tracingInstrumentation {
  	excludes.set(setOf("vigo/vivalink/**"))
  }
}"

facing the same issue

**Comment by satyasivaprasad** [comment]
> @satyasivaprasad from the stacktrace we can see `vigo.vivalink.libs:vivalink-libs-core:1.4`, is this a private library which is obfuscated?

yes

**Comment by romtsn** [comment]
> after adding
> 
> "sentry { tracingInstrumentation { excludes.set(setOf("vigo/vivalink/**")) } }"
> 
> facing the same issue

hmm, that should work, unless the library package name differs from `vigo.vivalink.**`. Can you check what's the package name of the classes coming from this lib?

**Comment by romtsn** [comment]
```
 tracingInstrumentation { excludes.set([ "vigo/vivalink/**", "com/vivalink/**" ]) }
```
I'm not sure it's a correct way to set it. Do you use `.gradle` or `.gradle.kts`?

**Comment by satyasivaprasad** [comment]
> .gradle

I am using ".gradle"

**Comment by romtsn** [comment]
oh ok, then it should be:
```
tracingInstrumentation { 
  excludes = ['com/vivalink/**']
}
```

**Comment by satyasivaprasad** [comment]
> oh ok, then it should be:
> 
> ```
> tracingInstrumentation { 
>   excludes = ['com/vivalink/**']
> }
> ```

No luck , still facing issue

`Execution failed for task ':app:mergeExtDexQa'.
> Could not resolve all files for configuration ':app:qaRuntimeClasspath'.
   > Failed to transform vivalink-libs-core-1.4.aar (vigo.vivalink.libs:vivalink-libs-core:1.4) to match attributes {artifactType=android-dex, asm-transformed-variant=qa, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AsmClassesTransform: /Users/siva/.gradle/caches/transforms-3/ae04c72823ca4937fa0d7b4659b6f560/transformed/jetified-vivalink-libs-core-1.4-runtime.jar.
         > java.lang.ArrayIndexOutOfBoundsException (no error message)
`

**Comment by romtsn** [comment]
hey @satyasivaprasad, I've finally had time to take a look into this, thanks for sending me over the library! Based on my observations, I think the following config should set you up:

```gradle
tracingInstrumentation { 
  excludes = ['com/vivalink/**', 'com/ihealth/**']
}
```

please try it out and let us know if that helped. Thanks!

**Comment by romtsn** [comment]
@satyasivaprasad have you had a chance to look at my suggestion above?

**Comment by stefanosiano** [comment]
closing this issue. If it is still relevant, feel free to reopen and add a comment
