### ISSUE TITLE
Does Screenshot don't need user consent?

### ISSUE THREAD

**Issue by sakibanda** [getsentry/sentry-android-gradle-plugin#718]
### Problem Statement

I am using screenshots feature but is it not against privacy violation?

Do I need to take user consent before sending screenshot? Do I need to implement it or just include this in privacy policy?

### Solution Brainstorm

Show alert dialog where user can choose to agree to send screenshot for this issue and option to send for all future issues.

**Comment by romtsn** [comment]
this actually depends on your app policies and terms of service, so we cannot really recommend anything and leave it up to you to decide whether you want to show the consent dialog. The SDK does not have built-in support for showing a Consent Dialog, but you can upvote this issue to have us increase the priority: https://github.com/getsentry/team-mobile/issues/24

I'm going to close this issue, but feel free to comment here or on the linked issue if you have any questions/suggestions. Thank you!
