### ISSUE TITLE
conditionally enable Sentry for non-Android projects

### ISSUE THREAD

**Issue by samhanes-fs** [getsentry/sentry-android-gradle-plugin#737]
### Problem Statement

When using the plain Java version of the plugin (`io.sentry.jvm.gradle`) as described in [Sentry for Java](https://docs.sentry.io/platforms/java/gradle/), it attempts to upload a Source Context bundle for _every_ build that includes the `assemble` task, including those run by developers on their local machines. That typically fails on a missing Sentry auth token, which makes it impossible to build jars without providing a token and uploading the source bundle.

The Android version of the plugin has `ignoreVariants`, `ignoreFlavors`, and `ignoreBuildTypes`, but those options don't do anything for for non-Android projects (which makes sense - those are Android concepts), and there's no equivalent available.

To work around this, I've had to enable the plugin conditionally using the legacy `apply plugin` syntax:
```groovy
buildscript {
    dependencies {
        // the Sentry plugin is applied conditionally using the legacy method
        // because otherwise it runs for all builds, even for local development
        classpath 'io.sentry.jvm.gradle:io.sentry.jvm.gradle.gradle.plugin:4.10.0'
    }
}

dependencies {
    implementation 'io.sentry:sentry-spring-boot-jakarta:7.12.0'
    implementation 'io.sentry:sentry-logback:7.12.0'
}

// use the Sentry plugin to upload a source bundle
// but only for release builds, and only if we have a Sentry token
if (
    !version.toString().endsWith('-SNAPSHOT')
    && System.getenv('SENTRY_AUTH_TOKEN') != null
) {
    apply plugin: 'io.sentry.jvm.gradle'

    sentry {
        org = 'aamit'
        projectName = 'crs-api'
        authToken = System.getenv("SENTRY_AUTH_TOKEN")

        includeSourceContext = true
        includeDependenciesReport = true

        // can't use this because we only apply the plugin conditionally
        autoInstallation { enabled = false }
    }
}
```

### Solution Brainstorm

Provide a "non-release" mode where the tasks that require the Sentry CLI and an auth token don't run automatically. Allow projects to configure whether the plugin runs in release mode in `build.gradle`, e.g.
```groovy
sentry {
    release = !version.toString().endsWith('-SNAPSHOT')
}
```

Making it a boolean property gives project maintainers the flexibility to define what constitutes a release build which should have a Source Context bundle uploaded to Sentry.

The Auto Installation feature needs to behave identically whether or not the plugin is in release mode so that the Sentry API is always available to the application code and so that the dependencies are consistent across all builds (especially important for projects using lockfiles).

Ideally, when I'm not running a release build I don't want the plugin to download and run the Sentry CLI at all.

**Comment by lbloder** [comment]
Hi @samhanes-fs,
Thanks for reaching out.

I think, you can actually use the `includeSourceContext` flag for this, it controls the `collectSources`, `bundleSources` and `uploadSourceBundle` tasks. Here's a quick example based on your condition:

```
    sentry {
        org = 'aamit'
        projectName = 'crs-api'
        authToken = System.getenv("SENTRY_AUTH_TOKEN")

        includeSourceContext = !version.toString().endsWith('-SNAPSHOT') && System.getenv('SENTRY_AUTH_TOKEN') != null
        includeDependenciesReport = true

        // can't use this because we only apply the plugin conditionally
        autoInstallation { enabled = false }
    }
``` 

So the plugin is always active and the `sourceContext` is only created and uploaded if your condition is met.

Could you give this a try and let me know the outcome?
