### ISSUE TITLE
uploading mappings Error:  request failure (http status: 500)

### ISSUE THREAD

**Issue by RangerAnan** [getsentry/sentry-android-gradle-plugin#74]
_sentry-android-gradle-plugin:_
**1.7.27*

_Gradle:_
**6.7**

_Optimizer:_
- [x]  ProGuard
- [ ]  R8

_Have you created the sentry.properties file?_
- [x]  Yes -> where?
- [ ]  No

_SDKs:_
- [x]  sentry-android -> which version?     //4.3.0
- [ ]  sentry-react-native -> which version?

---
I have the following issue:
> Task :app:persistSentryProguardUuidsForZntReleaseZnt-release
> compressing mappings
> uploading mappings
error: API request failed
  caused by: sentry reported an error: request failure (http status: 500)
  Object({"detail": String("Internal Error"), "errorId": String("f9edb6df15be4cd7a597d76850155192")})

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

> Task :app:persistSentryProguardUuidsForZntReleaseZnt-release FAILED

FAILURE: Build failed with an exception.

**Comment by marandaneto** [comment]
@RangerAnan try upgrading the plugin to the latest version, please.

**Comment by RangerAnan** [comment]
has The same problem(http status: 500) when upgraded

**Comment by marandaneto** [comment]
how your `sentry.properties` looks like? which folder did you place in? could you export `SENTRY_LOG_LEVEL=debug` run it and copy-paste the full log? thanks

**Comment by marandaneto** [comment]
news here @RangerAnan ?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
