### ISSUE TITLE
java.lang.IllegalAccessError: Field 'okhttp3.OkHttpClient$Builder.eventListenerFactory'

### ISSUE THREAD

**Issue by KB-C-Mobile** [getsentry/sentry-android-gradle-plugin#762]
### Gradle Version

8.10

### AGP Version

8.6.0

### Code Minifier/Optimizer

Proguard

### Version

3.11>=

### Sentry SDK Version

Automatically added by the Sentry Android Gradle Plugin

### Steps to Reproduce

We have upgraded the Sentry Gradle plugin from version 2.1,.5 to the latest version. The application crashes after the upgrade.
We've tried versions like 4.x, 3.11-3.14, but the APK still crashes. The only version that works is <= 3.10. We found a similar bug at https://github.com/getsentry/sentry-android-gradle-plugin/pull/514. Based on the code `if (okHttpVersion.major >= 4)`, we generated a tree of dependencies and made sure that all dependencies use the latest okHttpVersion, 4.12. It doesn't seem to matter whether we use minify or not. 

### Expected Result

A working app.

### Actual Result

```kotlin
java.lang.IllegalAccessError: Field 'okhttp3.OkHttpClient$Builder.eventListenerFactory' is inaccessible to class 'okhttp3.OkHttpClient' (declaration of 'okhttp3.OkHttpClient' appears in /data/app/~~ie6boU6zHaffW7r9QCEzZw==/com.x.y.z-VSYu4OJ1v4FL_tjvzao7zA==/base.apk!classes7.dex)
at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:121)

at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069)

at com.x.y.z.core.data.rest.OkHttpClientFactory.create(OkHttpClientFactory.kt:56)

at com.x.y.z.c.service.ZXCOkHttpClientFactory.create(ZXCOkHttpClientFactory.java:61)

at com.x.y.z.core.data.rest.service.ServiceApiFactory.<init>(ServiceApiFactory.kt:23)

at com.x.y.z.DaggerZXCApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get0(DaggerZXCApplication_HiltComponents_SingletonC.java:6706)

at com.x.y.z.DaggerZXCApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerZXCApplication_HiltComponents_SingletonC.java:7022)

at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
```

**Comment by romtsn** [comment]
hi @KB-C-Mobile, sorry for the trouble! Would you mind trying to enable `forceInstrumentDependencies` (one-time), to invalidate and re-instrument your local jars. Seems like this is a caching issue after updating the Sentry gradle plugin version.

```gradle
sentry {
  tracingInstrumentation {
    forceInstrumentDependencies = true // or .set(true) for kts
  }
}
```

If it still doesn't work, I'd ask you to provide a minimal reproducible sample, if possible.

**Comment by KB-C-Mobile** [comment]
ForceInstrumentDependencies doesn't work.
However, I disabled auto-install with the Sentry Android Gradle plugin and manually added SentryOkHttpInterceptor, SentryOkHttpEventListener. Now it seems to work.
https://docs.sentry.io/platforms/android/integrations/okhttp/#manual-installation

**Comment by romtsn** [comment]
it's still not a proper fix though, but thanks for the update! We'll keep it closed for now, if someone else reports the same issue, we can revisit this.
