### ISSUE TITLE
User interaction tracking for Compose testTag stopped working

### ISSUE THREAD

**Issue by audkar** [getsentry/sentry-android-gradle-plugin#784]
### Gradle Version

8.10.2

### AGP Version

8.7.1

### Code Minifier/Optimizer

None

### Version

4.13.0

### Sentry SDK Version

7.16.0

### Steps to Reproduce

1. Setup basic Android project config with `io.sentry.kotlin.compiler.gradle` plugin added
2. Add a clickable composable. e.g. `Button(modifier = Modifier.testTag("click_me"), <..>)`
3. Run app and click button.

### Expected Result

User interaction Breadcrumb with `click_me` is registered

### Actual Result

No such breadcrumb registered

(Use of `.sentryTag("click_me")` does work)

**Comment by romtsn** [comment]
oh, not again 🙈 did it start happening after bumping the compose version or the sentry sdk version?

**Comment by audkar** [comment]
I do not have the answer. Our dependencies are automatically kept up to date. At some point, this Sentry functionality stopped working. It was only reported when developers noticed that click breadcrumbs were missing from screens created with Compose. Since we don't have integration tests that test the Sentry functionality, I can't say when it broke.

**Comment by romtsn** [comment]
@audkar understood, we'll take a look and sorry for the trouble again! We'll set up compat matrix for testing soon
