### ISSUE TITLE
Add `chunkUpload` option to use the new cli capability to upload proguard mappings chunked

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-android-gradle-plugin#789]
### Description

After [this](https://github.com/getsentry/sentry-cli/pull/2264) lands, we could add a new option that sets the experimental env variable to enable chunk upload for the upload proguard mappings task.

```[tasklist]
### 🛑 Blocked by
- [ ] https://github.com/getsentry/sentry-cli/pull/2264
```

**Comment by szokeasaurusrex** [comment]
I don't think we should add this option; users should just set the environment variable directly. This "experimental" chunk uploading feature is meant as a temporary solution; I am still working on the more permanent solution, which should be ready in a few weeks. Once it is ready, chunk uploading will become the default upload mechanism for Proguard files.

**Comment by romtsn** [comment]
closing for now then 👍
