### ISSUE TITLE
Confused on how to integrate sentry

### ISSUE THREAD

**Issue by ColtonIdle** [getsentry/sentry-android-gradle-plugin#802]
### Description

I have a new project and I'm not sure if I need the android gradle plugin or not. I've read through the docs and I don't want to do the setup via the sentry wizard... but so far I just added the dependencies myself (without the plugin) and everything seems to work. confused why id even need the plugin?

Most tools only have a single way to integrate, but looks like sentry has:
- the wizard
- the plugin
- the libraries

i know that each one probably came out in order to simplify things, but im just confused. lol

**Comment by markushi** [comment]
Hey @ColtonIdle, thanks for reaching out! Our plugin is optional, but it has quite a few features, which save you from writing any extra code. Here are the docs to get started: https://docs.sentry.io/platforms/android/configuration/gradle/

If you have any detailed feedback, we'd be happy to hear about them to improve our docs!

**Comment by ColtonIdle** [comment]
thanks. so if i use the plugin, then I also dont need to declare the dependencies myself (or declare a BOM?). So that just leaves me with a single version to bump (the sentry gradle plugin) and I'll get the updates that I would from bumping the BOM?

**Comment by markushi** [comment]
Yes, exactly! The Gradle plugin will automatically add the SDK dependencies to your `:app` module.

**Comment by ColtonIdle** [comment]
Got it. looks like that feature is sorta new. so maybe that add to the confusion.
going further on that. i think i was even more confused because of the overloaded nature of "manual setup" and the auto setup.

in crashlytics, manual setup is when i dont use the plugin and therefore it doesn't use the content provider or anything. and i just need to init it myself in my application class. while in sentry the cmd line wizard is kinda a new thing (at least to me as an android dev for 5+ years that has integrated a lot of sdks) the wizard kinda threw me off. and the "manual" steps weren't really manual. theres just the way that you set it up. lol.

idk. just trying to offer some helpful feedback on where i got confused as a decently senior android dev. I think I will be going the route of adding the plugin myself, disabling auto-init (i hate the content provider "trick") and initing sentry myself in the app class.

Closing this for now. hope some of the feedback was constructive. Cheers @markushi and thanks for always having a quick and welcoming (and non-dismissive) response to questions! ❤

**Comment by ColtonIdle** [comment]
@markushi FWIW. it looks like gradle plugin doesn't apply the sentry okhttp interceptor. so i still need to add the bom directly in my case. would be good to note maybe what to do in this sort of scenario because only having to define the plugin (and therefore only a single "sentry" version, would be nice)

**Comment by romtsn** [comment]
@ColtonIdle that smells like a bug actually. Could you share how do you verify whether the interceptor is applied? Do you check gradle deps or bytecode or just the Sentry dashboard for http breacrumbs presence?

**Comment by ColtonIdle** [comment]
I just couldn't compile my app because it uses SentryOkHttpInerceptor

**Comment by romtsn** [comment]
I guess you probably applied the plugin to the `app` module, but your SentryOkHttpInterceptor is in another module, right? I think this is a flaw with the current approach, we could potentially fix it when supporting multi-module apps.

**Comment by ColtonIdle** [comment]
nope. single module app

**Comment by ColtonIdle** [comment]
@romtsn related question now. Seems like I'm continuing to get failures from networking code that isn't mine. like 500's from firebase api when it went down. i dont want these to clutter sentry as im already towards my limit. how do i remove them?

**Comment by romtsn** [comment]
@ColtonIdle you can disable OkHttp auto-instrumentation as mentioned [here](https://docs.sentry.io/platforms/android/integrations/okhttp/#disable). But there's no granular configuration for which clients you want to instrument or not, unfortunately. It's all or nothing.

**Comment by ColtonIdle** [comment]
Thanks. FWIW. I find it weird that to disable auto-instrumentation of okhttp you need

sentry {
  tracingInstrumentation {
    enabled = true
    features = EnumSet.allOf(InstrumentationFeature) - InstrumentationFeature.OKHTTP
  }
}

but for timber you need

configurations.configureEach {
  exclude group: "io.sentry", module: "sentry-android-timber"
}
.

Last question. Can I add okhttp-sentry dependency so that I can add okhttp interceptor to MY okhttp client, but disable auto-instrumentation of other okhttp clients (from third party libs)?

**Comment by romtsn** [comment]
> but for timber you need
> configurations.configureEach {
> exclude group: "io.sentry", module: "sentry-android-timber"
> }

That's because Timber is not auto-instrumented through bytecode, but just at runtime: we check via reflection if it's present on the classpath and install our tree. We have an [issue](https://github.com/getsentry/sentry-docs/issues/7035) to improve that though, I agree it's confusing.

> Can I add okhttp-sentry dependency so that I can add okhttp interceptor to MY okhttp client, but disable auto-instrumentation of other okhttp clients (from third party libs)?

Yeah, for sure. Just throw the okhttp dependency in and add the interceptor/eventlistener as described [here](https://docs.sentry.io/platforms/android/integrations/okhttp/#install-1).

**Comment by ColtonIdle** [comment]
gotcha. i thought (oroginally) that the okhttp dependency was the thing that added auto-instrumentation. to my chagrin when i removed it, but i kept getting issues from Firebase library internal networking errors. lol

cool. (and yeah i figured about the disabling between okhttp and timber was due to some technical constraints... but wnated to at least bring it up to make sure im not going crazy). personally id love an overall "disable auto instrumentation of 3rd party libs" but im fine with this. thank you for the detailed explainer!

**Comment by ColtonIdle** [comment]
Nevermind. there is another section that prints out json of integrations. and that includes okhttp!
