### ISSUE TITLE
Plugin fails for variants that generate no mappings

### ISSUE THREAD

**Issue by cerisier** [getsentry/sentry-android-gradle-plugin#82]
_Android Gradle Plugin:_
**4.1.3**

_Gradle:_
**6.7.1**

_Optimizer:_
- [ ]  ProGuard
- [x]  R8

_Have you created the sentry.properties file?_
- [x]  Yes -> where?
- [ ]  No

_SDKs:_
- [x]  sentry-android-gradle-plugin -> 2.0.0-alpha.2

---
I have the following issue:

Plugin fails with missing mappings for variants that do not produce mappings (`minifyEnabled false`)
```
problem was found with the configuration of task ':app:uploadSentryProguardMappingsRegularLoveDebugRegular-love-debug' (type 'SentryUploadProguardMappingsTask').
--
  | > No value has been specified for property 'mappingsFile'.
```

**Comment by cerisier** [comment]
Just seen you created a similar issue #83. Letting you close if needed.

**Comment by marandaneto** [comment]
I'll let yours as you opened first :)

what we can do is:

not creating `uploadSentryProguardMappingsTask` if `variant.buildType.isMinifyEnabled` is disabled for example
