### ISSUE TITLE
Transformer task not found when R8 is disabled

### ISSUE THREAD

**Issue by markdingram** [getsentry/sentry-android-gradle-plugin#9]
Using Gradle 5.6.4 

gradle.properties:
`android.enableR8=false`

`./gradlew tasks `shows that no addSentryProguardSettingsFor... tasks are created, and release builds fail due to missing Proguard config for Sentry. 

Looks like the getTransformerTask is not finding the minify${variant.name.capitalize()}With**Proguard** tasks here? 

(I guess Gradle changed at some point as there don't appear to be any tasks beginning with  transformClassesAndResources... whether or not the enableR8 flag is set.)

**Comment by marandaneto** [comment]
hey @markdingram thanks for your message.

Which `sentry-android-gradle-plugin` and `AGP` versions are you working with?

Those task names have changed in the past, but it is compatible with Gradle 5.6.4, send me that info and I'll check it out, thanks.

**Comment by marandaneto** [comment]
hey @markdingram :) you were right, just tested it and found out.

It seems that AGP 3.6.x created a new task for Proguard on AGP 3.6.x but it was an easy fix #10
I'll release a new version latest by the end of the week, thanks for reporting this.

**Comment by markdingram** [comment]
Thank you very much @marandaneto !

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/v1.7.33
