### ISSUE TITLE
Cannot query the value of this property because it has no value available

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android-gradle-plugin#91]
[sentry] .mappingFileProvider is missing for com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated@5f98da2e - Error: Cannot query the value of this property because it has no value available.

this could be solved automatically if we work on https://github.com/getsentry/sentry-android-gradle-plugin/issues/84

it's not a bug though, as it does not break the build or anything

**Comment by cortinico** [comment]
> this could be solved automatically if we work on #84

Yup true.

> it's not a bug though, as it does not break the build or anything

Perhaps the logger level of that message could be changed from `warn` to `info`.

**Comment by cortinico** [comment]
Closed by #111
