### ISSUE TITLE
Task ':app:lintVitalRelease' uses this output of task ':app:generateSentryProguardUuidReleaseRelease' without declaring an explicit or implicit dependency

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-android-gradle-plugin#92]
Task :app:lintVitalRelease
Execution optimizations have been disabled for task ':app:lintVitalRelease' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/android/app/build/generated/assets/sentry/release'. Reason: Task ':app:lintVitalRelease' uses this output of task ':app:generateSentryProguardUuidReleaseRelease' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - 
Gradle detected a problem with the following location: '/android/app/build/generated/assets/sentry/release'. Reason: Task ':app:lintVitalRelease' uses this output of task ':app:generateSentryProguardUuidReleaseRelease' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradle.org/7.0/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

**Comment by cortinico** [comment]
> Task :app:lintVitalRelease

This is not with the `:example` modules right? Can we craft a reproducer as I wasn't really able to reproduce. I'm actually getting this other issue:

```
Execution optimizations have been disabled for task ':examples:android-gradle-kts:lintVitalRelease' to ensure correctness due to the following reasons:
  - Type 'LintPerVariantTask' property 'allInputs' cannot be resolved:  Cannot convert the provided notation to a File or URI: classes.jar (project :examples:android-gradle-kts). The following types/formats are supported:  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'. - A String or CharSequence URI, for example 'file:/usr/include'. - A File instance. - A Path instance. - A Directory instance. - A RegularFile instance. - A URI or URL instance. - A TextResource instance. Reason: An input file collection couldn't be resolved, making it impossible to determine task inputs. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#unresolvable_input for more details about this problem.
```

**Comment by marandaneto** [comment]
> > Task :app:lintVitalRelease
> 
> This is not with the `:example` modules right? Can we craft a reproducer as I wasn't really able to reproduce. I'm actually getting this other issue:
> 
> ```
> Execution optimizations have been disabled for task ':examples:android-gradle-kts:lintVitalRelease' to ensure correctness due to the following reasons:
>   - Type 'LintPerVariantTask' property 'allInputs' cannot be resolved:  Cannot convert the provided notation to a File or URI: classes.jar (project :examples:android-gradle-kts). The following types/formats are supported:  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'. - A String or CharSequence URI, for example 'file:/usr/include'. - A File instance. - A Path instance. - A Directory instance. - A RegularFile instance. - A URI or URL instance. - A TextResource instance. Reason: An input file collection couldn't be resolved, making it impossible to determine task inputs. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#unresolvable_input for more details about this problem.
> ```

I guess I've seen this one too.
I'll check if I can reproduce again the issue above.

**Comment by marandaneto** [comment]
> Execution optimizations have been disabled for task ':examples:android-gradle-kts:lintVitalRelease' to ensure correctness due to the following reasons:
>   - Type 'LintPerVariantTask' property 'allInputs' cannot be resolved:  Cannot convert the provided notation to a File or URI: classes.jar (project :examples:android-gradle-kts). The following types/formats are supported:  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'. - A String or CharSequence URI, for example 'file:/usr/include'. - A File instance. - A Path instance. - A Directory instance. - A RegularFile instance. - A URI or URL instance. - A TextResource instance. Reason: An input file collection couldn't be resolved, making it impossible to determine task inputs. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#unresolvable_input for more details about this problem.
> ```

this one happens after migrating to Gradle 7.x so I guess we can ignore it for now

**Comment by cortinico** [comment]
All the "Execution optimizations have been disabled for task..." are fired by Gradle 7.0.
We could technically ignore them for now, but I'd rather try to solve them. Most of the time they highlights issues with Input/Outputs and task ordering.

**Comment by marandaneto** [comment]
yep, if its related to one of our tasks, for sure, the one you've shared, its an AGP task -> `lintVitalRelease`

**Comment by marandaneto** [comment]
closing it as its fixed by using the providers lazily instead of adding the task dependencies manually, can't reproduce it using the latest beta
