### ISSUE TITLE
NativeLib Directory Doesn't exist on Rebuild

### ISSUE THREAD

**Issue by colinrparker** [getsentry/sentry-android-gradle-plugin#98]
_Android Gradle Plugin:_
**4.1.3**

_Gradle:_
**6.8.3**

_Optimizer:_
- [ X]  ProGuard
- [ ]  R8

_Have you created the sentry.properties file?_
- [ ]  Yes -> where?
- [ X]  No

_SDKs:_
- [1.7.36 ]  sentry-android -> which version?
- [ ]  sentry-react-native -> which version?

---
I am trying to integrate the sentry-android-gradle plugin with a native library project.  For the sake of this bug report, we can use the [android-sample](https://github.com/getsentry/examples/tree/master/android).

The project successfully builds in Android Studio after I "Build->Clean Project" && "Build->Make Project".  However if I "Build->Rebuild" the project fails with the following error.

I am getting the following error on a rebuild:

`/Users/xx/sandbox/examples/android/app/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at /Users/xx/sandbox/examples/android/app/CMakeLists.txt:9 (include):
  include could not find load file:

    /Users/xx/sandbox/examples/android/app/build/nativeLib/gradle.mk
`
i.e. the nativeLib directory does not exists

**Steps to reproduce:**
- Build -> Rebuild

**Actual result:**

`Executing tasks: [clean, :app:assembleDebug] in project /Users/xx/sandbox/examples/android

> Configure project :app
getMappingFile(): Cannot query the value of this property because it has no value available.
WARNING: API 'variant.getMappingFile()' is obsolete and has been replaced with 'variant.getMappingFileProvider()'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMappingFile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
:app:external cmake build 
:app:external cmake build 

> Task :clean UP-TO-DATE
> Task :app:preBuild
> Task :app:preDebugBuild

> Task :app:externalNativeBuildCleanDebug
Clean native-sample armeabi-v7a
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/debug/armeabi-v7a'
[1/1] Cleaning all built files...
Cleaning... 2 files.
Clean native-sample arm64-v8a
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/debug/arm64-v8a'
[1/1] Cleaning all built files...
Cleaning... 2 files.
Clean native-sample x86
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/debug/x86'
[1/1] Cleaning all built files...
Cleaning... 2 files.
Clean native-sample x86_64
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/debug/x86_64'
[1/1] Cleaning all built files...
Cleaning... 2 files.

> Task :app:extractProguardFiles
> Task :app:preReleaseBuild

> Task :app:externalNativeBuildCleanRelease
Clean native-sample armeabi-v7a
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/release/armeabi-v7a'
[0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xx/sandbox/examples/android/app/.cxx/cmake/release/armeabi-v7a
[1/1] Cleaning all built files...
Cleaning... 0 files.
Clean native-sample arm64-v8a
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/release/arm64-v8a'
[0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xx/sandbox/examples/android/app/.cxx/cmake/release/arm64-v8a
[1/1] Cleaning all built files...
Cleaning... 0 files.
Clean native-sample x86
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/release/x86'
[0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xx/sandbox/examples/android/app/.cxx/cmake/release/x86
[1/1] Cleaning all built files...
Cleaning... 0 files.
Clean native-sample x86_64
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/release/x86_64'
[0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xx/sandbox/examples/android/app/.cxx/cmake/release/x86_64
[1/1] Cleaning all built files...
Cleaning... 0 files.

> Task :app:clean
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:processDebugMainManifest
> Task :app:processDebugManifest
> Task :app:generateJsonModelDebug FAILED
> Task :app:checkDebugAarMetadata
> Task :app:mergeDebugResources
> Task :app:javaPreCompileDebug
> Task :app:processDebugManifestForPackage

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonModelDebug'.
> /Users/xx/sandbox/examples/android/app/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at /Users/xx/sandbox/examples/android/app/CMakeLists.txt:9 (include):
    include could not find load file:
  
      /Users/xx/sandbox/examples/android/app/build/nativeLib/gradle.mk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
17 actionable tasks: 16 executed, 1 up-to-date`

**Expected result:**

`Executing tasks: [:app:assembleDebug] in project /Users/xx/sandbox/examples/android

> Configure project :app
getMappingFile(): Cannot query the value of this property because it has no value available.
WARNING: API 'variant.getMappingFile()' is obsolete and has been replaced with 'variant.getMappingFileProvider()'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMappingFile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
:app:external cmake build 
:app:external cmake build 

> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:generateJsonModelDebug

> Task :app:externalNativeBuildDebug
Build native-sample_armeabi-v7a
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/debug/armeabi-v7a
ninja: no work to do.
Build native-sample_arm64-v8a
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/debug/arm64-v8a
ninja: no work to do.
Build native-sample_x86
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/debug/x86
ninja: no work to do.
Build native-sample_x86_64
ninja: Entering directory `/Users/xx/sandbox/examples/android/app/.cxx/cmake/debug/x86_64
ninja: no work to do.

> Task :app:compileDebugSources
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:dexBuilderDebug UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :app:mergeDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:assembleDebug

BUILD SUCCESSFUL in 852ms
29 actionable tasks: 3 executed, 26 up-to-date`

**Comment by marandaneto** [comment]
@colinrparker thanks for reporting.

why do you think it's a `sentry-android-gradle-plugin` issue and not a Gradle or Android Gradle plugin?
what's your Gradle version?

**Comment by colinrparker** [comment]
@marandaneto I just updated the gradle version in the original question.

I believe that NativeLib folder is generated as part of the `com.ydq.android.gradle.build.tool:nativeBundle:1.0.7`'s import of the sentry-native libraries.  I believe this occurs as part of the `sentry-android-gradle-plugin' apply step during the `Configure project :app`. I found [this](https://github.com/howardpang/androidNativeBundle/issues/1) issue that seems related on the initial build.

When performing a rebuild, the `Configure project :app` step is run which creates the folders and then a clean occurs which deletes the files.

When performing the build, the clean never occurs so the folder's are present.

So, regarding Android Gradle vs. Sentry Android Gradle, I'm a newbie in this ecosystem.  But it seems like the sentry-android-gradle-plugin should be in charge of making certain that it's dependencies are run.

**Comment by marandaneto** [comment]
@colinrparker this plugin does not reference `com.ydq.android.gradle.build.tool:nativeBundle` at all., I'm still wondering if its actually an issue in this plugin or elsewhere, can you set up a repro case on GH? thanks

**Comment by colinrparker** [comment]
@marandaneto The [Sentry android-sample](https://github.com/getsentry/examples/tree/master/android) demonstrates this issue.  Just hit "Build -> Rebuild Project"

How does `com.ydq.android.gradle.build.tool:nativeBundle` know to import `sentry-android-ndk`?

`@MacBook-Pro nativeLib % tree
.
├── gradle.mk
├── io.sentry
│   └── sentry-android-ndk
│       └── jni
│           ├── arm64-v8a
│           │   ├── libsentry-android.so
│           │   └── libsentry.so
│           ├── armeabi-v7a
│           │   ├── libsentry-android.so
│           │   └── libsentry.so
│           ├── include
│           │   └── sentry.h
│           ├── x86
│           │   ├── libsentry-android.so
│           │   └── libsentry.so
│           └── x86_64
│               ├── libsentry-android.so
│               └── libsentry.so
└── tmp.mk

8 directories, 11 files`

**Comment by marandaneto** [comment]
@colinrparker via https://github.com/getsentry/examples/blob/master/android/app/CMakeLists.txt#L8-L11

you actually only need the `nativeBundle` plugin if you need to link the libraries, do you?

See https://docs.sentry.io/platforms/android/using-ndk/#allowing-the-compiler-to-link-libraries

if you don't apply `com.ydq.android.gradle.native-aar.import`, you don't see this error, hence seems like a https://github.com/howardpang/androidNativeBundle/issues issue

**Comment by marandaneto** [comment]
Closing in favor of https://github.com/howardpang/androidNativeBundle/issues/11

**Comment by colinrparker** [comment]
Thanks for your help @marandaneto
